import { DatabaseCardRecord } from "../database-experiment/contract";
import { SqliteRow } from "../database-experiment/sqlite-readonly-adapter";
import { CharacterAcquisitionRecord, CharacterDropReference, DatabaseCharacterAcquisitionCoverage, DatabaseCharacterAcquisitionDataset } from "./acquisition-contract";
import { ProgressionRawRow, ProgressionRowRef } from "./progression-contract";
import { CharacterSourceInput, streamDb1Cards } from "./source";

export type AcquisitionTables = Record<string, SqliteRow[]>;
const ref = (table: string, rowId: unknown): ProgressionRowRef => ({ table, rowId: String(rowId) });
const sourced = (table: string, row: SqliteRow): ProgressionRawRow => ({ values: row, provenance: { table, rowId: String(row.id), columns: Object.keys(row) } });
const dropKey = (value: CharacterDropReference): string => `${value.source.table}:${value.source.rowId}:${value.sourceColumn}:${value.cardId}`;

export async function buildDatabaseCharacterAcquisitionDataset(source: CharacterSourceInput, tables: AcquisitionTables, cardsInput: AsyncIterable<DatabaseCardRecord> = streamDb1Cards(source.artifactPath)): Promise<DatabaseCharacterAcquisitionDataset> {
    const rawRows = Object.keys(tables).sort().flatMap(table => tables[table].map(row => sourced(table, row))).sort((a, b) => `${a.provenance.table}:${a.provenance.rowId}`.localeCompare(`${b.provenance.table}:${b.provenance.rowId}`, undefined, { numeric: true }));
    const quests = new Map((tables.quests ?? []).map(row => [String(row.id), row]));
    const dropReferences: CharacterDropReference[] = [];
    for (const row of tables.sugoroku_map_boss_drop_items ?? []) if (row.item_type === "Card") { const questId = String(row.quest_id), cardId = String(row.item_id); dropReferences.push({ source: ref("sugoroku_map_boss_drop_items", row.id), sourceColumn: "item_id", questId, quest: quests.has(questId) ? ref("quests", questId) : undefined, cardId, itemTypeRaw: row.item_type, sourceKind: "boss_drop" }); }
    for (const row of tables.quest_drop_item_views ?? []) for (let slot = 1; slot <= 6; slot++) if (row[`item${slot}_type`] === "Card") { const questId = String(row.quest_id), cardId = String(row[`item${slot}_id`]); dropReferences.push({ source: ref("quest_drop_item_views", row.id), sourceColumn: `item${slot}_id`, questId, quest: quests.has(questId) ? ref("quests", questId) : undefined, cardId, itemTypeRaw: row[`item${slot}_type`], sourceKind: "quest_drop_preview" }); }
    dropReferences.sort((a, b) => dropKey(a).localeCompare(dropKey(b), undefined, { numeric: true }));
    const sourceCards: Array<{ cardId: string; cardUniqueInfoId?: string; collectionEntries: ProgressionRowRef[]; collectionEventIds: string[]; awakeningSourceRouteIds: string[]; reversibleExchangePartners: CharacterAcquisitionRecord["reversibleExchangePartners"] }> = [];
    for await (const card of cardsInput) sourceCards.push({ cardId: card.cardId, cardUniqueInfoId: card.ids.cardUniqueInfoId, collectionEntries: card.catalog.collectionEntries.map(row => ref(row.provenance.table, row.provenance.rowId)), collectionEventIds: [...new Set(card.catalog.collectionEntries.flatMap(row => row.values.event_id === null || row.values.event_id === undefined ? [] : [String(row.values.event_id)]))].sort((a, b) => Number(a) - Number(b)), awakeningSourceRouteIds: card.awakeningPaths.incoming.map(row => row.provenance.rowId).sort((a, b) => Number(a) - Number(b)), reversibleExchangePartners: card.formRelations.filter(row => row.kind.value === "reversible-exchange" && row.targetCardId).map(row => ({ targetCardId: row.targetCardId!, source: row.provenance })).sort((a, b) => `${a.targetCardId}:${a.source.table}:${a.source.rowId}`.localeCompare(`${b.targetCardId}:${b.source.table}:${b.source.rowId}`, undefined, { numeric: true })) });
    const knownCards = new Set(sourceCards.map(card => card.cardId)), dropsByCard = new Map<string, CharacterDropReference[]>();
    for (const drop of dropReferences) dropsByCard.set(drop.cardId, [...(dropsByCard.get(drop.cardId) ?? []), drop]);
    const cardsByUnique = new Map<string, typeof sourceCards>(); for (const card of sourceCards) if (card.cardUniqueInfoId) cardsByUnique.set(card.cardUniqueInfoId, [...(cardsByUnique.get(card.cardUniqueInfoId) ?? []), card]);
    const cards: CharacterAcquisitionRecord[] = sourceCards.map(card => {
        const drops = dropsByCard.get(card.cardId) ?? [], uniqueId = card.cardUniqueInfoId;
        return { cardId: card.cardId, collectionEntries: card.collectionEntries, collectionEventIds: card.collectionEventIds, stageDrops: drops, summonability: "unknown_no_first_party_relation_in_snapshot", f2p: { classification: "unknown", evidence: drops.map(drop => ({ kind: "first_party_stage_drop", source: drop.source, questId: drop.questId })) }, awakeningSourceRouteIds: card.awakeningSourceRouteIds, trainingPartnerCandidates: uniqueId ? (cardsByUnique.get(uniqueId) ?? []).filter(other => other.cardId !== card.cardId).map(other => ({ cardId: other.cardId, evidence: "derived_same_card_unique_info_id", cardUniqueInfoId: uniqueId })) : [], reversibleExchangePartners: card.reversibleExchangePartners, exclusiveSkillOrbCompatibility: "raw_only_owned_by_k4" } as CharacterAcquisitionRecord;
    }).sort((a, b) => Number(a.cardId) - Number(b.cardId));
    return { schemaVersion: 1, contract: "dokkan-database-characters-acquisition", contractVersion: "1.0.0", generatedAt: source.generatedAt, source: { snapshotVersion: source.snapshotVersion, databaseSha256: source.databaseSha256, db1ArtifactSha256: source.artifactSha256, itemTypeCardEvidence: "first-party-string-enum-plus-existing-E5-item-catalog-binding" }, policy: { schedulesExcluded: true, textUsedForF2pClassification: false, stageDropDoesNotProveF2p: true, derivedTrainingNeverFirstParty: true, summonDataAbsent: true }, rawRows, cards, unjoinedCardDropReferences: dropReferences.filter(drop => !knownCards.has(drop.cardId)) };
}

export function buildDatabaseCharacterAcquisitionCoverage(dataset: DatabaseCharacterAcquisitionDataset): DatabaseCharacterAcquisitionCoverage {
    const drops = [...dataset.cards.flatMap(card => card.stageDrops), ...dataset.unjoinedCardDropReferences], dropKeys = drops.map(dropKey), rawKeys = dataset.rawRows.map(row => `${row.provenance.table}:${row.provenance.rowId}`), candidates = dataset.cards.flatMap(card => card.trainingPartnerCandidates);
    return { schemaVersion: 1, rawRowCount: dataset.rawRows.length, cardCount: dataset.cards.length, collectionEntryCount: dataset.cards.reduce((sum, card) => sum + card.collectionEntries.length, 0), collectionEventIdCount: new Set(dataset.cards.flatMap(card => card.collectionEventIds)).size, stageDropReferenceCount: drops.length, stageDropCardCount: new Set(drops.map(drop => drop.cardId)).size, unjoinedCardDropReferenceCount: dataset.unjoinedCardDropReferences.length, missingQuestJoinCount: drops.filter(drop => !drop.quest).length, cardsWithStageDropEvidenceCount: dataset.cards.filter(card => card.stageDrops.length).length, assertedF2pCount: dataset.cards.filter(card => card.f2p.classification !== "unknown").length, assertedSummonableCount: dataset.cards.filter(card => card.summonability !== "unknown_no_first_party_relation_in_snapshot").length, derivedTrainingCandidateCount: candidates.length, unmarkedDerivedTrainingCandidateCount: candidates.filter(candidate => candidate.evidence !== "derived_same_card_unique_info_id").length, reversibleExchangePairCount: dataset.cards.reduce((sum, card) => sum + card.reversibleExchangePartners.length, 0), duplicateDropIdentityCount: dropKeys.length - new Set(dropKeys).size, duplicateRawRowIdentityCount: rawKeys.length - new Set(rawKeys).size, duplicateCardIdentityCount: dataset.cards.length - new Set(dataset.cards.map(card => card.cardId)).size };
}
