import { DatabaseCardRecord } from "../database-experiment/contract"; import { SqliteRow } from "../database-experiment/sqlite-readonly-adapter"; import { CharacterAssetGap, CharacterAssetReference, CharacterAssetRole, DatabaseCharacterAssetsCoverage, DatabaseCharacterAssetsDataset } from "./assets-contract"; import { ProgressionRawRow } from "./progression-contract"; import { CharacterSourceInput, streamDb1Cards } from "./source";
export type AssetTables = Record<string, SqliteRow[]>;
const id = (value: unknown): string | undefined => value === null || value === undefined || String(value) === "" || Number(value) === 0 ? undefined : String(value);
const sourced = (table: string, row: SqliteRow): ProgressionRawRow => ({ values: row, provenance: { table, rowId: String(row.id), columns: Object.keys(row) } });
const group = (rows: SqliteRow[], column: string) => { const map = new Map<string, SqliteRow[]>(); for (const row of rows) { const key = id(row[column]); if (key) map.set(key, [...(map.get(key) ?? []), row]); } return map; };
const byId = (rows: SqliteRow[]) => new Map(rows.map(row => [String(row.id), row]));
function reference(cardId: string, role: CharacterAssetRole, value: unknown, table: string, rowId: unknown, column: string, sourceColumns?: string[]): CharacterAssetReference | undefined { const actual = id(value); if (!actual) return undefined; const path = typeof value === "string" && !/^\d+$/.test(value); return { referenceId: `${cardId}:${role}:${table}:${rowId}:${column}:${actual}`, cardId, role, firstPartyValue: actual, source: { table, rowId: String(rowId), column, columns: sourceColumns }, assetKey: { value: path ? actual : `${role}:${actual}`, kind: path ? "first_party_path_or_script" : "derived_from_first_party_id" }, localFile: { status: "unknown_no_compatible_local_asset_catalog" }, delivery: "unknown_owned_by_server_campaign" }; }

export async function buildDatabaseCharacterAssetsDataset(source: CharacterSourceInput, tables: AssetTables, cardsInput: AsyncIterable<DatabaseCardRecord> = streamDb1Cards(source.artifactPath)): Promise<DatabaseCharacterAssetsDataset> {
    const rawRows = Object.keys(tables).sort().flatMap(table => tables[table].map(row => sourced(table, row))).sort((a, b) => `${a.provenance.table}:${a.provenance.rowId}`.localeCompare(`${b.provenance.table}:${b.provenance.rowId}`, undefined, { numeric: true }));
    const cards: Array<{ cardId: string; resourceId?: string; resourceSource: DatabaseCardRecord["card"]["provenance"]; forms: DatabaseCardRecord["formRelations"] }> = [];
    for await (const card of cardsInput) cards.push({ cardId: card.cardId, resourceId: card.ids.resourceId, resourceSource: card.card.provenance, forms: card.formRelations });
    const resources = new Map(cards.map(card => [card.cardId, { resourceId: card.resourceId, source: card.resourceSource }])), references: CharacterAssetReference[] = [], gaps: CharacterAssetGap[] = [];
    let relationTargetCount = 0, unresolvedTargetCount = 0;
    for (const card of cards) { const base = reference(card.cardId, "card_resource_bundle", card.resourceId, card.resourceSource.table, card.resourceSource.rowId, "resource_id", card.resourceSource.columns); if (base) references.push(base); else gaps.push({ gapId: `${card.cardId}:card_resource_bundle`, cardId: card.cardId, role: "card_resource_bundle", reason: "missing_resource_id", source: { table: card.resourceSource.table, rowId: card.resourceSource.rowId, column: "resource_id", columns: card.resourceSource.columns } }); for (const form of card.forms) if (form.targetCardId) { relationTargetCount++; const target = resources.get(form.targetCardId); if (target?.resourceId) { const item = reference(card.cardId, "form_resource_bundle", target.resourceId, target.source.table, target.source.rowId, "resource_id", target.source.columns)!; item.referenceId = `${card.cardId}:form_resource_bundle:${form.provenance.table}:${form.provenance.rowId}:${form.targetCardId}:${target.resourceId}`; item.relationSource = form.provenance; references.push(item); } else { unresolvedTargetCount++; gaps.push({ gapId: `${card.cardId}:form_resource_bundle:${form.targetCardId}:${form.provenance.table}:${form.provenance.rowId}`, cardId: card.cardId, targetCardId: form.targetCardId, role: "form_resource_bundle", reason: target ? "missing_resource_id" : "target_card_outside_corpus", source: target ? { table: target.source.table, rowId: target.source.rowId, column: "resource_id", columns: target.source.columns } : { table: form.provenance.table, rowId: form.provenance.rowId, columns: form.provenance.columns }, relationSource: form.provenance }); } } }
    const selected = new Set(cards.map(card => card.cardId)), motions = group(tables.card_motions ?? [], "card_id"), specials = group(tables.card_specials ?? [], "card_id"), specialViews = byId(tables.special_views ?? []);
    const activeRelations = group(tables.card_active_skills ?? [], "card_id"), activeSets = byId(tables.active_skill_sets ?? []), standbyRelations = group(tables.card_standby_skill_set_relations ?? [], "card_id"), standbySets = byId(tables.standby_skill_sets ?? []), finishRelations = group(tables.card_finish_skill_set_relations ?? [], "card_id"), finishSets = byId(tables.finish_skill_sets ?? []);
    const add = (value: CharacterAssetReference | undefined) => { if (value) references.push(value); }, addViewScript = (cardId: string, viewId: unknown) => { const view = specialViews.get(String(viewId)); if (view) add(reference(cardId, "animation_script", view.script_name, "special_views", view.id, "script_name")); };
    for (const cardId of selected) {
        for (const row of motions.get(cardId) ?? []) add(reference(cardId, "card_motion", row.filename, "card_motions", row.id, "filename"));
        for (const row of specials.get(cardId) ?? []) { add(reference(cardId, "super_view", row.view_id, "card_specials", row.id, "view_id")); add(reference(cardId, "super_asset", row.special_asset_id, "card_specials", row.id, "special_asset_id")); const view = specialViews.get(String(row.view_id)); if (view) { add(reference(cardId, "super_script", view.script_name, "special_views", view.id, "script_name")); add(reference(cardId, "card_motion", view.special_motion, "special_views", view.id, "special_motion")); } }
        for (const row of activeRelations.get(cardId) ?? []) { const set = activeSets.get(String(row.active_skill_set_id)); if (set) { add(reference(cardId, "active_view", set.special_view_id, "active_skill_sets", set.id, "special_view_id")); add(reference(cardId, "active_costume_view", set.costume_special_view_id, "active_skill_sets", set.id, "costume_special_view_id")); add(reference(cardId, "bgm", set.bgm_id, "active_skill_sets", set.id, "bgm_id")); addViewScript(cardId, set.special_view_id); addViewScript(cardId, set.costume_special_view_id); } }
        for (const row of standbyRelations.get(cardId) ?? []) { const set = standbySets.get(String(row.standby_skill_set_id)); if (set) { add(reference(cardId, "standby_view", set.special_view_id, "standby_skill_sets", set.id, "special_view_id")); add(reference(cardId, "standby_costume_view", set.costume_special_view_id, "standby_skill_sets", set.id, "costume_special_view_id")); add(reference(cardId, "standby_icon", set.ingame_icon_path, "standby_skill_sets", set.id, "ingame_icon_path")); add(reference(cardId, "bgm", set.bgm_id, "standby_skill_sets", set.id, "bgm_id")); addViewScript(cardId, set.special_view_id); addViewScript(cardId, set.costume_special_view_id); } }
        for (const row of finishRelations.get(cardId) ?? []) { const set = finishSets.get(String(row.finish_skill_set_id)); if (set) { add(reference(cardId, "finish_view", set.special_view_id, "finish_skill_sets", set.id, "special_view_id")); add(reference(cardId, "finish_costume_view", set.costume_special_view_id, "finish_skill_sets", set.id, "costume_special_view_id")); add(reference(cardId, "bgm", set.bgm_id, "finish_skill_sets", set.id, "bgm_id")); addViewScript(cardId, set.special_view_id); addViewScript(cardId, set.costume_special_view_id); } }
    }
    const uniqueReferences = [...new Map(references.map(item => [item.referenceId, item])).values()]; references.length = 0; references.push(...uniqueReferences); references.sort((a, b) => a.referenceId.localeCompare(b.referenceId, undefined, { numeric: true }));
    gaps.sort((a, b) => a.gapId.localeCompare(b.gapId, undefined, { numeric: true })); return { schemaVersion: 1, contract: "dokkan-database-characters-assets", contractVersion: "1.0.0", generatedAt: source.generatedAt, source: { snapshotVersion: source.snapshotVersion, databaseSha256: source.databaseSha256, db1ArtifactSha256: source.artifactSha256 }, policy: { endpointsDiscovered: false, catalogsDownloaded: false, resourceBundleNotClaimedAsPortraitOrCardArt: true, rarityTypeFrameMapping: "unknown", entranceAnimationGrouping: "unknown", domainAnimationGrouping: "unknown", deliveryOwnedElsewhere: true }, rawRows, references, gaps, formResourceAudit: { relationTargetCount, unresolvedTargetCount } };
}
export function buildDatabaseCharacterAssetsCoverage(dataset: DatabaseCharacterAssetsDataset): DatabaseCharacterAssetsCoverage {
    const roles: CharacterAssetRole[] = ["card_resource_bundle", "card_motion", "super_view", "super_asset", "super_script", "animation_script", "active_view", "active_costume_view", "standby_view", "standby_costume_view", "standby_icon", "finish_view", "finish_costume_view", "bgm", "form_resource_bundle"], roleCounts = Object.fromEntries(roles.map(role => [role, 0])) as Record<CharacterAssetRole, number>; dataset.references.forEach(item => roleCounts[item.role]++); const rawKeys = dataset.rawRows.map(row => `${row.provenance.table}:${row.provenance.rowId}`);
    const relationRows = (table: string) => dataset.rawRows.filter(row => row.provenance.table === table), setIds = (table: string) => new Set(relationRows(table).map(row => row.provenance.rowId)); const specialViewIds = setIds("special_views");
    return { schemaVersion: 1, rawRowCount: dataset.rawRows.length, referenceCount: dataset.references.length, referencedCardCount: new Set(dataset.references.map(item => item.cardId)).size, roleCounts, firstPartyPathOrScriptCount: dataset.references.filter(item => item.assetKey.kind === "first_party_path_or_script").length, derivedKeyCount: dataset.references.filter(item => item.assetKey.kind === "derived_from_first_party_id").length, provedLocalFileCount: 0, unknownDeliveryCount: dataset.references.filter(item => item.delivery === "unknown_owned_by_server_campaign").length, missingCardResourceCount: dataset.gaps.filter(gap => gap.role === "card_resource_bundle").length,
        missingFormTargetCount: dataset.gaps.filter(gap => gap.role === "form_resource_bundle").length,
        missingActionSetCount: relationRows("card_active_skills").filter(row => !setIds("active_skill_sets").has(String(row.values.active_skill_set_id))).length + relationRows("card_standby_skill_set_relations").filter(row => !setIds("standby_skill_sets").has(String(row.values.standby_skill_set_id))).length + relationRows("card_finish_skill_set_relations").filter(row => !setIds("finish_skill_sets").has(String(row.values.finish_skill_set_id))).length,
        missingSpecialViewCount: dataset.references.filter(item => ["super_view", "active_view", "active_costume_view", "standby_view", "standby_costume_view", "finish_view", "finish_costume_view"].includes(item.role) && !specialViewIds.has(item.firstPartyValue)).length, duplicateReferenceIdentityCount: dataset.references.length - new Set(dataset.references.map(item => item.referenceId)).size, duplicateRawRowIdentityCount: rawKeys.length - new Set(rawKeys).size };
}
