import { mkdir, writeFile } from "fs/promises"; import { resolve } from "path";
import { buildDeterministicJsonGzipArtifact, sha256Bytes } from "./artifact"; import { AcquisitionTables, buildDatabaseCharacterAcquisitionCoverage, buildDatabaseCharacterAcquisitionDataset } from "./acquisition-builder"; import { validateDatabaseCharacterAcquisitionDataset } from "./acquisition-validator"; import { assertPinnedArtifactFile, assertPinnedDatabaseFile, readCharacterSourceInput, readPinnedDatabaseTable } from "./source";
const COLUMNS: Record<string, string[]> = {
    collection_cards: ["id", "collection_unique_id", "card_id", "event_id", "priority", "created_at", "updated_at"], quests: ["id", "area_id", "name", "prev_quest_id", "created_at", "updated_at"], sugoroku_map_boss_drop_items: ["id", "sugoroku_map_id", "quest_id", "drop_type", "item_id", "item_type", "card_exp_init", "created_at", "updated_at"], quest_drop_item_views: ["id", "quest_id", "difficulties", "item1_id", "item1_type", "item2_id", "item2_type", "item3_id", "item3_type", "item4_id", "item4_type", "item5_id", "item5_type", "item6_id", "item6_type", "created_at", "updated_at"],
    training_fields: ["id", "level_bg_id", "name", "description", "rarity", "zeni", "exp", "elements", "multiplier", "addend", "card_training_field_exp_up_prob_id", "created_at", "updated_at"], training_items: ["id", "name", "description", "element", "exp", "rarity", "zeni_to_use", "created_at", "updated_at"], card_training_field_exp_up_probs: ["id", "key", "effect", "success_prob_percent", "created_at", "updated_at"], card_training_skill_lv_up_probs: ["id", "rarity", "n", "r", "sr", "ssr", "ur", "lr"], card_training_skill_lvs: ["id", "card_id", "skill_lv", "condition", "probability", "created_at", "updated_at"], item_card_properties: ["id", "card_id", "exp", "created_at", "updated_at"],
};
function arg(name: string): string | undefined { const index = process.argv.indexOf(name); return index < 0 ? undefined : process.argv[index + 1]; }
async function run() { const inputDir = arg("--input-dir"), database = arg("--database"); if (!inputDir || !database) throw new Error("--input-dir and --database are required"); const outputDir = resolve(arg("--output-dir") ?? "data/database-characters/k5"); let peakRssBytes = process.memoryUsage().rss; const timer = setInterval(() => peakRssBytes = Math.max(peakRssBytes, process.memoryUsage().rss), 25);
    try { const source = await readCharacterSourceInput(inputDir), tables: AcquisitionTables = {}; for (const [table, columns] of Object.entries(COLUMNS)) tables[table] = await readPinnedDatabaseTable(database, table, columns); await assertPinnedDatabaseFile(database);
        const generate = async () => { const dataset = await buildDatabaseCharacterAcquisitionDataset(source, tables), coverage = buildDatabaseCharacterAcquisitionCoverage(dataset), validation = validateDatabaseCharacterAcquisitionDataset(dataset, coverage); if (!validation.valid) throw new Error(`${validation.failures.join("; ")} coverage=${JSON.stringify(coverage)}`); return { artifact: buildDeterministicJsonGzipArtifact(dataset), coverage, validation }; };
        const first = await generate(), second = await generate(); if (!first.artifact.gzip.equals(second.artifact.gzip)) throw new Error("K5 two-generation byte identity failed"); await assertPinnedArtifactFile(source.artifactPath, { sha256: source.artifactSha256, sizeBytes: source.artifactSizeBytes }); await assertPinnedDatabaseFile(database);
        const coverageBytes = `${JSON.stringify(first.coverage, null, 2)}\n`, validationBytes = `${JSON.stringify(first.validation, null, 2)}\n`; const manifest = { schemaVersion: 1, contractVersion: "1.0.0", generatedAt: source.generatedAt, fileName: "database-characters-k5-acquisition.json.gz", compression: "gzip", sha256: first.artifact.sha256, sizeBytes: first.artifact.gzip.length, uncompressedSizeBytes: first.artifact.json.length, sourceSnapshotVersion: source.snapshotVersion, sourceDatabaseSha256: source.databaseSha256, sourceDb1ArtifactSha256: source.artifactSha256, consumedTables: Object.keys(COLUMNS), coverageFile: "database-characters-k5-coverage.json", coverageSha256: sha256Bytes(coverageBytes), coverageSizeBytes: Buffer.byteLength(coverageBytes), validationFile: "database-characters-k5-validation.json", validationSha256: sha256Bytes(validationBytes), validationSizeBytes: Buffer.byteLength(validationBytes) };
        peakRssBytes = Math.max(peakRssBytes, process.memoryUsage().rss); if (peakRssBytes >= 1_073_741_824) throw new Error(`K5 exceeded 1 GiB RSS ceiling: ${peakRssBytes}`); await mkdir(outputDir, { recursive: true }); await Promise.all([writeFile(resolve(outputDir, manifest.fileName), first.artifact.gzip), writeFile(resolve(outputDir, "database-characters-k5-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`), writeFile(resolve(outputDir, manifest.coverageFile), coverageBytes), writeFile(resolve(outputDir, manifest.validationFile), validationBytes)]); console.log(JSON.stringify({ outputDir, manifest, coverage: first.coverage, twoGenerationByteIdentical: true, peakRssBytes }, null, 2));
    } finally { clearInterval(timer); } }
if (require.main === module) run().catch(error => { console.error(error); process.exitCode = 1; });
