import { DatabaseCardRecord, SourcedRow } from "../database-experiment/contract";
import { SqliteRow } from "../database-experiment/sqlite-readonly-adapter";
import { CharacterProgressionCard, DatabaseCharacterProgressionCoverage, DatabaseCharacterProgressionDataset, EquipmentSkillOrbReference, ProgressionRawRow, ProgressionRowRef } from "./progression-contract";
import { CharacterSourceInput, streamDb1Cards } from "./source";

export type ProgressionTables = Record<string, SqliteRow[]>;
const id = (value: unknown): string | undefined => value === null || value === undefined || String(value) === "" ? undefined : String(value);
const numeric = (value: unknown): number | null => Number.isFinite(Number(value)) ? Number(value) : null;
const hasReference = (value: unknown): boolean => value !== null && value !== undefined && Number(value) !== 0;
const ref = (table: string, rowId: string): ProgressionRowRef => ({ table, rowId });
const sourced = (table: string, row: SqliteRow): ProgressionRawRow => ({ values: row, provenance: { table, rowId: String(row.id), columns: Object.keys(row) } });
const group = (rows: SqliteRow[], column: string): Map<string, SqliteRow[]> => { const result = new Map<string, SqliteRow[]>(); for (const row of rows) { const key = id(row[column]); if (key) result.set(key, [...(result.get(key) ?? []), row]); } return result; };
const stateId = (cardId: string, state: DatabaseCardRecord["skillStates"][number]): string => state.growthStep ? `card-state:${cardId}:growth:${state.growthStep.provenance.rowId}` : `card-state:${cardId}:initial`;

export async function buildDatabaseCharacterProgressionDataset(source: CharacterSourceInput, tables: ProgressionTables, cardsInput: AsyncIterable<DatabaseCardRecord> = streamDb1Cards(source.artifactPath)): Promise<DatabaseCharacterProgressionDataset> {
    const rawRows = Object.keys(tables).sort().flatMap(table => tables[table].map(row => sourced(table, row))).sort((a, b) => `${a.provenance.table}:${a.provenance.rowId}`.localeCompare(`${b.provenance.table}:${b.provenance.rowId}`, undefined, { numeric: true }));
    const awakenSets = new Map((tables.card_awakening_sets ?? []).map(row => [String(row.id), row]));
    const awakeningsBySet = group(tables.card_awakenings ?? [], "card_awakening_set_id");
    const awakeningItems = new Map((tables.awakening_items ?? []).map(row => [String(row.id), row]));
    const growthsByType = group(tables.card_growths ?? [], "grow_type"), optimalByType = group(tables.optimal_awakening_growths ?? [], "optimal_awakening_grow_type"), expsByType = group(tables.card_exps ?? [], "exp_type");
    const boards = new Map((tables.potential_boards ?? []).map(row => [String(row.id), row])), squaresByBoard = group(tables.potential_squares ?? [], "potential_board_id");
    const cards: CharacterProgressionCard[] = [];
    for await (const card of cardsInput) {
        const boardId = card.ids.potentialBoardId, board = boardId ? boards.get(boardId) : undefined;
        cards.push({ cardId: card.cardId, playerCardStats: { hpInitial: card.stats.hpInitial, hpMax: card.stats.hpMax, atkInitial: card.stats.atkInitial, atkMax: card.stats.atkMax, defInitial: card.stats.defInitial, defMax: card.stats.defMax, source: { table: "cards", rowId: card.card.provenance.rowId, columns: ["hp_init", "hp_max", "atk_init", "atk_max", "def_init", "def_max"] } },
            statDomains: { playerCard: "supported_raw", enemyRuntime: "not_in_contract", displayed: "unknown", calculatedCombat: "not_projected" }, rarityRaw: card.card.values.rarity,
            growthProfile: { growTypeRaw: card.card.values.grow_type, cardGrowthStatus: !hasReference(card.card.values.grow_type) ? "not_applicable" : growthsByType.has(String(card.card.values.grow_type)) ? "supported" : "unknown", cardGrowthRows: (growthsByType.get(String(card.card.values.grow_type)) ?? []).map(row => ref("card_growths", String(row.id))), optimalAwakeningGrowTypeRaw: card.card.values.optimal_awakening_grow_type, optimalAwakeningGrowthStatus: !hasReference(card.card.values.optimal_awakening_grow_type) ? "not_applicable" : optimalByType.has(String(card.card.values.optimal_awakening_grow_type)) ? "supported" : "unknown", optimalAwakeningGrowthRows: (optimalByType.get(String(card.card.values.optimal_awakening_grow_type)) ?? []).map(row => ref("optimal_awakening_growths", String(row.id))) },
            experienceProfile: { expTypeRaw: card.card.values.exp_type, status: !hasReference(card.card.values.exp_type) ? "not_applicable" : expsByType.has(String(card.card.values.exp_type)) ? "supported" : "unknown", rows: (expsByType.get(String(card.card.values.exp_type)) ?? []).map(row => ref("card_exps", String(row.id))) },
            states: card.skillStates.map(state => ({ stateId: stateId(card.cardId, state), sourceStateKey: state.stateKey, releaseState: state.releaseState, growthStep: state.growthStep ? { table: state.growthStep.provenance.table, rowId: state.growthStep.provenance.rowId } : undefined, growthStepNumber: state.growthStep ? Number(state.growthStep.values.step) : undefined, maxLevel: state.maxLevel, maxSuperAttackLevel: state.maxSuperAttackLevel, statOverride: "unknown_not_present_in_source_contract" })),
            potential: { boardId, boardStatus: board ? "supported" : "unknown", board: board ? ref("potential_boards", String(board.id)) : undefined, squareRows: boardId ? (squaresByBoard.get(boardId) ?? []).map(row => ref("potential_squares", String(row.id))) : [] },
            awakeningRequirements: card.awakeningPaths.outgoing.map(route => { const setId = id(route.values.card_awakening_set_id), set = setId ? awakenSets.get(setId) : undefined; return { route: { table: route.provenance.table, rowId: route.provenance.rowId }, awakeningSetId: setId, set: set ? ref("card_awakening_sets", String(set.id)) : undefined, requirements: (setId ? awakeningsBySet.get(setId) ?? [] : []).map(row => { const itemId = String(row.awakening_item_id), item = awakeningItems.get(itemId); return { row: ref("card_awakenings", String(row.id)), itemId, item: item ? ref("awakening_items", String(item.id)) : undefined, quantity: numeric(row.quantity) }; }) }; }) });
    }
    const limitationBySet = group(tables.equipment_skill_limitations ?? [], "equipment_skill_limitation_set_id"), skillsByItem = group(tables.equipment_skills ?? [], "equipment_skill_item_id");
    const equipmentSkillOrbs: EquipmentSkillOrbReference[] = (tables.equipment_skill_items ?? []).map(row => { const setId = id(row.equipment_skill_limitation_set_id); return { itemId: String(row.id), row: ref("equipment_skill_items", String(row.id)), limitationSetId: setId, limitationRows: setId ? (limitationBySet.get(setId) ?? []).map(item => ref("equipment_skill_limitations", String(item.id))) : [], skillRows: (skillsByItem.get(String(row.id)) ?? []).map(item => ref("equipment_skills", String(item.id))), compatibilitySemantics: "raw_structural_only" }; });
    cards.sort((a, b) => Number(a.cardId) - Number(b.cardId)); equipmentSkillOrbs.sort((a, b) => Number(a.itemId) - Number(b.itemId));
    return { schemaVersion: 1, contract: "dokkan-database-characters-progression", contractVersion: "1.0.0", generatedAt: source.generatedAt, source: { snapshotVersion: source.snapshotVersion, databaseSha256: source.databaseSha256, db1ArtifactSha256: source.artifactSha256, lineage: "validated-db1-plus-focused-sqlite-no-combat-calculation" }, policy: { playerStatsNeverUsedAsEnemyStats: true, combatCalculationImplemented: false, potentialSemanticsPromoted: false, equipmentLimitationSemanticsPromoted: false, saAndLeaderMechanicsOwnedByK3: true }, rawRows, cards, equipmentSkillOrbs };
}

export function buildDatabaseCharacterProgressionCoverage(dataset: DatabaseCharacterProgressionDataset): DatabaseCharacterProgressionCoverage {
    const rawKeys = new Set(dataset.rawRows.map(row => `${row.provenance.table}:${row.provenance.rowId}`)), squareIds = new Set(dataset.rawRows.filter(row => row.provenance.table === "potential_squares").map(row => row.provenance.rowId));
    const squareRelations = dataset.rawRows.filter(row => row.provenance.table === "potential_square_relations");
    const rows = (table: string) => dataset.rawRows.filter(row => row.provenance.table === table), rowIds = (table: string) => new Set(rows(table).map(row => row.provenance.rowId));
    const potentialEventIds = rowIds("potential_events"), conditionSetIds = rowIds("potential_square_condition_sets"), conditionIds = rowIds("potential_square_conditions"), potentialSkillIds = rowIds("potential_skills"), equipmentItemIds = rowIds("equipment_skill_items");
    const itemLimitationSetIds = new Set(rows("equipment_skill_items").filter(row => hasReference(row.values.equipment_skill_limitation_set_id)).map(row => String(row.values.equipment_skill_limitation_set_id))), limitationSetIds = new Set(rows("equipment_skill_limitations").map(row => String(row.values.equipment_skill_limitation_set_id)));
    const requirements = dataset.cards.flatMap(card => card.awakeningRequirements.flatMap(route => route.requirements));
    const allStates = dataset.cards.flatMap(card => card.states), allRoutes = dataset.cards.flatMap(card => card.awakeningRequirements);
    return { schemaVersion: 1, rawRowCount: dataset.rawRows.length, cardCount: dataset.cards.length, stateCount: allStates.length, ezaStateCount: allStates.filter(state => state.releaseState === "eza").length, sezaStateCount: allStates.filter(state => state.releaseState === "seza").length, unknownStateCount: allStates.filter(state => state.releaseState === "unknown").length,
        awakeningRouteCount: allRoutes.length, awakeningRequirementCount: requirements.length, referencedAwakeningItemCount: new Set(requirements.map(value => value.itemId)).size, missingAwakeningSetCount: allRoutes.filter(route => route.awakeningSetId && !route.set).length, missingAwakeningItemCount: requirements.filter(value => !value.item).length,
        missingCardGrowthProfileCount: dataset.cards.filter(card => card.growthProfile.cardGrowthStatus === "unknown").length, missingOptimalAwakeningGrowthProfileCount: dataset.cards.filter(card => card.growthProfile.optimalAwakeningGrowthStatus === "unknown").length, missingExperienceProfileCount: dataset.cards.filter(card => card.experienceProfile.status === "unknown").length,
        potentialBoardCardCount: dataset.cards.filter(card => card.potential.boardId).length, missingPotentialBoardCount: dataset.cards.filter(card => card.potential.boardId && !card.potential.board).length, potentialBoardWithoutSquaresCount: dataset.cards.filter(card => card.potential.board && card.potential.squareRows.length === 0).length, potentialSquareCount: squareIds.size, potentialSquareRelationCount: squareRelations.length, potentialRootRelationCount: squareRelations.filter(row => row.values.prev_potential_square_id === null).length, danglingPotentialSquareRelationCount: squareRelations.filter(row => !squareIds.has(String(row.values.potential_square_id)) || (row.values.prev_potential_square_id !== null && !squareIds.has(String(row.values.prev_potential_square_id)))).length,
        danglingPotentialSquareEventCount: rows("potential_squares").filter(row => hasReference(row.values.event_id) && !potentialEventIds.has(String(row.values.event_id))).length, danglingPotentialSquareConditionSetCount: rows("potential_squares").filter(row => hasReference(row.values.condition_set_id) && !conditionSetIds.has(String(row.values.condition_set_id))).length, danglingPotentialConditionRelationCount: rows("potential_square_condition_set_relations").filter(row => !conditionSetIds.has(String(row.values.condition_set_id)) || !conditionIds.has(String(row.values.condition_id))).length,
        equipmentSkillOrbCount: dataset.equipmentSkillOrbs.length, equipmentSkillRowCount: rows("equipment_skills").length, equipmentLimitationRowCount: rows("equipment_skill_limitations").length, danglingEquipmentSkillItemCount: rows("equipment_skills").filter(row => !equipmentItemIds.has(String(row.values.equipment_skill_item_id))).length, danglingEquipmentPotentialSkillCount: rows("equipment_skills").filter(row => hasReference(row.values.potential_skill_id) && !potentialSkillIds.has(String(row.values.potential_skill_id))).length, danglingPotentialSkillLevelCount: rows("potential_skill_lv_values").filter(row => !potentialSkillIds.has(String(row.values.potential_skill_id))).length, missingEquipmentLimitationSetCount: [...itemLimitationSetIds].filter(value => !limitationSetIds.has(value)).length, orphanEquipmentLimitationSetCount: [...limitationSetIds].filter(value => !itemLimitationSetIds.has(value)).length,
        duplicateRawRowIdentityCount: dataset.rawRows.length - rawKeys.size, duplicateCardIdentityCount: dataset.cards.length - new Set(dataset.cards.map(card => card.cardId)).size };
}
