import { createHash } from "crypto";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { getHeapStatistics } from "v8";
import { collectCaptureSensitiveValues, scanTextsForSecrets } from "../database-server-captures/capture-secret-scan";
import { SpecialM6MemoryEvidence } from "./special-m6-contract";
import { buildSpecialM6, validateSpecialM6 } from "./special-m6-readiness";

const root = resolve(process.cwd()); if (getHeapStatistics().heap_size_limit >= 1024 * 1024 * 1024) throw new Error("M6 requires a Node heap below 1 GiB"); const read = (path: string) => readFileSync(resolve(root, path), "utf8"), artifacts = ["m0", "m1", "m2", "m3", "m4", "m5"].map((gate, index) => { const names = ["special-m0-inventory.json", "special-m1-pettan.json", "special-m2-burst.json", "special-m3-database-joins.json", "special-m4-lossless-facts.json", "special-m5-shadow-parity.json"]; return { gate: gate as "m0" | "m1" | "m2" | "m3" | "m4" | "m5", fileName: names[index], text: read(`data/database-special-modes-captures/${gate}/${names[index]}`) }; }), validations = ["m0", "m1", "m2", "m3", "m4", "m5"].map((gate, index) => JSON.parse(read(`data/database-special-modes-captures/${gate}/special-${gate}-validation.json`))), models = artifacts.map(value => JSON.parse(value.text)), fixtureText = read("database-special-modes-captures/fixtures/special-modes-synthetic-shapes.json"), memory = JSON.parse(read("database-special-modes-captures/special-m6-memory-evidence.json")) as SpecialM6MemoryEvidence, dataset = buildSpecialM6({ m0: models[0], m0Validation: validations[0], m1: models[1], m1Validation: validations[1], m2: models[2], m2Validation: validations[2], m3: models[3], m3Validation: validations[3], m4: models[4], m4Validation: validations[4], m5: models[5], m5Validation: validations[5], artifactTexts: artifacts, fixtureText, memory }), validation = validateSpecialM6(dataset), text = `${JSON.stringify(dataset, null, 2)}\n`, manifest = { schemaVersion: 1, contractVersion: dataset.contractVersion, generatedAt: dataset.generatedAt, fileName: "special-m6-readiness.json", sizeBytes: Buffer.byteLength(text), sha256: createHash("sha256").update(text).digest("hex") }, sourceManifest = { schemaVersion: 1 as const, inputRoot: "special", captures: [{ captureId: "burst-mode-2026-08-10", path: "burst_mode.har" }, { captureId: "pettan-not-live-2026-08-10", path: "pettan_but_not_live.har" }] }, scan = scanTextsForSecrets(collectCaptureSensitiveValues(sourceManifest, { special: "D:\\Dokkan\\har logs\\08-10" }), [...artifacts.map(value => ({ name: value.fileName, text: value.text })), { name: "special-m6-readiness.json", text }, { name: "special-modes-synthetic-shapes.json", text: fixtureText }]); if (!scan.valid) throw new Error("M6 secret scan failed"); const out = resolve(root, "data/database-special-modes-captures/m6"); mkdirSync(out, { recursive: true }); writeFileSync(resolve(out, manifest.fileName), text); writeFileSync(resolve(out, "special-m6-validation.json"), `${JSON.stringify(validation, null, 2)}\n`); writeFileSync(resolve(out, "special-m6-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`); writeFileSync(resolve(out, "special-m6-secret-scan.json"), `${JSON.stringify(scan, null, 2)}\n`); process.stdout.write(`${JSON.stringify({ ...validation, secretScanValid: scan.valid, exactCapturedSecretMatches: scan.exactCapturedSecretMatches })}\n`);
