import { createHash } from "crypto";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { getHeapStatistics } from "v8";
import { SpecialM1Dataset } from "./special-m1-contract";
import { SpecialM2Dataset } from "./special-m2-contract";
import { SpecialM3Dataset } from "./special-m3-contract";
import { buildSpecialM4, validateSpecialM4 } from "./special-m4-lossless";
const root = resolve(process.cwd()); if (getHeapStatistics().heap_size_limit >= 1024 * 1024 * 1024) throw new Error("M4 requires a Node heap below 1 GiB"); const read = (path: string) => readFileSync(resolve(root, path), "utf8"), m1Text = read("data/database-special-modes-captures/m1/special-m1-pettan.json"), m2Text = read("data/database-special-modes-captures/m2/special-m2-burst.json"), m3Text = read("data/database-special-modes-captures/m3/special-m3-database-joins.json"), m1 = JSON.parse(m1Text) as SpecialM1Dataset, m2 = JSON.parse(m2Text) as SpecialM2Dataset, m3 = JSON.parse(m3Text) as SpecialM3Dataset, dataset = buildSpecialM4(m1, m1Text, m2, m2Text, m3, m3Text), validation = validateSpecialM4(dataset, m1, m2, m3), text = `${JSON.stringify(dataset, null, 2)}\n`, manifest = { schemaVersion: 1, contractVersion: dataset.contractVersion, generatedAt: dataset.generatedAt, fileName: "special-m4-lossless-facts.json", sizeBytes: Buffer.byteLength(text), sha256: createHash("sha256").update(text).digest("hex") }, out = resolve(root, "data/database-special-modes-captures/m4"); mkdirSync(out, { recursive: true }); writeFileSync(resolve(out, manifest.fileName), text); writeFileSync(resolve(out, "special-m4-validation.json"), `${JSON.stringify(validation, null, 2)}\n`); writeFileSync(resolve(out, "special-m4-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`); process.stdout.write(`${JSON.stringify(validation)}\n`);
