import { strict as assert } from "assert";
import { buildSpecialM0, sanitizeSpecialM0Entry } from "./special-m0-audit";
import { SpecialM0SourceLock } from "./special-m0-contract";
import { createHash } from "crypto";

describe("special modes M0 offline inventory", () => {
    it("keeps only names and metadata while classifying representations", () => { const entry = sanitizeSpecialM0Entry("burst-mode-2026-08-10", { startedDateTime: "2026-08-10T12:00:00Z", request: { method: "POST", url: "https://ishin-global.aktsk.com/sd/packs/open?token=synthetic-secret", headers: [{ name: "Authorization", value: "synthetic-secret" }], postData: { mimeType: "application/json", text: "{\"secret\":\"synthetic-secret\"}" } }, response: { status: 200, headers: [], content: { mimeType: "application/x-zstd", encoding: "base64", text: "KLUv/Q==" } } }, 0); const text = JSON.stringify(entry); assert.equal(entry.trafficClass, "mutation_observed"); assert.equal(entry.response.representation, "zstandard_base64"); assert.deepEqual(entry.sensitiveRequestHeaderNames, ["authorization"]); assert(!text.includes("synthetic-secret")); });
    it("distinguishes cache and binary bodies", () => { const cached = sanitizeSpecialM0Entry("burst-mode-2026-08-10", { request: { method: "GET", url: "https://cf.ishin-global.aktsk.com/private.png" }, response: { status: 304, content: { mimeType: "application/octet-stream", text: "" } } }, 0), binary = sanitizeSpecialM0Entry("burst-mode-2026-08-10", { request: { method: "GET", url: "https://cf.ishin-global.aktsk.com/private.png" }, response: { status: 200, content: { mimeType: "image/png", encoding: "base64", text: "c3ludGhldGlj" } } }, 1); assert.equal(cached.response.representation, "cache_not_modified_304"); assert.equal(binary.response.representation, "binary_base64"); });
    it("is deterministic and validates exact capture identity", () => { const text = JSON.stringify({ log: { entries: [{ startedDateTime: "2026-08-10T12:00:00Z", request: { method: "GET", url: "https://ishin-global.aktsk.com/sd/packs" }, response: { status: 200, content: { mimeType: "application/json", text: "{\"sd_packs\":[]}" } } }] } }), item = (captureId: "burst-mode-2026-08-10" | "pettan-not-live-2026-08-10") => ({ captureId, fileName: `${captureId}.har`, sizeBytes: Buffer.byteLength(text), sha256: createHash("sha256").update(text).digest("hex"), entryCount: 1 }), locks = [item("burst-mode-2026-08-10"), item("pettan-not-live-2026-08-10")], lock = { schemaVersion: 1, contract: "dokkan-special-modes-offline-source-lock", contractVersion: "0.1.0", captureRoot: "special-modes-2026-08-10", captures: locks } as SpecialM0SourceLock, a = buildSpecialM0(locks.map(value => ({ text, lock: value })), lock), b = buildSpecialM0(locks.map(value => ({ text, lock: value })), lock); assert.deepEqual(a, b); assert.equal(a.entries.length, 2); });
});
