import { Buffer } from "buffer";
import { createHash } from "crypto";
import { SpecialM0Dataset } from "./special-m0-contract";
import { SpecialM1Announcement, SpecialM1Asset, SpecialM1Dataset, SpecialM1Operation, SpecialM1Validation, SpecialSourceSpan } from "./special-m1-contract";

function sha256(value: string | Buffer): string { return createHash("sha256").update(value).digest("hex"); }
function positive(value: unknown): number | null { return Number.isSafeInteger(value) && (value as number) > 0 ? value as number : null; }
function json(content: any): any | null { if (!content || typeof content.text !== "string" || content.encoding === "base64" || !String(content.mimeType ?? "").toLowerCase().startsWith("application/json")) return null; try { return JSON.parse(content.text); } catch { return null; } }
function span(entryIndex: number, jsonPointer: string): SpecialSourceSpan { return { captureId: "pettan-not-live-2026-08-10", entryIndex, jsonPointer }; }
function ids(values: unknown[]): number[] { return [...new Set(values.flatMap(value => { const parsed = positive(value); return parsed === null ? [] : [parsed]; }))].sort((a, b) => a - b); }
function safeAssetPath(value: unknown): string | null { if (typeof value !== "string") return null; let path = value; try { if (/^https?:\/\//i.test(value)) path = new URL(value).pathname; } catch { return null; } path = `/${path.replace(/^\/+/, "")}`.replace(/\/{2,}/g, "/"); return /^\/banners\/en\/news\/[A-Za-z0-9_.-]+\.(?:png|jpe?g)$/i.test(path) ? path : null; }
function topShape(content: any, stop: Set<string>): string[] { const value = json(content); if (!value || typeof value !== "object" || Array.isArray(value)) return []; return Object.keys(value).sort().map(key => { const child = value[key], type = child === null ? "null" : Array.isArray(child) ? "array" : typeof child; return `$.${stop.has(key) ? "[account-subtree]" : /^[A-Za-z_][A-Za-z0-9_-]{0,63}$/.test(key) ? key : "[dynamic-key]"}:${type}`; }); }

export function buildSpecialM1(harText: string, m0: SpecialM0Dataset, m0Text: string): SpecialM1Dataset { const entries = JSON.parse(harText)?.log?.entries; if (!Array.isArray(entries)) throw new Error("M1 invalid HAR"); const expected = m0.sources.find(value => value.captureId === "pettan-not-live-2026-08-10"); if (!expected || expected.sha256 !== sha256(harText) || expected.sizeBytes !== Buffer.byteLength(harText)) throw new Error("M1/M0 capture lineage mismatch"); const packIndexObservations: SpecialM1Dataset["packIndexObservations"] = [], operations: SpecialM1Operation[] = [], announcements: SpecialM1Announcement[] = [], assets: SpecialM1Asset[] = [];
    entries.forEach((entry: any, entryIndex: number) => { let url: URL; try { url = new URL(entry?.request?.url); } catch { return; } const method = String(entry?.request?.method ?? "").toUpperCase(), path = url.pathname.replace(/\/{2,}/g, "/"), status = Number.isSafeInteger(entry?.response?.status) ? entry.response.status : 0, body = json(entry?.response?.content);
        if (url.hostname.toLowerCase() === "ishin-global.aktsk.com" && method === "GET" && path === "/sd/packs" && body) { const packs = Array.isArray(body.sd_packs) ? body.sd_packs : []; packIndexObservations.push({ sourceSpan: span(entryIndex, "/sd_packs"), status, packCount: packs.length, packIds: ids(packs.map((value: any) => positive(value?.id) ?? positive(value?.sd_pack_id))), mapIds: ids(packs.map((value: any) => value?.sd_map_id)), authority: "capture_time_product_observation_not_universal_availability" }); }
        const op = method === "POST" && path === "/sd/packs/open" ? "/sd/packs/open" : method === "POST" && path === "/sd/tutorial/finish_opening" ? "/sd/tutorial/finish_opening" : method === "PUT" && path === "/sd/tutorial" ? "/sd/tutorial" : null; if (op) operations.push({ sourceSpan: span(entryIndex, "/"), method: method as "POST" | "PUT", normalizedPath: op, status, requestShape: topShape(entry?.request?.postData, new Set(["progress"])), responseShape: topShape(entry?.response?.content, new Set(["items", "missions", "user_items"])), accountValuesOmitted: true, replayCapability: false, authority: "observed_shape_only_no_effect_or_reward_authority" });
        if (url.hostname.toLowerCase() === "ishin-global.aktsk.com" && method === "GET" && /^\/announcements\/\d+$/.test(path) && body?.announcement) { const pathId = positive(Number(path.split("/").at(-1))), bodyId = positive(body.announcement.id); if (pathId !== null && bodyId === pathId) { const refs: SpecialM1Announcement["referencedAssetPaths"] = []; for (const [index, value] of (Array.isArray(body.announcement.bodies) ? body.announcement.bodies : []).entries()) { const assetPath = safeAssetPath(value?.image); if (assetPath) refs.push({ path: assetPath, sourceSpan: span(entryIndex, `/announcement/bodies/${index}/image`) }); } announcements.push({ announcementId: pathId, sourceSpan: span(entryIndex, "/announcement/id"), referencedAssetPaths: refs.sort((a, b) => a.path.localeCompare(b.path)), identityPolicy: "numeric_announcement_id_only_text_excluded" }); } }
        if (url.hostname.toLowerCase() === "cf.ishin-global.aktsk.com" && method === "GET" && status === 200) { const assetPath = safeAssetPath(path), content = entry?.response?.content; if (assetPath && content?.encoding === "base64" && typeof content.text === "string") { const bytes = Buffer.from(content.text, "base64"); assets.push({ path: assetPath, status, mimeType: String(content.mimeType ?? "unknown").split(";", 1)[0].toLowerCase(), sizeBytes: bytes.length, sha256: sha256(bytes), sourceSpan: span(entryIndex, "/response/content/text"), associationBoundary: "exact_path_observed_not_series_map_or_gameplay_identity" }); } }
    });
    const dataset: SpecialM1Dataset = { schemaVersion: 1, contract: "dokkan-special-modes-pettan-offline-observation", contractVersion: "0.2.0", generatedAt: m0.generatedAt, generatedAtPolicy: "inherits_m0_capture_timestamp", collectionMode: "offline_local_har_no_requests_no_replay", defaultEnabled: false, productionMutation: false, replayCapability: false, captureState: "pettan_not_live", valuePolicy: "global_structural_ids_and_shapes_only_account_values_excluded", m0ArtifactSha256: sha256(m0Text), m0ArtifactSizeBytes: Buffer.byteLength(m0Text), packIndexObservations: packIndexObservations.sort((a, b) => a.sourceSpan.entryIndex - b.sourceSpan.entryIndex), operations: operations.sort((a, b) => a.sourceSpan.entryIndex - b.sourceSpan.entryIndex), announcements: announcements.sort((a, b) => a.announcementId - b.announcementId), assets: assets.sort((a, b) => a.path.localeCompare(b.path)), topologyEvidence: { seriesIds: [], mapIds: [...new Set(packIndexObservations.flatMap(value => value.mapIds))].sort((a, b) => a - b), arenaIds: [], stageIds: [], status: "unknown", boundary: "no_active_pack_or_topology_payload_observed" }, battleEvidence: { observedRouteCount: 0, status: "unknown", boundary: "no_pettan_battle_route_observed_event_inactive_no_battle_inferred" }, availability: { emptyPackIndexObservationCount: packIndexObservations.filter(value => value.packCount === 0).length, inference: "unknown", boundary: "empty_capture_time_list_does_not_prove_universal_inactivity" } };
    const validation = validateSpecialM1(dataset, m0, m0Text); if (!validation.valid) throw new Error(`M1 validation failed: ${validation.failures.join(", ")}`); return dataset; }

export function validateSpecialM1(dataset: SpecialM1Dataset, m0?: SpecialM0Dataset, m0Text?: string): SpecialM1Validation { const failures: string[] = []; if (dataset.schemaVersion !== 1 || dataset.contract !== "dokkan-special-modes-pettan-offline-observation" || dataset.contractVersion !== "0.2.0" || dataset.generatedAtPolicy !== "inherits_m0_capture_timestamp" || dataset.collectionMode !== "offline_local_har_no_requests_no_replay" || dataset.defaultEnabled !== false || dataset.productionMutation !== false || dataset.replayCapability !== false || dataset.captureState !== "pettan_not_live" || dataset.valuePolicy !== "global_structural_ids_and_shapes_only_account_values_excluded" || dataset.battleEvidence.observedRouteCount !== 0 || dataset.battleEvidence.status !== "unknown") failures.push("dataset contract"); if (dataset.packIndexObservations.length === 0 || dataset.packIndexObservations.some(value => value.sourceSpan.captureId !== "pettan-not-live-2026-08-10" || value.authority !== "capture_time_product_observation_not_universal_availability")) failures.push("pack observations"); if (dataset.operations.some(value => value.accountValuesOmitted !== true || value.replayCapability !== false || !["POST", "PUT"].includes(value.method))) failures.push("operation boundary"); if (dataset.assets.some(value => !/^[a-f0-9]{64}$/.test(value.sha256) || value.sizeBytes <= 0 || value.associationBoundary !== "exact_path_observed_not_series_map_or_gameplay_identity") || dataset.announcements.some(value => value.identityPolicy !== "numeric_announcement_id_only_text_excluded")) failures.push("resource boundary"); if (m0 && m0Text && (dataset.generatedAt !== m0.generatedAt || dataset.m0ArtifactSha256 !== sha256(m0Text) || dataset.m0ArtifactSizeBytes !== Buffer.byteLength(m0Text))) failures.push("M0 lineage"); return { schemaVersion: 1, valid: failures.length === 0, packIndexObservationCount: dataset.packIndexObservations.length, observedPackCount: dataset.packIndexObservations.reduce((sum, value) => sum + value.packCount, 0), operationCount: dataset.operations.length, announcementCount: dataset.announcements.length, assetCount: dataset.assets.length, battleRouteCount: dataset.battleEvidence.observedRouteCount, failures: [...new Set(failures)] }; }
