import { createHash } from "crypto";
import { Buffer } from "buffer";
import { SpecialM0Dataset, SpecialM0Validation } from "./special-m0-contract";
import { SpecialM1Dataset, SpecialM1Validation } from "./special-m1-contract";
import { SpecialM2Dataset, SpecialM2Validation } from "./special-m2-contract";
import { SpecialM3Dataset, SpecialM3Validation } from "./special-m3-contract";
import { SpecialM4Dataset, SpecialM4Validation } from "./special-m4-contract";
import { SpecialM5Dataset, SpecialM5Validation } from "./special-m5-contract";
import { SpecialM6Artifact, SpecialM6CaptureFlow, SpecialM6Dataset, SpecialM6Decision, SpecialM6DecisionId, SpecialM6MemoryEvidence, SpecialM6Validation } from "./special-m6-contract";

const sha256 = (value: string | Buffer): string => createHash("sha256").update(value).digest("hex");
export function specialM6Decisions(): SpecialM6Decision[] { return [
    { id: "merge_disabled_infrastructure", status: "GO", reason: "additive offline contracts are default-off, fail closed and expose no request, replay, publisher or production path" },
    { id: "tracked_synthetic_fixtures", status: "GO", reason: "the minimal fixture is explicitly synthetic and carries no captured scalar, account, header, token or payload value" },
    { id: "pettan_active_catalog_or_battle", status: "NO_GO", reason: "the capture was not live, pack indexes were empty and no Pettan battle route was observed" },
    { id: "burst_gameplay_or_scoring", status: "NO_GO", reason: "briefing fields and quest identity do not prove modifier effects, scoring, battle rules or causality" },
    { id: "burst_opaque_start_configuration", status: "NO_GO", reason: "the common start body is an omitted opaque signature and reveals no safely projectable configuration" },
    { id: "replace_existing_sources_or_caches", status: "NO_GO", reason: "E/S/H and current caches are shadow references with explicit coverage gaps and non-equivalent representations" },
    { id: "android", status: "NO_GO", reason: "Android is out of scope and unchanged" },
    { id: "r2_or_publisher", status: "NO_GO", reason: "R2 and publisher work are out of scope and no dry-run or byte projection exists" },
    { id: "production_enablement", status: "NO_GO", reason: "production remains unchanged and all special-mode infrastructure is disabled by default" },
    { id: "request_replay_or_mutation_automation", status: "NO_GO", reason: "requests, replay and automated POST or PUT behavior are prohibited and unsupported" },
]; }
export function specialM6CaptureFlows(): SpecialM6CaptureFlow[] { return [
    { id: "pettan-active-pack-index-cold-warm", domain: "pettan", precondition: "server UI visibly reports an active Pettan window; passive recorder is local and no action endpoint is invoked", steps: [
        { order: 1, action: "start a cold passive recording before manually opening the read-only Pettan landing screen", retain: ["GET /sd/packs status", "numeric pack/map identities", "empty/null/presence states", "source span"], stopBoundary: "stop before pack opening, tutorial advance or any mutation control", expectedStatus: "partial" },
        { order: 2, action: "repeat the same read-only navigation with a warm cache", retain: ["200 versus 304 representation", "validator/cache metadata names without values", "source span"], stopBoundary: "do not force, forge or replay conditional requests", expectedStatus: "partial" },
    ], completionEvidence: "at least one non-empty 200 product index plus its natural 200/304 warm representation, both sanitized and source-pinned" },
    { id: "pettan-active-topology", domain: "pettan", precondition: "active window and user-driven read-only navigation only", steps: [
        { order: 1, action: "passively record every GET naturally triggered while browsing pack, series/map, arena and stage selection screens", retain: ["normalized GET route", "numeric sd_pack/sd_map/sd_arena/sd_stage IDs", "parent-child structural IDs", "source span"], stopBoundary: "stop at the first UI step that would start a battle, open a pack, finish a tutorial or mutate account state", expectedStatus: "unknown" },
        { order: 2, action: "join only the captured numeric IDs to E1/E2 after offline sanitization", retain: ["exact ID joins", "dangling IDs", "representation differences"], stopBoundary: "never use title, localized text, filename proximity or display order as identity", expectedStatus: "partial" },
    ], completionEvidence: "a complete captured numeric chain to an E2 sd map/arena/stage, or an explicit unknown report naming the absent link" },
    { id: "pettan-battle-observation", domain: "pettan", precondition: "a user independently elects to play during an active event in a separately authorized passive-capture session", steps: [
        { order: 1, action: "record route names and sanitized structural shapes without causing, scripting or replaying the play", retain: ["operation order", "numeric product IDs", "shape-only account boundaries", "source span"], stopBoundary: "no automation, no replay, no synthetic battle and no claim of effects from ordering", expectedStatus: "unknown" },
    ], completionEvidence: "observed passive route shapes remain unknown until an independent semantic authority exists" },
    { id: "burst-active-home-and-briefing", domain: "burst", precondition: "Burst is visibly active and the user performs normal read-only navigation", steps: [
        { order: 1, action: "passively capture the naturally issued GET /resources/home and retain only Burst structural IDs and window fields", retain: ["genkai root ID", "schedule ID", "area/map IDs", "start/end representation", "source span"], stopBoundary: "omit account subtrees and do not infer availability beyond the capture instant", expectedStatus: "partial" },
        { order: 2, action: "capture cold and warm GET /quests/:id/briefing for the same root in at least two naturally selected map/difficulty contexts", retain: ["numeric route quest ID", "query key names only", "genkai/gimmick/condition IDs", "200/304 representation", "source span"], stopBoundary: "omit deck, supporters, score, descriptions and all query/header values", expectedStatus: "partial" },
        { order: 3, action: "repeat steps 1-2 in a distinct schedule/window", retain: ["numeric schedule identity", "bounded timestamps", "typed representation changes"], stopBoundary: "do not promote temporal change or absence to conflict", expectedStatus: "partial" },
    ], completionEvidence: "two schedule-bounded ID-only observations with natural cold/warm representations and no gameplay inference" },
    { id: "burst-common-start-schema", domain: "burst", precondition: "separate future authorization for local client-side schema instrumentation during a user's legitimate manual play", steps: [
        { order: 1, action: "instrument only the pre-sign or post-verification schema boundary locally; do not retain values", retain: ["field names", "types", "presence/cardinality", "numeric product-ID domains", "source span"], stopBoundary: "never emit, store, reconstruct, send or replay a signed body; this campaign supplies no such instrumentation", expectedStatus: "unknown" },
    ], completionEvidence: "a separately reviewed schema-only artifact that proves configuration dimensions without any signature, account value or raw payload" },
    { id: "binary-and-cache-representations", domain: "representation", precondition: "assets are fetched naturally by a user-driven read-only screen", steps: [
        { order: 1, action: "passively capture a natural cold 200 and warm 304 for each referenced announcement asset", retain: ["normalized asset path class", "status", "MIME", "size/hash of sanitized local evidence", "source span"], stopBoundary: "do not retain binary bytes in Git and do not treat 200/304 as content conflict", expectedStatus: "partial" },
    ], completionEvidence: "paired representation records whose identity is structural and whose bytes remain local and unversioned" },
    { id: "future-zstandard-proof", domain: "zstandard", precondition: "a future special-mode capture contains an application/x-zstd response", steps: [
        { order: 1, action: "validate frame format and record the declared dictionary ID without decoding", retain: ["frame metadata", "compressed size/hash", "source span"], stopBoundary: "dictionary ID 315060143 alone is never identity proof", expectedStatus: "unknown" },
        { order: 2, action: "obtain dictionary bytes from an independently documented source and pin exact bytes, size, SHA-256 and declared ID", retain: ["dictionary provenance receipt", "size", "SHA-256", "ID"], stopBoundary: "no brute force, filename guess or candidate promotion", expectedStatus: "unknown" },
        { order: 3, action: "decode only through a reviewed bounded provider after every pin matches", retain: ["green decode receipt", "output size/hash", "schema-only sanitized projection"], stopBoundary: "fail closed on any mismatch or output limit", expectedStatus: "partial" },
    ], completionEvidence: "independent dictionary identity plus a bounded green decode receipt; otherwise compressed content remains unknown" },
]; }
function artifact(gate: SpecialM6Artifact["gate"], fileName: string, text: string): SpecialM6Artifact { return { gate, fileName, sizeBytes: Buffer.byteLength(text), sha256: sha256(text) }; }
export interface SpecialM6Inputs { m0: SpecialM0Dataset; m0Validation: SpecialM0Validation; m1: SpecialM1Dataset; m1Validation: SpecialM1Validation; m2: SpecialM2Dataset; m2Validation: SpecialM2Validation; m3: SpecialM3Dataset; m3Validation: SpecialM3Validation; m4: SpecialM4Dataset; m4Validation: SpecialM4Validation; m5: SpecialM5Dataset; m5Validation: SpecialM5Validation; artifactTexts: Array<{ gate: SpecialM6Artifact["gate"]; fileName: string; text: string }>; fixtureText: string; memory: SpecialM6MemoryEvidence }
export function buildSpecialM6(input: SpecialM6Inputs): SpecialM6Dataset { if (![input.m0Validation.valid, input.m1Validation.valid, input.m2Validation.valid, input.m3Validation.valid, input.m4Validation.valid, input.m5Validation.valid].every(Boolean)) throw new Error("M6 requires green M0-M5 validations"); const fixture = JSON.parse(input.fixtureText); if (fixture.schemaVersion !== 1 || fixture.synthetic !== true || fixture.valuePolicy !== "no_real_capture_values" || fixture.routes.some((value: any) => value.method !== "GET")) throw new Error("M6 fixture contract mismatch"); const dataset: SpecialM6Dataset = { schemaVersion: 1, contract: "dokkan-special-modes-capture-readiness", contractVersion: "0.7.0", generatedAt: input.m5.generatedAt, generatedAtPolicy: "inherits_m5_capture_timestamp", collectionMode: "offline_local_artifacts_no_requests_no_replay", defaultEnabled: false, productionMutation: false, coverage: { harEntries: input.m0Validation.entryCount, pettanObservedPacks: input.m1Validation.observedPackCount, pettanBattleRoutes: input.m1Validation.battleRouteCount, burstFacts: input.m2Validation.factCount, losslessFacts: input.m4Validation.factCount, sourceSpans: input.m4Validation.sourceSpanCount, parityFacts: input.m5Validation.factCount, parityByClassification: input.m5Validation.byClassification }, zstandard: { observedBodyCount: 0, dictionaryIdOfInterest: 315060143, dictionaryIdentityStatus: "not_proved_and_not_needed_for_current_inputs", decodeStatus: "not_attempted", proofBoundary: "exact_dictionary_bytes_size_sha256_id_and_independent_provenance_required_id_alone_never_proves_identity" }, artifacts: input.artifactTexts.map(value => artifact(value.gate, value.fileName, value.text)).sort((a, b) => a.gate.localeCompare(b.gate)), fixture: { fileName: "special-modes-synthetic-shapes.json", sizeBytes: Buffer.byteLength(input.fixtureText), sha256: sha256(input.fixtureText), synthetic: true }, memory: input.memory, decisions: specialM6Decisions(), gaps: [
        { id: "pettan-active-product-identity", status: "unknown", boundary: "both observed pack indexes are empty and the event was not live" },
        { id: "pettan-battle", status: "unknown", boundary: "zero battle routes were observed; no battle is invented" },
        { id: "pettan-database-topology", status: "partial", boundary: "48 maps, 231 arenas and 1169 stages exist database-first but no capture ID closes the join" },
        { id: "burst-modifier-semantics", status: "partial", boundary: "raw briefing fields are captured, but labels, units, precedence and runtime effects are unproved" },
        { id: "burst-start-configuration", status: "unknown", boundary: "request and response are opaque omitted signatures" },
        { id: "burst-candidate-roots", status: "unknown", boundary: "747 database candidate rows expose no genkai root foreign key" },
        { id: "current-cache-totality", status: "unknown", boundary: "cache absence and separate namespaces are representation or coverage evidence, never conflict" },
    ], captureFlows: specialM6CaptureFlows() }; const validation = validateSpecialM6(dataset); if (!validation.valid) throw new Error(`M6 validation failed: ${validation.failures.join(", ")}`); return dataset; }
export function validateSpecialM6(dataset: SpecialM6Dataset): SpecialM6Validation { const failures: string[] = [], expected = new Map(specialM6Decisions().map(value => [value.id, value.status])), ids = new Set<SpecialM6DecisionId>(); if (dataset.schemaVersion !== 1 || dataset.contract !== "dokkan-special-modes-capture-readiness" || dataset.contractVersion !== "0.7.0" || dataset.generatedAtPolicy !== "inherits_m5_capture_timestamp" || dataset.collectionMode !== "offline_local_artifacts_no_requests_no_replay" || dataset.defaultEnabled !== false || dataset.productionMutation !== false) failures.push("dataset contract"); for (const decision of dataset.decisions) { if (ids.has(decision.id) || expected.get(decision.id) !== decision.status) failures.push("decision policy"); ids.add(decision.id); } if (ids.size !== expected.size) failures.push("decision set"); if (dataset.zstandard.observedBodyCount !== 0 || dataset.zstandard.dictionaryIdOfInterest !== 315060143 || dataset.zstandard.decodeStatus !== "not_attempted" || !dataset.zstandard.proofBoundary.includes("id_alone_never_proves_identity")) failures.push("zstandard boundary"); const measuredMaximum = Math.max(...dataset.memory.measurements.map(value => value.peakWorkingSetBytes)); if (dataset.memory.schemaVersion !== 1 || dataset.memory.contract !== "dokkan-special-modes-memory-evidence" || dataset.memory.contractVersion !== "0.7.0" || dataset.memory.limitBytes !== 1073741824 || !dataset.memory.withinLimit || dataset.memory.maximumPeakWorkingSetBytes !== measuredMaximum || measuredMaximum >= dataset.memory.limitBytes) failures.push("memory evidence"); if (dataset.artifacts.length !== 6 || new Set(dataset.artifacts.map(value => value.gate)).size !== 6 || dataset.artifacts.some(value => value.sizeBytes <= 0 || !/^[a-f0-9]{64}$/.test(value.sha256)) || !dataset.fixture.synthetic || !/^[a-f0-9]{64}$/.test(dataset.fixture.sha256)) failures.push("artifact evidence"); if (dataset.coverage.pettanObservedPacks !== 0 || dataset.coverage.pettanBattleRoutes !== 0 || dataset.coverage.parityByClassification.confirmed_conflict !== 0 || !dataset.gaps.some(value => value.id === "pettan-battle" && value.status === "unknown")) failures.push("evidence boundaries"); if (dataset.captureFlows.length !== 7 || dataset.captureFlows.some(flow => flow.steps.length === 0 || flow.steps.some((step, index) => step.order !== index + 1 || !step.stopBoundary))) failures.push("capture checklist"); return { schemaVersion: 1, valid: failures.length === 0, decisionCount: dataset.decisions.length, goCount: dataset.decisions.filter(value => value.status === "GO").length, noGoCount: dataset.decisions.filter(value => value.status === "NO_GO").length, artifactCount: dataset.artifacts.length, captureFlowCount: dataset.captureFlows.length, maximumPeakWorkingSetBytes: dataset.memory.maximumPeakWorkingSetBytes, failures: [...new Set(failures)] }; }
