"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert = require("assert");
const wt0_audit_1 = require("./wt0-audit");
const wt1_catalog_1 = require("./wt1-catalog");
const routes = ["/resources/home", "/bonus_schedules", "/budokais/7/entry", "/budokais/7/ranks", "/budokais/7/rankings", "/budokais/7/rankings/borders", "/budokais/7/rankings/friends", "/budokais/7/box_rankings/71", "/quests/0/briefing"];
function source() { const entries = routes.map(path => ({ request: { method: "GET", url: `https://example.invalid${path}`, headers: [] }, response: { status: 200, headers: [], content: { text: "{}" } } })); entries.push({ request: { method: "POST", url: "https://example.invalid/budokais/7/tournaments", headers: [], postData: { text: "{\"sign\":\"synthetic-request\"}" } }, response: { status: 200, headers: [], content: { text: "{\"sign\":\"synthetic-response\"}" } } }); return JSON.stringify({ log: { entries } }); }
describe("world tournament WT1", () => {
    it("catalogs every required route deterministically", () => { const raw = source(), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, a = (0, wt1_catalog_1.buildWt1)(wt0, text), b = (0, wt1_catalog_1.buildWt1)(wt0, text); assert.deepEqual(a, b); assert.equal((0, wt1_catalog_1.validateWt1)(a).valid, true); assert.equal(a.requiredSurface.every(value => value.status === "observed"), true); });
    it("rejects input bytes that do not exactly bind WT0", () => { const raw = source(), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)); assert.throws(() => (0, wt1_catalog_1.buildWt1)(wt0, `${JSON.stringify(wt0, null, 2)} `), /exact WT0 input mismatch/); });
    it("rejects a missing route", () => { const raw = source(), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, dataset = (0, wt1_catalog_1.buildWt1)(wt0, text); dataset.requiredSurface[0].status = "unknown"; assert.equal((0, wt1_catalog_1.validateWt1)(dataset).valid, false); });
    it("preserves type to occurrence association", () => { const raw = JSON.parse(source()); raw.log.entries.push({ request: { method: "GET", url: "https://example.invalid/resources/home", headers: [] }, response: { status: 200, headers: [], content: { text: "{\"budokai\":{\"id\":7}}" } } }, { request: { method: "GET", url: "https://example.invalid/resources/home", headers: [] }, response: { status: 200, headers: [], content: { text: "{\"budokai\":{\"id\":\"synthetic\"}}" } } }); const text = JSON.stringify(raw), wt0 = (0, wt0_audit_1.buildWt0)(text, (0, wt0_audit_1.makeExternalSourceLock)(text)), wt0Text = `${JSON.stringify(wt0, null, 2)}\n`, catalog = (0, wt1_catalog_1.buildWt1)(wt0, wt0Text), node = catalog.routes.find(value => value.route === "/resources/home").responseSchema.find(value => value.path === "$.budokai.id"); assert.deepEqual(node.types, ["number", "string"]); assert.equal(node.typeOccurrences.length, 2); assert.notDeepEqual(node.typeOccurrences[0].observedEntryIndexes, node.typeOccurrences[1].observedEntryIndexes); });
    it("does not let GET satisfy the POST start contract", () => { const raw = source(), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)), start = wt0.entries.find(value => value.route.endsWith("/tournaments")); start.method = "GET"; start.traffic = "read_observed"; const text = `${JSON.stringify(wt0, null, 2)}\n`; assert.throws(() => (0, wt1_catalog_1.buildWt1)(wt0, text), /required observed surface/); });
    it("rejects a canonical but semantically forged WT0", () => { const raw = source(), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)); wt0.contract = "forged"; assert.throws(() => (0, wt1_catalog_1.buildWt1)(wt0, `${JSON.stringify(wt0, null, 2)}\n`), /exact WT0 input mismatch/); });
    it("rejects forged route and required-surface contracts", () => { const raw = source(), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, catalog = (0, wt1_catalog_1.buildWt1)(wt0, text); catalog.routes[0].route = "/budokais/private-literal"; catalog.requiredSurface.pop(); assert.equal((0, wt1_catalog_1.validateWt1)(catalog).valid, false); });
    it("rejects forged scope, schema type and GET traffic", () => { const raw = source(), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, catalog = (0, wt1_catalog_1.buildWt1)(wt0, text), get = catalog.routes.find(value => value.method === "GET" && value.responseSchema.length > 0); get.classification = "opaque"; get.traffic = "mutation_observed_not_replayable"; get.responseSchema[0].types = ["forged"]; assert.equal((0, wt1_catalog_1.validateWt1)(catalog).valid, false); });
});
//# sourceMappingURL=wt1-catalog.spec.js.map