"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert = require("assert");
const wt0_audit_1 = require("./wt0-audit");
const wt1_catalog_1 = require("./wt1-catalog");
const wt2_event_entry_1 = require("./wt2-event-entry");
function inputs() { const entries = [{ request: { method: "GET", url: "https://x.invalid/budokais/7/entry", headers: [] }, response: { status: 200, headers: [], content: { text: JSON.stringify({ id: 7, name: "Synthetic", description: "Synthetic", start_at: 1, end_at: 2, collecting_end_at: 3, result_end_at: 4, has_entry: false, participant: 0, point: 0, title_num: 0, continuous_title_num: 0, continuous_title_bonus: 0, rank: 0, is_box_ranking_rewards_acceptable: false, tournament: { deck_num: null }, budokai_maps: [{ id: 71, budokai_id: 7, name: "Synthetic", round: 1, act: 1, turn: 1, battle_turn: 1, hp_masu_interval_turn: 1, player_count: 1, winner_count: 1, is_qualify_round: true }], budokai_status: { budokai_mission_progress: { point: 0, rank: 0, title_num: 0, continuous_title_num: 0 }, motivation: { id: null, opened_ids: [1] }, next_budokai_mission_id: 7001, ranking: { current_ranking_range_top: null, next_ranking_range_bottom: 1 } } }) } } }, { request: { method: "GET", url: "https://x.invalid/budokais/7/ranks", headers: [] }, response: { status: 200, headers: [], content: { text: JSON.stringify({ ranks: [{ rank: 1, user_count: 2 }] }) } } }]; for (const path of ["/resources/home", "/bonus_schedules", "/budokais/7/rankings", "/budokais/7/rankings/borders", "/budokais/7/rankings/friends", "/budokais/7/box_rankings/71", "/quests/0/briefing"])
    entries.push({ request: { method: "GET", url: `https://x.invalid${path}`, headers: [] }, response: { status: 200, headers: [], content: { text: "{}" } } }); entries.push({ request: { method: "POST", url: "https://x.invalid/budokais/7/tournaments", headers: [], postData: { text: "{\"sign\":\"synthetic\"}" } }, response: { status: 200, headers: [], content: { text: "{\"sign\":\"synthetic\"}" } } }); const raw = JSON.stringify({ log: { entries } }), wt0 = (0, wt0_audit_1.buildWt0)(raw, (0, wt0_audit_1.makeExternalSourceLock)(raw)), a = `${JSON.stringify(wt0, null, 2)}\n`, wt1 = (0, wt1_catalog_1.buildWt1)(wt0, a), b = `${JSON.stringify(wt1, null, 2)}\n`; return { wt0, a, wt1, b }; }
describe("world tournament WT2", () => { it("separates global lifecycle and account state", () => { const i = inputs(), a = (0, wt2_event_entry_1.buildWt2)(i.wt0, i.a, i.wt1, i.b), b = (0, wt2_event_entry_1.buildWt2)(i.wt0, i.a, i.wt1, i.b); assert.deepEqual(a, b); assert.equal(a.budokai.globalStatus.status, "unknown"); assert.equal(a.entry.fields.every(value => value.classification === "account_scoped"), true); assert.equal(a.budokai.maps.parentRelation.status, "partial"); assert.equal((0, wt2_event_entry_1.validateWt2)(a).valid, true); }); it("rejects promotion of account status or an unproved map parent", () => { const i = inputs(), d = (0, wt2_event_entry_1.buildWt2)(i.wt0, i.a, i.wt1, i.b); d.budokai.globalStatus.status = "observed"; d.budokai.maps.parentRelation.budokaiId = 7; assert.equal((0, wt2_event_entry_1.validateWt2)(d).valid, false); }); it("rejects missing rank schema", () => { const i = inputs(); i.wt1.routes.find(value => value.route.endsWith("/ranks")).responseSchema = []; i.b = `${JSON.stringify(i.wt1, null, 2)}\n`; assert.throws(() => (0, wt2_event_entry_1.buildWt2)(i.wt0, i.a, i.wt1, i.b), /upstream lineage mismatch|validation failed/); }); it("rejects upstream lineage drift", () => { const i = inputs(); i.wt1.source.sizeBytes += 1; i.b = `${JSON.stringify(i.wt1, null, 2)}\n`; assert.throws(() => (0, wt2_event_entry_1.buildWt2)(i.wt0, i.a, i.wt1, i.b), /upstream lineage mismatch/); }); it("rejects forged output lineage version and size", () => { const i = inputs(), d = (0, wt2_event_entry_1.buildWt2)(i.wt0, i.a, i.wt1, i.b); d.lineage[0].contractVersion = "forged"; d.lineage[1].sizeBytes = Number.POSITIVE_INFINITY; assert.equal((0, wt2_event_entry_1.validateWt2)(d).valid, false); }); it("keeps rank definitions separate from grants", () => { const i = inputs(), d = (0, wt2_event_entry_1.buildWt2)(i.wt0, i.a, i.wt1, i.b); d.ranks.rewardBoundary = "grant"; assert.equal((0, wt2_event_entry_1.validateWt2)(d).valid, false); }); });
//# sourceMappingURL=wt2-event-entry.spec.js.map