"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = require("assert");
const server_s7_builder_1 = require("./server-s7-builder");
const payloads = { s0: "server-s0-catalog.json", s1: "server-s1-schedule-banners.json", s2: "server-s2-roots.json", s3: "server-s3-reward-joins.json", s4: "server-s4-asset-delivery.json", s5: "server-s5-registry.json", s6: "server-s6-shadow-parity.json" };
const gate = (name, dataset) => ({ gate: name, contractVersion: `0.${Number(name[1]) + 1}.0`, path: `data/database-server/${name}/${payloads[name]}`, sha256: name[1].repeat(64), sizeBytes: 10, generatedAt: `2026-08-0${Number(name[1]) + 1}T00:00:00.000Z`, dataset });
function inputs() {
    const endpoints = [{ sourceClass: "official_client", collectionGate: "discover_only" }], banners = [{ featuredCharacters: { entries: [{}, {}] } }];
    const sbr = { key: "super_battle_road", rootStatus: "supported", joins: [{ status: "supported", matchedCount: 177 }] }, clash = { key: "ultimate_clash", rootStatus: "partial", joins: [{ status: "unjoinable", unmatchedCount: 98 }] };
    return { s0: gate("s0", { collectionMode: "static_inventory_no_network_capture", endpoints }), s1: gate("s1", { schedules: [], authority: { officialDynamicAuthorityCount: 0 }, collection: { failures: [], receipts: [{}], fetchedBytes: 20 }, banners }), s2: gate("s2", { families: [sbr, clash] }), s3: gate("s3", { assessments: [{ classification: "partial_candidate" }] }), s4: gate("s4", { e6Projection: { remoteManifestJoinedReferenceCount: 0, uniqueReferenceCount: 4 }, networkSampleGate: { fullCatalogProjectedBytes: null }, baseApkInventory: { representativeSampleBytes: 3 } }), s5: gate("s5", { defaultEnabled: false, productionMutation: false, sidecars: Array.from({ length: 5 }, () => ({ defaultEnabled: false })) }), s6: gate("s6", { completeness: { proven: false, unknownOrUnjoinableCount: 2 }, totals: { confirmedConflict: 0, comparedCount: 3 }, subjects: [{ key: "reward_row_identity", counts: { unknown: 1, unjoinable: 1 } }] }) };
}
describe("server S7 readiness", () => {
    it("builds nine deterministic independent readiness decisions", () => { const first = (0, server_s7_builder_1.buildServerS7)(inputs()), second = (0, server_s7_builder_1.buildServerS7)(inputs()); (0, assert_1.deepEqual)(first, second); (0, assert_1.equal)((0, server_s7_builder_1.validateServerS7)(first).valid, true); (0, assert_1.equal)(first.decisions.length, 9); });
    it("allows only disabled infrastructure merge and bounded optional refresh", () => { const dataset = (0, server_s7_builder_1.buildServerS7)(inputs()), go = dataset.decisions.filter(value => value.decision === "GO").map(value => value.key); (0, assert_1.deepEqual)(go, ["merge_disabled_infrastructure", "optional_refresh"]); (0, assert_1.equal)(dataset.productionMutation, false); });
    it("keeps combined SBR/RMBattle resolution NO-GO despite SBR agreement", () => { const value = (0, server_s7_builder_1.buildServerS7)(inputs()).decisions.find(item => item.key === "resolve_sbr_rmbattle"); (0, assert_1.equal)(value.decision, "NO_GO"); (0, assert_1.equal)(value.blockers.length > 0, true); });
    it("rejects a readiness flip that preserves decision count", () => { const dataset = (0, server_s7_builder_1.buildServerS7)(inputs()); dataset.decisions.find(value => value.key === "r2_publication").decision = "GO"; const validation = (0, server_s7_builder_1.validateServerS7)(dataset); (0, assert_1.equal)(validation.valid, false); (0, assert_1.equal)(validation.exactDecisionSet, false); });
    it("requires blockers and exit criteria for every NO-GO", () => { const dataset = (0, server_s7_builder_1.buildServerS7)(inputs()); dataset.decisions.find(value => value.key === "asset_delivery").exitCriteria = []; const validation = (0, server_s7_builder_1.validateServerS7)(dataset); (0, assert_1.equal)(validation.noGoExitCriteriaComplete, false); (0, assert_1.equal)(validation.valid, false); });
    it("fails before readiness if any sidecar is activated", () => { const value = inputs(); value.s5.dataset.sidecars[0].defaultEnabled = true; (0, assert_1.throws)(() => (0, server_s7_builder_1.buildServerS7)(value), /S7 S5 activation boundary/); });
    it("fails before readiness if an official endpoint is promoted for collection", () => { const value = inputs(); value.s0.dataset.endpoints[0].collectionGate = "eligible_get_probe"; (0, assert_1.throws)(() => (0, server_s7_builder_1.buildServerS7)(value), /S7 S0 collection boundary/); });
    it("rejects substitution of a mandatory terminal prohibition", () => { const dataset = (0, server_s7_builder_1.buildServerS7)(inputs()); dataset.terminalBoundary.prohibitedWithoutNewEvidenceOrAuthority[4] = "harmless_placeholder"; const validation = (0, server_s7_builder_1.validateServerS7)(dataset); (0, assert_1.equal)(validation.stopBoundaryPreserved, false); (0, assert_1.equal)(validation.valid, false); });
});
//# sourceMappingURL=server-s7-builder.spec.js.map