/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 45191ed7942f8e44af69e00d0fd1e9e0)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
