import { createHash } from "crypto";
import { Buffer } from "buffer";
import { FrontierF3Dataset } from "./frontier-f3-contract";
import { FrontierF4Dataset } from "./frontier-f4-contract";
import { FrontierF5Classification, FrontierF5Dataset, FrontierF5Fact, FrontierF5Inputs, FrontierF5Lineage, FrontierF5Validation } from "./frontier-f5-contract";

const classifications: FrontierF5Classification[] = ["agreement", "representation_gain", "temporal_account_observation", "representation_mismatch", "confirmed_conflict", "coverage_gap", "unknown", "unjoinable"];
function sha256(value: string | Buffer): string { return createHash("sha256").update(value).digest("hex"); }
export function classifyStructuralPresence(captured: boolean, database: boolean, comparable = true): FrontierF5Classification { if (captured && database) return comparable ? "agreement" : "representation_mismatch"; if (captured) return "representation_gain"; if (database) return "coverage_gap"; return "unknown"; }
function entries(value: { provenance: Array<{ entryIndex: number }> }): number[] { return [...new Set(value.provenance.map(item => item.entryIndex))].sort((a, b) => a - b); }

export function buildFrontierF5(f3: FrontierF3Dataset, f3Text: string, f4: FrontierF4Dataset, f4Text: string, inputs: FrontierF5Inputs, lineage: FrontierF5Lineage[]): FrontierF5Dataset { if (inputs.series.length !== 2 || inputs.episodes.length !== 3 || inputs.pages.length !== 13 || inputs.battles.length !== 52) throw new Error("F5 pinned Origin universe mismatch"); const facts: FrontierF5Fact[] = [], add = (domain: FrontierF5Fact["domain"], subjectId: string, classification: FrontierF5Classification, captureEntryIndexes: number[], reason: string) => facts.push({ key: `${domain}:${subjectId}`, domain, subjectId, classification, captureEntryIndexes: [...new Set(captureEntryIndexes)].sort((a, b) => a - b), reason });
    const capturedSeries = new Map(f3.series.map(value => [value.id, value])), dbSeries = new Map(inputs.series.map(value => [value.id, value])); for (const id of [...new Set([...capturedSeries.keys(), ...dbSeries.keys()])].sort((a, b) => a - b)) { const capture = capturedSeries.get(id), database = dbSeries.get(id); add("series", String(id), classifyStructuralPresence(!!capture, !!database), capture ? entries(capture) : [], capture && database ? "numeric series ID joins E1" : capture ? "capture-only series ID" : "E1 series absent from capture"); }
    const capturedEpisodes = new Map(f3.episodes.map(value => [value.id, value])), dbEpisodes = new Map(inputs.episodes.map(value => [value.id, value])); for (const id of [...new Set([...capturedEpisodes.keys(), ...dbEpisodes.keys()])].sort((a, b) => a - b)) { const capture = capturedEpisodes.get(id), database = dbEpisodes.get(id); const classification = capture && database ? capture.seriesId === database.seriesId ? "agreement" : "confirmed_conflict" : classifyStructuralPresence(!!capture, !!database); add("episode", String(id), classification, capture ? entries(capture) : [], capture && database ? capture.seriesId === database.seriesId ? "episode and series IDs join E1" : "same episode ID has incompatible series relation" : capture ? "capture-only episode ID" : "E1 episode absent from capture index"); }
    const capturedPages = new Map(f3.pages.map(value => [value.id, value])), dbPages = new Map(inputs.pages.map(value => [value.id, value])); for (const id of [...new Set([...capturedPages.keys(), ...dbPages.keys()])].sort((a, b) => a - b)) { const capture = capturedPages.get(id), database = dbPages.get(id); const compatible = !!capture && !!database && capture.episodeId === database.episodeId && (database.order === null || capture.observedOrdinal + 1 === database.order), classification = capture && database ? compatible ? "agreement" : "confirmed_conflict" : classifyStructuralPresence(!!capture, !!database); add("page", String(id), classification, capture ? entries(capture) : [], capture && database ? compatible ? "page, episode and one-based order join E1" : "same page ID has incompatible episode or order" : capture ? "capture-only page ID" : "E1 page belongs to episode not detailed in capture"); }
    const capturedBattles = new Map(f3.battles.map(value => [value.id, value])), dbBattles = new Map(inputs.battles.map(value => [value.id, value])); for (const id of [...new Set([...capturedBattles.keys(), ...dbBattles.keys()])].sort((a, b) => a - b)) { const capture = capturedBattles.get(id), database = dbBattles.get(id), compatible = !!capture && !!database && capture.nodeId === database.spotId, classification = capture && database ? compatible ? "agreement" : "confirmed_conflict" : classifyStructuralPresence(!!capture, !!database); add("battle", String(id), classification, capture ? entries(capture) : [], capture && database ? compatible ? "capture closes E2 origin_spot_id to battle ID relation" : "same battle ID has incompatible spot relation" : capture ? "capture-only battle ID" : "E2 battle belongs to episode not detailed in capture"); }
    const encounters = new Map(inputs.encounters.map(value => [value.battleId, value])); for (const battle of f3.battles) { const encounter = encounters.get(battle.id); if (battle.enemyCardId === null) add("enemy", String(battle.id), "unknown", entries(battle), "capture supplies no display enemy reference"); else if (!encounter) add("enemy", String(battle.id), "coverage_gap", entries(battle), "E3 encounter missing for captured battle"); else add("enemy", String(battle.id), encounter.enemyCardIds.includes(battle.enemyCardId) ? "agreement" : "representation_mismatch", entries(battle), encounter.enemyCardIds.includes(battle.enemyCardId) ? "display enemy card ID occurs in E3 encounter" : "display enemy and encounter enemy arrays are different representations"); }
    for (const node of f3.nodes) add("node_topology", String(node.id), "representation_gain", entries(node), "capture adds page membership, predecessor, position and spot type missing from E2 spot-root topology");
    const missionIds = new Set(inputs.originMissions.map(value => value.id)); for (const battle of f3.battles) for (const missionId of battle.unlockMissionIds) add("mission", `${battle.id}:${missionId}`, missionIds.has(missionId) ? "agreement" : "representation_gain", entries(battle), missionIds.has(missionId) ? "unlock mission numeric ID joins E5 Origin mission slice" : "capture adds an unlock mission reference absent from the pinned E5 linked slice; contents and rewards remain unproved");
    const heatSets = new Set(inputs.heatUpSets.map(value => value.id)); f3.briefings.forEach(value => { const proof = [value.provenance.entryIndex]; if (value.heatUpGimmickSetId !== null) add("briefing", `heat-up:${value.provenance.entryIndex}:${value.heatUpGimmickSetId}`, heatSets.has(value.heatUpGimmickSetId) ? "agreement" : "unknown", proof, heatSets.has(value.heatUpGimmickSetId) ? "heat-up set ID joins E4 but briefing-to-stage association remains unproved" : "heat-up set ID absent from E4"); if (value.groupChangeSymbolId !== null) add("briefing", `group-change:${value.provenance.entryIndex}:${value.groupChangeSymbolId}`, "unknown", proof, "no E0-E9 semantic target for group-change symbol"); for (const limitation of value.limitations) add("briefing", `limitation:${value.provenance.entryIndex}:${limitation.owner}:${limitation.id}`, "representation_gain", proof, "capture adds structural team limitation definition; runtime meaning remains raw"); });
    for (const value of f3.availability) add("availability", `${value.owner}:${value.ownerId ?? "index"}:${value.provenance.entryIndex}`, "temporal_account_observation", [value.provenance.entryIndex], "capture-time next_open_at is not universal current availability"); for (const value of f3.accountObservations) add("account_state", `${value.owner}:${value.field}`, "temporal_account_observation", [], "account-scoped field presence recorded; scalar values omitted");
    const dbAssetPaths = new Set(inputs.originAssetPaths.map(value => `/${value.replace(/^\/+/, "")}`)); for (const value of [...new Map(f3.assets.map(asset => [asset.sanitizedPath, asset])).values()]) add("asset", value.sanitizedPath, dbAssetPaths.has(value.sanitizedPath) ? "agreement" : "unjoinable", [value.provenance.entryIndex], dbAssetPaths.has(value.sanitizedPath) ? "exact sanitized path joins E6" : "captured news CDN path has no exact E6 path reference; prefix or filename inference forbidden"); add("asset", "e6-origin-reference-surface", "coverage_gap", [], `${inputs.originAssetPaths.length} path and ${inputs.originNumericAssetCount} numeric E6 Origin references lack a captured JSON-to-delivery join`);
    add("reward", "finish-response", "coverage_gap", [f4.postFinishObservation.finishEntryIndex], "finish response remains compressed_unknown so no reward schema or value is projected"); for (const name of [...new Set(f4.operations.map(value => value.operation))].sort()) add("protocol", name, "unknown", f4.operations.filter(value => value.operation === name).map(value => value.entryIndex), "request order and shape observed; response state, causality, RNG and replayability unknown");
    facts.sort((a, b) => a.key.localeCompare(b.key)); const summary = Object.fromEntries(classifications.map(value => [value, facts.filter(fact => fact.classification === value).length])) as Record<FrontierF5Classification, number>, dataset: FrontierF5Dataset = { schemaVersion: 1, contract: "dokkan-frontier-e0-e9-shadow-parity", contractVersion: "0.6.0", generatedAt: f4.generatedAt, generatedAtPolicy: "inherits_f4_capture_timestamp", collectionMode: "offline_local_artifacts_no_requests_no_replay", productionMutation: false, defaultEnabled: false, identityPolicy: "numeric_structural_ids_only_no_text_joins", aggregatePolicy: "fact_rows_are_exclusive_but_domains_are_non_equivalent_units", f3ArtifactSha256: sha256(f3Text), f3ArtifactSizeBytes: Buffer.byteLength(f3Text), f4ArtifactSha256: sha256(f4Text), f4ArtifactSizeBytes: Buffer.byteLength(f4Text), sourceLineage: lineage, universe: { series: inputs.series.length, episodes: inputs.episodes.length, pages: inputs.pages.length, battles: inputs.battles.length, originMissions: inputs.originMissions.length, originAssetPaths: inputs.originAssetPaths.length, originNumericAssets: inputs.originNumericAssetCount }, facts, summary }; const validation = validateFrontierF5(dataset, f3, f3Text, f4, f4Text); if (!validation.valid) throw new Error(`F5 validation failed: ${validation.failures.join(", ")}`); return dataset; }
export function validateFrontierF5(dataset: FrontierF5Dataset, f3?: FrontierF3Dataset, f3Text?: string, f4?: FrontierF4Dataset, f4Text?: string): FrontierF5Validation { const failures: string[] = []; if (dataset.schemaVersion !== 1 || dataset.contract !== "dokkan-frontier-e0-e9-shadow-parity" || dataset.contractVersion !== "0.6.0" || dataset.generatedAtPolicy !== "inherits_f4_capture_timestamp" || dataset.collectionMode !== "offline_local_artifacts_no_requests_no_replay" || dataset.productionMutation !== false || dataset.defaultEnabled !== false || dataset.identityPolicy !== "numeric_structural_ids_only_no_text_joins" || dataset.aggregatePolicy !== "fact_rows_are_exclusive_but_domains_are_non_equivalent_units" || dataset.universe.series !== 2 || dataset.universe.episodes !== 3 || dataset.universe.pages !== 13 || dataset.universe.battles !== 52) failures.push("dataset contract"); if (new Set(dataset.facts.map(value => value.key)).size !== dataset.facts.length || dataset.facts.some(value => !classifications.includes(value.classification) || !/^[A-Za-z0-9_./:-]+$/.test(value.subjectId))) failures.push("fact contract"); const byClassification = Object.fromEntries(classifications.map(value => [value, dataset.facts.filter(fact => fact.classification === value).length])) as Record<FrontierF5Classification, number>; if (JSON.stringify(dataset.summary) !== JSON.stringify(byClassification)) failures.push("summary"); if (dataset.sourceLineage.length !== 8 || new Set(dataset.sourceLineage.map(value => value.key)).size !== 8) failures.push("source lineage"); if (f3 && f3Text && f4 && f4Text && (dataset.generatedAt !== f4.generatedAt || dataset.f3ArtifactSha256 !== sha256(f3Text) || dataset.f3ArtifactSizeBytes !== Buffer.byteLength(f3Text) || dataset.f4ArtifactSha256 !== sha256(f4Text) || dataset.f4ArtifactSizeBytes !== Buffer.byteLength(f4Text))) failures.push("capture lineage"); return { schemaVersion: 1, valid: failures.length === 0, factCount: dataset.facts.length, byClassification, sourceCount: dataset.sourceLineage.length, confirmedConflictCount: byClassification.confirmed_conflict, failures: [...new Set(failures)] }; }
