export interface FrontierProvenance { entryIndex: number; capturedAt: string }
export interface FrontierF3Series { id: number; episodeIds: number[]; provenance: FrontierProvenance[] }
export interface FrontierF3Episode { id: number; seriesId: number; detailObserved: boolean; provenance: FrontierProvenance[] }
export interface FrontierF3Page { id: number; episodeId: number; observedOrdinal: number; provenance: FrontierProvenance[] }
export interface FrontierF3Node { id: number; pageId: number; observedOrdinal: number; numberRaw: number | null; previousNodeId: number | null; spotTypeRaw: string; position: { x: number; y: number }; enemyCardId: number | null; originBattleId: number | null; provenance: FrontierProvenance[] }
export interface FrontierF3Battle { id: number; nodeId: number; enemyCardId: number | null; unlockMissionIds: number[]; provenance: FrontierProvenance[] }
export interface FrontierF3Limitation { id: number; owner: "episode" | "battle"; episodeId: number | null; rawType: string; allowedCategoryIds: number[]; forbiddenCardIds: number[]; requiredCardIds: number[]; requiredCount: number | null }
export interface FrontierF3Briefing { provenance: FrontierProvenance; groupChangeSymbolId: number | null; heatUpGimmickSetId: number | null; limitations: FrontierF3Limitation[]; associationBoundary: "no_stage_id_in_request_temporal_adjacency_not_a_join"; accountSubtreesOmitted: ["last_deck_cards", "special_guests"] }
export interface FrontierF3Availability { owner: "series_index" | "episode"; ownerId: number | null; nextOpenAtRaw: number | null; provenance: FrontierProvenance; authority: "capture_time_global_field_not_universal_current_availability" }
export interface FrontierF3AccountObservation { owner: "series" | "episode" | "battle" | "briefing"; field: string; observationCount: number; provenance: FrontierProvenance[]; valuesOmitted: true; authority: "account_scoped_observation_only" }
export interface FrontierF3AssetObservation { sanitizedPath: string; status: number; provenance: FrontierProvenance; relationToCatalog: "unproved_temporal_delivery_observation" }
export interface FrontierF3Dataset { schemaVersion: 1; contract: "dokkan-frontier-offline-catalog"; contractVersion: "0.4.0"; generatedAt: string; generatedAtPolicy: "inherits_f2_capture_timestamp"; collectionMode: "offline_local_har_no_requests_no_replay"; productionMutation: false; defaultEnabled: false; authority: "capture_bound_product_facts_and_separate_account_shape_observations"; identityPolicy: "numeric_structural_ids_only_names_and_titles_excluded"; f2ArtifactSha256: string; f2ArtifactSizeBytes: number; series: FrontierF3Series[]; episodes: FrontierF3Episode[]; pages: FrontierF3Page[]; nodes: FrontierF3Node[]; battles: FrontierF3Battle[]; briefings: FrontierF3Briefing[]; availability: FrontierF3Availability[]; accountObservations: FrontierF3AccountObservation[]; assets: FrontierF3AssetObservation[]; rewardCoverage: { status: "coverage_gap"; reason: "finish_response_compressed_unknown_no_reward_projection" } }
export interface FrontierF3Validation { schemaVersion: 1; valid: boolean; seriesCount: number; episodeCount: number; detailedEpisodeCount: number; pageCount: number; nodeCount: number; battleCount: number; missionReferenceCount: number; briefingCount: number; assetObservationCount: number; danglingRelationCount: number; failures: string[] }
