import { spawnSync } from "child_process";
import { createHash } from "crypto";
import { lstatSync, readFileSync, realpathSync, statSync } from "fs";
import { dirname, relative, resolve } from "path";
import { Buffer } from "buffer";
import { FrontierDictionaryArtifactScan, FrontierDictionaryCandidate, FrontierDictionarySearchLock, FrontierF1BodyEvidence, FrontierF1Dataset, FrontierF1Validation } from "./frontier-f1-contract";
import { FrontierF0Dataset } from "./frontier-f0-contract";
import { parseZstdFrameHeader } from "./frontier-zstd";

function sha256(value: string | Buffer): string { return createHash("sha256").update(value).digest("hex"); }
function normalizedRoute(pathname: string): string { const parts = pathname.replace(/\/{2,}/g, "/").split("/").filter(Boolean).map(value => /^\d+$/.test(value) ? ":id" : value.toLowerCase()); return `/${parts.join("/")}`; }
function safeArtifactPath(root: string, path: string): string { if (!/^[A-Za-z0-9_.\/-]+$/.test(path) || path.includes("..") || path.startsWith("/") || /^[A-Za-z]:/.test(path)) throw new Error("F1 artifact path is unsafe"); const rootReal = realpathSync(root), candidate = resolve(rootReal, path), inside = relative(rootReal, candidate); if (!inside || inside.startsWith("..") || resolve(rootReal, inside) !== candidate) throw new Error("F1 artifact escaped root"); let cursor = rootReal; for (const part of inside.split(/[\\/]/)) { cursor = resolve(cursor, part); const metadata = lstatSync(cursor); if (metadata.isSymbolicLink()) throw new Error("F1 artifact path contains a link"); } if (!statSync(candidate).isFile()) throw new Error("F1 artifact is not a file"); return candidate; }

export function scanFrontierDictionaryArtifacts(lock: FrontierDictionarySearchLock, roots: Record<string, string>): { scans: FrontierDictionaryArtifactScan[]; candidates: FrontierDictionaryCandidate[] } {
    if (lock.schemaVersion !== 1 || lock.contract !== "dokkan-frontier-zstd-dictionary-search-lock" || lock.contractVersion !== "0.2.0" || !Array.isArray(lock.artifacts) || lock.artifacts.length === 0) throw new Error("F1 artifact lock mismatch");
    const artifacts = lock.artifacts.map(item => { const root = roots[item.root]; if (!root || !/^[a-z][a-z0-9_-]{0,47}$/.test(item.role) || !Number.isSafeInteger(item.sizeBytes) || item.sizeBytes <= 0 || !/^[a-f0-9]{64}$/.test(item.sha256)) throw new Error("F1 invalid artifact lock entry"); const path = safeArtifactPath(root, item.relativePath), bytes = readFileSync(path); if (bytes.length !== item.sizeBytes || sha256(bytes) !== item.sha256) throw new Error(`F1 artifact identity mismatch ${item.role}`); return { role: item.role, path, scanArchiveEntries: item.scanArchiveEntries }; });
    const bridge = resolve(__dirname, "frontier-dictionary-readonly-bridge.py"), sourceBridge = resolve(__dirname, "..", "..", "database-frontier-captures", "frontier-dictionary-readonly-bridge.py"), result = spawnSync(process.platform === "win32" ? "python" : "python3", [require("fs").existsSync(bridge) ? bridge : sourceBridge], { input: JSON.stringify({ artifacts }), encoding: "utf8", maxBuffer: 16 * 1024 * 1024, windowsHide: true }); if (result.status !== 0) throw new Error(`F1 dictionary scan bridge failed: ${result.stderr}`);
    const parsed = JSON.parse(result.stdout) as { scans: FrontierDictionaryArtifactScan[]; candidates: FrontierDictionaryCandidate[] }; if (!Array.isArray(parsed.scans) || !Array.isArray(parsed.candidates) || parsed.scans.length !== lock.artifacts.length) throw new Error("F1 dictionary bridge schema mismatch"); const roles = new Set(lock.artifacts.map(value => value.role)); for (const item of lock.artifacts) { const matches = parsed.scans.filter(value => value.artifactRole === item.role), scan = matches[0]; if (matches.length !== 1 || !scan || scan.sizeBytes !== item.sizeBytes || scan.sha256 !== item.sha256 || ![scan.archiveEntryCount, scan.archiveExpandedBytes, scan.dictionaryHeaderCount].every(value => Number.isSafeInteger(value) && value >= 0)) throw new Error(`F1 artifact changed during scan ${item.role}`); } for (const candidate of parsed.candidates) { const safeArchiveEntry = candidate.archiveEntry === null || typeof candidate.archiveEntry === "string" && candidate.archiveEntry.length <= 512 && !candidate.archiveEntry.includes("\0") && !candidate.archiveEntry.split(/[\\/]/).includes(".."), identityShapeInvalid = candidate.identityStatus === "embedded_header_length_unknown" ? candidate.sizeBytes !== null || candidate.sha256 !== null : !Number.isSafeInteger(candidate.sizeBytes) || candidate.sizeBytes! <= 0 || !/^[a-f0-9]{64}$/.test(candidate.sha256 ?? ""); if (!roles.has(candidate.artifactRole) || !["file", "archive_entry"].includes(candidate.source) || !safeArchiveEntry || !Number.isSafeInteger(candidate.offset) || candidate.offset < 0 || !Number.isSafeInteger(candidate.dictionaryId) || candidate.dictionaryId < 0 || !["whole_file_dictionary", "whole_archive_entry_dictionary", "embedded_header_length_unknown"].includes(candidate.identityStatus) || identityShapeInvalid) throw new Error("F1 dictionary bridge candidate schema mismatch"); }
    return { scans: [...parsed.scans].sort((a, b) => a.artifactRole.localeCompare(b.artifactRole)), candidates: [...parsed.candidates].sort((a, b) => `${a.artifactRole}:${a.source}:${a.archiveEntry}:${a.offset}`.localeCompare(`${b.artifactRole}:${b.source}:${b.archiveEntry}:${b.offset}`)) };
}

export function selectFrontierDictionaryProofFromDiscovery(_candidates: FrontierDictionaryCandidate[], _observedDictionaryId: number): null { return null; }

export function buildFrontierF1(harText: string, f0: FrontierF0Dataset, f0Text: string, search: { scans: FrontierDictionaryArtifactScan[]; candidates: FrontierDictionaryCandidate[] }): FrontierF1Dataset {
    if (sha256(Buffer.from(harText)) !== f0.source.sha256 || Buffer.byteLength(harText) !== f0.source.sizeBytes) throw new Error("F1/F0 HAR lineage mismatch"); const entries = JSON.parse(harText)?.log?.entries; if (!Array.isArray(entries) || entries.length !== f0.entries.length) throw new Error("F1 invalid HAR lineage");
    const bodies: FrontierF1BodyEvidence[] = []; entries.forEach((entry: any, entryIndex: number) => { const content = entry?.response?.content, media = typeof content?.mimeType === "string" ? content.mimeType.split(";", 1)[0].trim().toLowerCase() : ""; if (media !== "application/x-zstd") return; if (content.encoding !== "base64" || typeof content.text !== "string") throw new Error("F1 Zstd body is not base64"); const compressed = Buffer.from(content.text, "base64"), frame = parseZstdFrameHeader(compressed), capturedAt = f0.entries[entryIndex]?.capturedAt; if (!capturedAt) throw new Error("F1 body lacks F0 provenance"); let path: string; try { path = normalizedRoute(new URL(entry.request.url).pathname); } catch { throw new Error("F1 body has invalid route"); } bodies.push({ entryIndex, capturedAt, method: f0.entries[entryIndex].method, normalizedPath: path, status: f0.entries[entryIndex].status, mimeType: "application/x-zstd", contentEncoding: "base64", compressedSizeBytes: compressed.length, compressedSha256: sha256(compressed), frame }); });
    if (bodies.length === 0) throw new Error("F1 found no Zstd bodies"); const dictionaryIds = [...new Set(bodies.map(value => value.frame.dictionaryId))]; if (dictionaryIds.length !== 1 || dictionaryIds[0] === 0) throw new Error("F1 requires one non-zero observed dictionary ID"); const observedDictionaryId = dictionaryIds[0], proof = selectFrontierDictionaryProofFromDiscovery(search.candidates, observedDictionaryId);
    const dataset: FrontierF1Dataset = { schemaVersion: 1, contract: "dokkan-frontier-zstd-frame-and-dictionary-audit", contractVersion: "0.2.0", generatedAt: f0.generatedAt, generatedAtPolicy: "inherits_f0_capture_timestamp", collectionMode: "offline_local_har_no_requests_no_replay", productionMutation: false, defaultEnabled: false, f0ArtifactSha256: sha256(f0Text), f0ArtifactSizeBytes: Buffer.byteLength(f0Text), frameFormat: "zstandard_rfc8878", bodies, dictionary: { observedDictionaryId, identityStatus: "unknown", proof, candidateProofPolicy: "discovery_candidates_never_grant_identity_explicit_pinned_dictionary_required", candidates: search.candidates, search: search.scans, unknownReason: "no_explicitly_pinned_zstd_dictionary_artifact_with_verified_id_size_and_sha256" } };
    const validation = validateFrontierF1(dataset, f0, f0Text); if (!validation.valid) throw new Error(`F1 validation failed: ${validation.failures.join(", ")}`); return dataset;
}

export function validateFrontierF1(dataset: FrontierF1Dataset, f0?: FrontierF0Dataset, f0Text?: string): FrontierF1Validation { const failures: string[] = []; if (dataset.schemaVersion !== 1 || dataset.contract !== "dokkan-frontier-zstd-frame-and-dictionary-audit" || dataset.contractVersion !== "0.2.0" || dataset.generatedAtPolicy !== "inherits_f0_capture_timestamp" || dataset.collectionMode !== "offline_local_har_no_requests_no_replay" || dataset.productionMutation !== false || dataset.defaultEnabled !== false || dataset.frameFormat !== "zstandard_rfc8878" || !/^[a-f0-9]{64}$/.test(dataset.f0ArtifactSha256) || !Number.isSafeInteger(dataset.f0ArtifactSizeBytes) || dataset.f0ArtifactSizeBytes <= 0) failures.push("dataset contract"); const ids = [...new Set(dataset.bodies.map(value => value.frame.dictionaryId))]; if (ids.length !== 1 || ids[0] !== dataset.dictionary.observedDictionaryId || dataset.bodies.some(value => value.frame.dictionaryIdFieldBytes !== 4 || value.frame.magic !== "28b52ffd" || !/^[a-f0-9]{64}$/.test(value.compressedSha256) || value.compressedSizeBytes <= 0)) failures.push("frame evidence"); if (dataset.dictionary.identityStatus !== "unknown" || dataset.dictionary.proof !== null || dataset.dictionary.candidateProofPolicy !== "discovery_candidates_never_grant_identity_explicit_pinned_dictionary_required" || typeof dataset.dictionary.unknownReason !== "string" || dataset.dictionary.unknownReason.length === 0) failures.push("dictionary proof"); if (f0 && f0Text && (dataset.generatedAt !== f0.generatedAt || dataset.f0ArtifactSha256 !== sha256(f0Text) || dataset.f0ArtifactSizeBytes !== Buffer.byteLength(f0Text) || dataset.bodies.some(value => f0.entries[value.entryIndex]?.responseMimeType !== "application/x-zstd"))) failures.push("F0 lineage"); return { schemaVersion: 1, valid: failures.length === 0, bodyCount: dataset.bodies.length, dictionaryId: ids.length === 1 ? ids[0] : null, dictionaryIdentityStatus: dataset.dictionary.identityStatus, candidateCount: dataset.dictionary.candidates.length, failures: [...new Set(failures)] }; }
