import { strict as assert } from "assert";
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, symlinkSync } from "fs";
import { tmpdir } from "os";
import { join, resolve } from "path";
import { Dd0Dataset, Dd0SourceLock, DdProvenance } from "./data-download-contract";
import { DD_CAPTURE_ROOT_ENV, resolveDdCaptureRoot } from "./data-download-context";
import { buildDd0, collectDdExternalSensitiveValues, collectDdSensitiveValues, LoadedDdCapture, LoadedDdExternalSource, loadDdCaptures, loadDdExternalSources, parseDdHar, scanVersionableTargets, sha256, validateDd0SourceLock, validateVersionableTarget } from "./data-download-core";
import { buildDd1 } from "./data-download-dd1";
import { buildDd2, ExternalDescriptor, parseClientAssetsBody, parseDatabaseBody, requireManifestExternalSource, sanitizeDdFilePath, sanitizeDdUrlPathname, summarizePathFamilies, validateDd2, validateUniqueExternalDescriptors, verifyExactExternalSuperset, verifyExternalOndemandPair } from "./data-download-dd2";

const lock = JSON.parse(readFileSync(resolve(process.cwd(), "database-data-download-captures/data-download-source-lock.json"), "utf8")) as Dd0SourceLock;
function source(captureIndex = 0, entries: any[] = []): LoadedDdCapture { return { lock: { ...lock.captures[captureIndex], entryCount: entries.length }, text: JSON.stringify({ log: { entries } }), har: { log: { entries } }, sourceIdentityFingerprint: "synthetic" }; }
const defaultEntryUrl = ["https://ishin-global.aktsk.com/client_assets?device_asset_size_", "bytes=123"].join("");
function entry(url = defaultEntryUrl, content: any = {}): any { return { startedDateTime: "2026-08-13T12:00:00Z", request: { method: "GET", url, headers: [{ name: "Authorization", value: "synthetic-authorization-value" }] }, response: { status: 200, headers: [], content } }; }
function external(index: number, text: string, discoveredFileNameSecret: string | null = null, discoveredQueryValueSecret: string | null = null): LoadedDdExternalSource { return { lock: lock.externalConfidentialSources[index], text, sourceIdentityFingerprint: "synthetic", discoveredFileNameSecret, discoveredQueryValueSecret }; }
const p: DdProvenance = { captureId: "incremental", mode: "incremental", entryIndex: 0, capturedAt: "2026-08-13T12:00:00.000Z", pathname: "/client_assets", status: 200, bodyState: "observed" };

describe("data download DD0-DD2", () => {
    it("requires the exact source-lock shape and rejects mutation", () => { validateDd0SourceLock(lock); const changed: any = JSON.parse(JSON.stringify(lock)); changed.captures[0].unexpected = true; assert.throws(() => validateDd0SourceLock(changed), /fields mismatch/); const changedHash: any = JSON.parse(JSON.stringify(lock)); changedHash.captures[0].sha256 = "0".repeat(64); assert.throws(() => validateDd0SourceLock(changedHash), /capture lock mismatch/); const changedScreenshot: any = JSON.parse(JSON.stringify(lock)); changedScreenshot.externalScreenshots[0].uiFileCount += 1; assert.throws(() => validateDd0SourceLock(changedScreenshot), /screenshot evidence/); for (const fileName of ["../capture.har", "C:\\capture.har", "\\\\server\\capture.har"]) { const changedPath: any = JSON.parse(JSON.stringify(lock)); changedPath.captures[0].fileName = fileName; assert.throws(() => validateDd0SourceLock(changedPath), /capture lock mismatch/); } for (const fileName of ["../body.json", "C:\\body.json", "\\\\server\\body.json"]) { const changedPath: any = JSON.parse(JSON.stringify(lock)); changedPath.externalConfidentialSources[0].fileName = fileName; assert.throws(() => validateDd0SourceLock(changedPath), /external source evidence/); } });
    it("requires an explicit real capture root without echoing supplied values", () => { const temp = mkdtempSync(join(tmpdir(), "dd-root-")), secret = "synthetic-secret-token"; try { assert.equal(resolveDdCaptureRoot(["--capture-root", temp], {}), realpathSync.native(temp)); assert.equal(resolveDdCaptureRoot([], { [DD_CAPTURE_ROOT_ENV]: temp }), realpathSync.native(temp)); assert.throws(() => resolveDdCaptureRoot([], {}), /required/); assert.throws(() => resolveDdCaptureRoot(["--capture-root", temp], { [DD_CAPTURE_ROOT_ENV]: temp }), /either/); try { resolveDdCaptureRoot(["--capture-root", join(temp, secret)], {}); assert.fail("missing root accepted"); } catch (error) { assert.equal(String(error).includes(secret), false); } } finally { rmSync(temp, { recursive: true, force: true }); } });
    it("rejects forbidden versionable raw artifacts and directories", () => { for (const name of ["capture.har", "raw-body.json", "x.sqlite", "x.cpk", "screenshots/a.json", "data/a.json", "logs/a.json", "attachments/a.json"]) assert.throws(() => validateVersionableTarget(name, "{}"), /forbidden/); const harShape = ['{"log":', '{"entries":[]}}'].join(""); assert.throws(() => validateVersionableTarget("capture.json", harShape), /forbidden/); assert.throws(() => validateVersionableTarget("opaque.bin", "safe\0binary"), /invalid/); });
    it("collects direct and nested query values, request scalars and sensitive values without exposing them", () => { const loaded = [source(0, [entry("https://ishin-global.aktsk.com/client_assets?x=synthetic-query-value", { mimeType: "application/json", text: JSON.stringify({ url: "https://cf.ishin-global.aktsk.com/a.cpk?sig=synthetic-nested-signature" }) })])]; loaded[0].har.log.entries[0].request.postData = { text: JSON.stringify({ scene: "synthetic-request-scalar" }) }; const values = collectDdSensitiveValues(loaded), target = { name: "database-data-download-captures/safe.json", text: "{}" }; assert.equal(values.has("synthetic-query-value"), true); assert.equal(values.has("synthetic-nested-signature"), true); assert.equal(values.has("synthetic-request-scalar"), true); assert.equal(values.has("synthetic-authorization-value"), true); assert.deepEqual(scanVersionableTargets(values, [target]).valid, true); assert.equal(scanVersionableTargets(values, [{ ...target, text: '"synthetic-nested-signature"' }]).valid, false); });
    it("fails closed on malformed HAR and external junctions", () => { const malformed: any = { ...lock, captures: lock.captures.map((value, index) => ({ ...value, sizeBytes: index + 1, sha256: "0".repeat(64), entryCount: 1 })) }; assert.throws(() => buildDd0(malformed, []), /lock mismatch|lineage/); const temp = mkdtempSync(join(tmpdir(), "dd-linked-")), outside = join(temp, "outside"), linked = join(temp, "linked"), regularRoot = join(temp, "regular-root"); try { mkdirSync(outside); mkdirSync(regularRoot); symlinkSync(outside, linked, "junction"); assert.throws(() => resolveDdCaptureRoot(["--capture-root", linked], {}), /symlink|junction/); assert.throws(() => loadDdCaptures(linked, lock), /root validation/); symlinkSync(outside, join(regularRoot, lock.externalConfidentialSources[0].fileName!), "junction"); assert.throws(() => loadDdExternalSources(regularRoot, lock), /external source validation/); } finally { rmSync(temp, { recursive: true, force: true }); } });
    it("rejects malformed HAR JSON and impossible entry cardinality", () => { assert.throws(() => parseDdHar("{", "incremental", 1), /malformed HAR/); const emptyHar = ['{"log":', '{"entries":[]}}'].join(""); assert.throws(() => parseDdHar(emptyHar, "incremental", 1), /entry count/); });
    it("keeps query values and bodies out of DD1 and fails on unknown encoding", () => { const syntheticLock: any = { ...lock, captures: lock.captures.map((value, index) => ({ ...value, entryCount: index === 0 ? 1 : 0 })) }; const loaded = [source(0, [entry()]), source(1), source(2)]; loaded.forEach((value, index) => value.lock = syntheticLock.captures[index]); const dd0: Dd0Dataset = { schemaVersion: 1, contract: "dokkan-data-download-source-audit", contractVersion: "0.1.0", generatedAt: "2026-08-13T12:00:00.000Z", collectionMode: "offline_local_har_no_requests_no_replay", defaultEnabled: false, productionMutation: false, sourceLockSha256: sha256(`${JSON.stringify(syntheticLock, null, 2)}\n`), sources: syntheticLock.captures, externalConfidentialSources: syntheticLock.externalConfidentialSources, externalScreenshots: syntheticLock.externalScreenshots, preTransformClassification: syntheticLock.preTransformClassification }; const result = buildDd1(loaded, syntheticLock, dd0); assert.equal(JSON.stringify(result).includes("123"), false); assert.equal(result.entries[0].deviceAssetSizeBytesQuery.type, "decimal_string"); loaded[0].har.log.entries[0].response.content = { encoding: "br", text: "x" }; assert.throws(() => buildDd1(loaded, syntheticLock, dd0), /unknown content encoding/); });
    it("records form-param request presence without retaining parameter values", () => { const syntheticLock: any = { ...lock, captures: lock.captures.map((value, index) => ({ ...value, entryCount: index === 0 ? 1 : 0 })) }; const value = entry("https://ishin-global.aktsk.com/ondemand_assets"); value.request.method = "POST"; value.request.postData = { mimeType: "application/x-www-form-urlencoded", params: [{ name: "scene", value: "synthetic-private-param" }] }; const loaded = [source(0, [value]), source(1), source(2)]; loaded.forEach((item, index) => item.lock = syntheticLock.captures[index]); const dd0: Dd0Dataset = { schemaVersion: 1, contract: "dokkan-data-download-source-audit", contractVersion: "0.1.0", generatedAt: "2026-08-13T12:00:00.000Z", collectionMode: "offline_local_har_no_requests_no_replay", defaultEnabled: false, productionMutation: false, sourceLockSha256: sha256(`${JSON.stringify(syntheticLock, null, 2)}\n`), sources: syntheticLock.captures, externalConfidentialSources: syntheticLock.externalConfidentialSources, externalScreenshots: syntheticLock.externalScreenshots, preTransformClassification: syntheticLock.preTransformClassification }; const result = buildDd1(loaded, syntheticLock, dd0); assert.equal(result.entries[0].requestBodyPresent, true); assert.equal(JSON.stringify(result).includes("synthetic-private-param"), false); });
    it("enforces exact DD2 bodies, cardinality and sanitized paths", () => { const signedUrl = ["https://cf.ishin-global.aktsk.com/assets/a.cpk?signa", "ture=secret"].join(""); const good = { mimeType: "application/json", text: JSON.stringify({ assets: [{ url: signedUrl, file_path: "assets/a.cpk", algorithm: "sha256", hash: "opaque_hash", size: 10 }], latest_version: 1 }) }; const parsed = parseClientAssetsBody(good, p); assert.equal(parsed.assets[0].urlPathname, "/assets/a.cpk"); assert.equal(JSON.stringify(parsed).includes("signature"), false); for (const path of ["../x.cpk", "/x.cpk", "C:\\x.cpk", "\\\\server\\x.cpk", "\\\\?\\C:\\x.cpk", "a\\b/c.cpk", "a/%2e%2e/x.cpk"]) assert.throws(() => sanitizeDdFilePath(path), /unsafe/); assert.throws(() => sanitizeDdUrlPathname("https://cf.ishin-global.aktsk.com/a/%2e%2e/x.cpk"), /unsafe/); assert.throws(() => parseClientAssetsBody({ mimeType: "application/json", text: JSON.stringify({ assets: [], latest_version: 1 }) }, p), /cardinality/); assert.throws(() => parseClientAssetsBody({ mimeType: "application/json", text: JSON.stringify({ assets: [], latest_version: 1, account: "x" }) }, p), /allowlist/); assert.throws(() => parseClientAssetsBody({ mimeType: "application/json" }, p), /missing body/); });
    it("binds the database contract to exact fields and rejects non-null unreviewed patches", () => { const body = { mimeType: "application/json", text: JSON.stringify({ url: "https://cf.ishin-global.aktsk.com/sqlite/current/en/v/database.db?sig=secret", file_path: "sqlite/current/en/database.db", algorithm: "sha256", hash: "opaque", version: 1, patch_hash: null, patch: null }) }; const parsed = parseDatabaseBody(body, { ...p, pathname: "/client_assets/database" }, 100); assert.equal(parsed.urlPathname, "/sqlite/current/en/v/database.db"); assert.equal(parsed.observedCdnDeclaredSizeBytes, 100); assert.deepEqual(parsed.patch, { descriptorState: "observed_null", hashState: "observed_null" }); const changed = JSON.parse(body.text); changed.patch = "unexpected"; assert.throws(() => parseDatabaseBody({ ...body, text: JSON.stringify(changed) }, { ...p, pathname: "/client_assets/database" }, null), /patch/); });
    it("rejects external manifest duplicates, identity mismatch, URL identity and account-body misuse", () => { const a: ExternalDescriptor = { filePath: "character/card/a.cpk", algorithm: "xxhash", hash: "h", sizeBytes: 1, url: "https://cf.ishin-global.aktsk.com/a?x=1" }, sameIdentityDifferentUrl = { ...a, url: "https://cf.ishin-global.aktsk.com/a?x=2" }; assert.throws(() => validateUniqueExternalDescriptors([a, a], "synthetic"), /duplicate/); verifyExternalOndemandPair([a], [sameIdentityDifferentUrl]); assert.throws(() => verifyExternalOndemandPair([a], [a]), /differ by every URL/); assert.throws(() => verifyExternalOndemandPair([a], [{ ...sameIdentityDifferentUrl, hash: "changed" }]), /agree by identity/); verifyExactExternalSuperset([a], [a, { ...a, filePath: "other/b.cpk" }]); assert.throws(() => verifyExactExternalSuperset([a], [{ ...a, hash: "changed" }]), /exact superset/); const account = external(3, "{}"); assert.throws(() => requireManifestExternalSource(account), /account body/); });
    it("aggregates family and extension without retaining individual paths", () => { const values: ExternalDescriptor[] = [{ filePath: "character/card/a.cpk", algorithm: "xxhash", hash: "h1", sizeBytes: 1, url: "https://example.invalid/a" }, { filePath: "character/card_bg/b.png", algorithm: "xxhash", hash: "h2", sizeBytes: 2, url: "https://example.invalid/b" }, { filePath: "lua/c.lua", algorithm: "xxhash", hash: "h3", sizeBytes: 3, url: "https://example.invalid/c" }]; const summaries = summarizePathFamilies(values), text = JSON.stringify(summaries); assert.equal(summaries.reduce((sum, value) => sum + value.descriptorCount, 0), 3); assert.equal(summaries.reduce((sum, value) => sum + value.totalSizeBytes, 0), 6); assert.equal(text.includes("character/card/a.cpk"), false); assert.equal(text.includes("character/card_bg/b.png"), false); });
    it("treats opaque external account JSON as scanner-only and rejects discovered query secrets", () => { const values = collectDdExternalSensitiveValues([external(3, JSON.stringify({ cards: [{ id: "synthetic-account-secret" }] })), external(2, "{}", "synthetic-discovered-name", "synthetic-discovered-query")]); assert.equal(values.has("synthetic-account-secret"), true); assert.equal(scanVersionableTargets(values, [{ name: "safe.json", text: "{}" }]).valid, true); assert.equal(scanVersionableTargets(values, [{ name: "safe.json", text: '"synthetic-discovered-query"' }]).valid, false); const queryBearingName = ["client_assetsdevice_asset_size_", "bytes=12345678.json"].join(""); assert.equal(scanVersionableTargets(new Set(), [{ name: queryBearingName, text: "{}" }]).valid, false); });
    (process.env[DD_CAPTURE_ROOT_ENV] ? it : it.skip)("validates the pinned confidential sources entirely in memory", () => { const captureRoot = resolveDdCaptureRoot([], process.env), captures = loadDdCaptures(captureRoot, lock), externals = loadDdExternalSources(captureRoot, lock), dd0 = buildDd0(lock, captures, externals), dd1 = buildDd1(captures, lock, dd0), dd2 = buildDd2(captures, externals, lock, dd0, dd1), validation = validateDd2(dd2), text = JSON.stringify(dd2), discovered = externals.find(value => value.lock.sourceId === "download_all_client_assets_manifest")!; assert.equal(validation.valid, true); assert.equal(dd2.ondemand.externalBodyEvidence?.descriptorCount, 4868); assert.equal(dd2.clientAssets.externalFullManifest?.descriptorCount, 25233); assert.equal(dd2.clientAssets.externalFullManifest?.pathFamilySummaries.reduce((sum, value) => sum + value.totalSizeBytes, 0), 22349705433); const drift: any = JSON.parse(JSON.stringify(dd2)); drift.clientAssets.externalFullManifest.latestVersion += 1; assert.equal(validateDd2(drift).valid, false); assert.equal(text.includes(discovered.discoveredFileNameSecret!), false); assert.equal(text.includes(discovered.discoveredQueryValueSecret!), false); assert.equal(text.includes("https://"), false); });
});
