"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = require("assert");
const events_e6_builder_1 = require("./events-e6-builder");
const events_e6_validator_1 = require("./events-e6-validator");
const observation = {
    areas: [{ id: 1, event_image_path: "layout/en/image/mypage.cpk", banner_image_path: null, listbutton_image_path: "remote/banner.png" }],
    questMaps: [{ id: 2, quest_id: 3, sugoroku_bgm_id: 9, battle_bgm_id: 10, boss_bgm_id: 11, battle_background_id: 12, start_script_id: 0, finish_script_id: 13 }], questTargets: [{ id: 3 }],
    zBattleStages: [{ id: 4, banner_image_path: null, listbutton_image_path: null }], zBattleStageViews: [{ id: 40, z_battle_stage_id: 4, enemy_resource_id: 100 }],
    budokais: [], originSeries: [{ id: 5, banner_image_path: null }], originEpisodes: [{ id: 6, origin_series_id: 5, banner_image_path: null, bgm_id: 9 }], originPages: [{ id: 7, origin_episode_id: 6, background_image_path: null, bgm_id: 9 }], originBattles: [{ id: 8, bgm_id: 9, background_id: 2 }],
    sdMaps: [{ id: 9, background_image_id: 1 }], sdArenas: [{ id: 10, sd_map_id: 9, background_image_id: 2 }], linkedMissionCategoryIds: [20], linkedMissionCategories: [{ id: 20, image_path: null }], referencedEnemyCardIds: [11], referencedEnemyCards: [{ id: 11, resource_id: 101 }], unusedAssetPathPatterns: [{ id: 12, file_path_pattern: "raw" }],
};
const apk = { entryCount: 2, assetEntryCount: 2, assetExtensionCounts: { ".acb": 1, ".cpk": 1 }, assetEntryPaths: ["assets/bgm/bgm_009.acb", "assets/layout/en/image/mypage.cpk"], samples: [{ path: "assets/layout/en/image/mypage.cpk", exists: true, sizeBytes: 10, compressedSizeBytes: 8, sha256: "sample" }] };
const baseline = { schemaVersion: 1, sourceApk: { fileName: "dokkan-global-base.apk", sizeBytes: 20, sha256: "apk" }, entryCount: 2, assetEntryCount: 2, samples: [{ path: "assets/layout/en/image/mypage.cpk", sizeBytes: 10, sha256: "sample" }] };
const build = () => (0, events_e6_builder_1.buildEventsE6Dataset)({ observation, apk, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE5Sha256: "e5", sourceApkSha256: "apk", sourceApkSizeBytes: 20 });
describe("events E6 assets", () => {
    it("separates structural references from binary delivery", () => { const dataset = build(), prefixed = dataset.pathAssets.find(value => value.rawPath.includes("mypage")), absent = dataset.pathAssets.find(value => value.rawPath.includes("remote")); (0, assert_1.equal)(prefixed.baseApkLiteralEntryStatus, "absent_literal"); (0, assert_1.equal)(prefixed.baseApkPrefixedCandidate?.status, "partial"); (0, assert_1.equal)(prefixed.deliveryStatus, "unknown_requires_downloaded_container_or_endpoint"); (0, assert_1.equal)(absent.deliveryStatus, "unknown_requires_downloaded_container_or_endpoint"); (0, assert_1.equal)((0, events_e6_validator_1.validateEventsE6Dataset)(dataset, observation, apk, baseline, true).valid, true); });
    it("keeps filename-based BGM matches partial", () => { const dataset = build(), bgm = dataset.numericAssets.find(value => value.assetKey === "bgm:9"); (0, assert_1.equal)(bgm.bundledCandidates.length, 1); (0, assert_1.equal)(bgm.bundledCandidates[0].status, "partial"); });
    it("rejects a dangling structural consumer", () => { const dataset = build(), inconsistent = { ...observation, zBattleStageViews: [{ ...observation.zBattleStageViews[0], z_battle_stage_id: 999 }] }; (0, assert_1.equal)((0, events_e6_builder_1.buildEventsE6Coverage)(dataset, inconsistent).danglingIdCount, 1); (0, assert_1.equal)((0, events_e6_validator_1.validateEventsE6Dataset)(dataset, inconsistent, apk, baseline, true).valid, false); });
    it("rejects a referenced enemy card omitted from joined rows", () => { const inconsistent = { ...observation, referencedEnemyCardIds: [11, 999] }; const dataset = (0, events_e6_builder_1.buildEventsE6Dataset)({ observation: inconsistent, apk, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE5Sha256: "e5", sourceApkSha256: "apk", sourceApkSizeBytes: 20 }); (0, assert_1.equal)((0, events_e6_builder_1.buildEventsE6Coverage)(dataset, inconsistent).danglingIdCount, 1); });
    it("rejects a linked mission category omitted from joined rows", () => { const inconsistent = { ...observation, linkedMissionCategoryIds: [20, 999] }; const dataset = (0, events_e6_builder_1.buildEventsE6Dataset)({ observation: inconsistent, apk, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE5Sha256: "e5", sourceApkSha256: "apk", sourceApkSizeBytes: 20 }); (0, assert_1.equal)((0, events_e6_builder_1.buildEventsE6Coverage)(dataset, inconsistent).danglingIdCount, 1); });
    it("pins every representative APK sample", () => { (0, assert_1.equal)((0, events_e6_validator_1.validateEventsE6ApkBaseline)(baseline, apk, "apk", 20), true); const changed = { ...apk, samples: [{ ...apk.samples[0], sha256: "changed" }] }; (0, assert_1.equal)((0, events_e6_validator_1.validateEventsE6ApkBaseline)(baseline, changed, "apk", 20), false); });
});
//# sourceMappingURL=events-e6-builder.spec.js.map