"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = require("assert");
const events_e1_builder_1 = require("./events-e1-builder");
const events_e1_validator_1 = require("./events-e1-validator");
const observation = { areas: [{ id: 1, type: "raw", category: 9, chapter_id: 2, db_story_id: null, name: "title", event_priority: 3, all_clear_bonus_stones: 1, first_released_at: null, mission_difficulty: null }], chapters: [{ id: 2, name: "chapter", open_at: "time" }], chapterProperties: [{ id: 1, chapter_id: 2, start_at: "time" }], dbStories: [], zBattleStages: [], zBattleStageViews: [], budokais: [], originSeries: [], originEpisodes: [], originPages: [], sdMaps: [], sdPacks: [], opaqueRootFamilies: [{ family: "rmbattle", sourceTable: "rmbattle_missions", sourceColumn: "rmbattle_id", ids: [4], sourceRowCount: 1, missingRootTable: true }], unrootedCandidateTables: [{ table: "score_benefits", rowCount: 2 }] };
describe("events E1 catalog", () => {
    it("keeps identity structural and schedules separate", () => { const dataset = (0, events_e1_builder_1.buildEventsE1Dataset)({ observation, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE0Sha256: "e0" }); (0, assert_1.equal)(dataset.catalog[0].identity.id, "1"); (0, assert_1.equal)(dataset.catalog[0].presentation?.title, "title"); (0, assert_1.equal)(dataset.availabilityHints.length, 2); (0, assert_1.equal)((0, events_e1_validator_1.validateEventsE1Dataset)(dataset, observation).valid, true); });
    it("rejects a text-derived or dangling identity mutation", () => { const dataset = (0, events_e1_builder_1.buildEventsE1Dataset)({ observation, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE0Sha256: "e0" }); dataset.catalog[0].identity.id = "title"; (0, assert_1.equal)((0, events_e1_validator_1.validateEventsE1Dataset)(dataset, observation).valid, false); });
    it("rejects omitted catalog records", () => { const dataset = (0, events_e1_builder_1.buildEventsE1Dataset)({ observation, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE0Sha256: "e0" }); dataset.catalog.pop(); (0, assert_1.equal)((0, events_e1_validator_1.validateEventsE1Dataset)(dataset, observation).valid, false); });
    it("rejects duplicate Z-Battle views before Map projection can hide them", () => { const changed = JSON.parse(JSON.stringify(observation)); changed.zBattleStages = [{ id: 8, type: "raw", priority: 1, related_z_battle_stage_id: null, start_at: null, end_at: null, eventkagi_start_at: null, eventkagi_end_at: null, enable_battle_auto: 0 }]; changed.zBattleStageViews = [{ id: 1, z_battle_stage_id: 8, enemy_name: "a", enemy_nickname: "", enemy_resource_id: 2 }, { id: 2, z_battle_stage_id: 8, enemy_name: "b", enemy_nickname: "", enemy_resource_id: 3 }]; const dataset = (0, events_e1_builder_1.buildEventsE1Dataset)({ observation: changed, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE0Sha256: "e0" }); (0, assert_1.equal)((0, events_e1_validator_1.validateEventsE1Dataset)(dataset, changed).valid, false); });
    it("rejects missing and orphan Z-Battle views even when counts match", () => { const changed = JSON.parse(JSON.stringify(observation)); changed.zBattleStages = [8, 9].map(value => ({ id: value, type: "raw", priority: 1, related_z_battle_stage_id: null, start_at: null, end_at: null, eventkagi_start_at: null, eventkagi_end_at: null, enable_battle_auto: 0 })); changed.zBattleStageViews = [8, 999].map((value, index) => ({ id: index + 1, z_battle_stage_id: value, enemy_name: "a", enemy_nickname: "", enemy_resource_id: 2 })); const dataset = (0, events_e1_builder_1.buildEventsE1Dataset)({ observation: changed, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE0Sha256: "e0" }); (0, assert_1.equal)((0, events_e1_validator_1.validateEventsE1Dataset)(dataset, changed).valid, false); });
});
//# sourceMappingURL=events-e1-builder.spec.js.map