"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = require("assert");
const events_e8_builder_1 = require("./events-e8-builder");
const events_e8_validator_1 = require("./events-e8-validator");
const profile = { schemaVersion: 1, contract: "dokkan-events-database-first-refresh-profile", contractVersion: "0.9.0", profileId: "snapshot", baselineFiles: [{ role: "e0_inventory", fileName: "e0.json", sha256: "0" }, { role: "e3_goldens", fileName: "e3.json", sha256: "3" }, { role: "e4_native_evidence", fileName: "e4.json", sha256: "4" }, { role: "e6_apk", fileName: "e6.json", sha256: "6" }], requiredSources: { database: { sizeBytes: 1, sha256: "db" }, elf: { sizeBytes: 2, sha256: "elf" }, apk: { sizeBytes: 3, sha256: "apk" } } };
const values = [
    { gate: 1, key: "event_catalog", version: "0.2.0", lineage: { sourceDatabaseSha256: "db", sourceE0Sha256: "e0" } },
    { gate: 2, key: "stage_topology", version: "0.3.0", lineage: { sourceDatabaseSha256: "db", sourceE1Sha256: "p1" } },
    { gate: 3, key: "encounters", version: "0.4.0", lineage: { sourceDatabaseSha256: "db", sourceE2Sha256: "p2" } },
    { gate: 4, key: "boss_mechanics", version: "0.5.0", lineage: { sourceDatabaseSha256: "db", sourceE3Sha256: "p3", sourceE2Sha256: "p2", sourceElfSha256: "elf", nativeEvidenceSha256: "native" } },
    { gate: 5, key: "rewards", version: "0.6.0", lineage: { sourceDatabaseSha256: "db", sourceE4Sha256: "p4", sourceE2Sha256: "p2", sourceE1Sha256: "p1" } },
    { gate: 6, key: "asset_references", version: "0.7.0", lineage: { sourceDatabaseSha256: "db", sourceE5Sha256: "p5", sourceApkSha256: "apk", apkBaselineSha256: "6" } },
];
const sidecars = values.map(value => ({ key: value.key, role: value.key, gate: value.gate, contractVersion: value.version, manifestFileName: `m${value.gate}.json`, payload: { fileName: `p${value.gate}.json`, sha256: `p${value.gate}`, sizeBytes: value.gate * 10 }, coverage: { fileName: `c${value.gate}.json`, sha256: `c${value.gate}`, sizeBytes: 1, counts: { danglingIdCount: 0 } }, validation: { fileName: `v${value.gate}.json`, sha256: `v${value.gate}`, sizeBytes: 1, value: value.gate === 1 ? { valid: true } : { valid: true, exactProjection: true } }, lineage: value.lineage }));
const sourceAnchors = { inventory: { contractVersion: "0.1.0", fileName: "e0.json", sha256: "e0", sizeBytes: 1 }, elf: { sha256: "elf", sizeBytes: 2, nativeEvidenceSha256: "native" }, apk: { sha256: "apk", sizeBytes: 3, apkBaselineSha256: "6" } };
const build = (inputs = sidecars) => (0, events_e8_builder_1.buildEventsE8Registry)({ sidecars: inputs, sourceAnchors, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", refreshProfile: profile, refreshProfileSha256: "profile" });
const validate = (inputs = sidecars) => (0, events_e8_validator_1.validateEventsE8Registry)(build(inputs), { sidecars: inputs, sourceAnchors, refreshProfile: profile, refreshProfileSha256: "profile", payloadHashesValid: true, coverageHashesValid: true, validationHashesValid: true });
describe("events E8 sidecars and refresh", () => {
    it("builds optional sidecars without enabling production", () => { const registry = build(); (0, assert_1.equal)(registry.sidecars.length, 6); (0, assert_1.deepEqual)(registry.delivery, { optional: true, defaultPipelineEnabled: false, productionReplacement: false, r2Published: false, androidConsumed: false }); (0, assert_1.equal)(validate().valid, true); });
    it("rejects a broken lineage chain", () => { const changed = sidecars.map(value => value.gate === 5 ? { ...value, lineage: { ...value.lineage, sourceE4Sha256: "old" } } : value); const validation = (0, events_e8_validator_1.validateEventsE8Registry)(build(changed), { sidecars: changed, sourceAnchors, refreshProfile: profile, refreshProfileSha256: "profile", payloadHashesValid: true, coverageHashesValid: true, validationHashesValid: true }); (0, assert_1.equal)(validation.valid, false); (0, assert_1.equal)(validation.lineageChainValid, false); });
    it("anchors E1 to E0 and mechanics/assets to external binaries", () => { const changed = sidecars.map(value => value.gate === 1 ? { ...value, lineage: { ...value.lineage, sourceE0Sha256: "old" } } : value); (0, assert_1.equal)((0, events_e8_validator_1.validateEventsE8Registry)(build(changed), { sidecars: changed, sourceAnchors, refreshProfile: profile, refreshProfileSha256: "profile", payloadHashesValid: true, coverageHashesValid: true, validationHashesValid: true }).lineageChainValid, false); });
    it("rejects a refresh profile missing an explicit baseline role", () => { const changedProfile = { ...profile, baselineFiles: profile.baselineFiles.slice(1) }; const validation = (0, events_e8_validator_1.validateEventsE8Registry)(build(), { sidecars, sourceAnchors, refreshProfile: changedProfile, refreshProfileSha256: "profile", payloadHashesValid: true, coverageHashesValid: true, validationHashesValid: true }); (0, assert_1.equal)(validation.refreshProfileValid, false); (0, assert_1.equal)(validation.valid, false); });
    it("rejects a source validation that is not green", () => { const changed = sidecars.map(value => value.gate === 3 ? { ...value, validation: { ...value.validation, value: { valid: false, exactProjection: true } } } : value); (0, assert_1.equal)((0, events_e8_validator_1.validateEventsE8Registry)(build(changed), { sidecars: changed, sourceAnchors, refreshProfile: profile, refreshProfileSha256: "profile", payloadHashesValid: true, coverageHashesValid: true, validationHashesValid: true }).valid, false); });
    it("accounts payload bytes and dangling IDs", () => { const coverage = (0, events_e8_builder_1.buildEventsE8Coverage)(build()); (0, assert_1.equal)(coverage.totalPayloadBytes, 210); (0, assert_1.equal)(coverage.danglingIdCount, 0); (0, assert_1.equal)(coverage.invalidValidationCount, 0); });
    it("rejects malformed dangling coverage instead of coercing it to zero", () => { const changed = sidecars.map(value => value.gate === 2 ? { ...value, coverage: { ...value.coverage, counts: {} } } : value); let message = ""; try {
        (0, events_e8_builder_1.buildEventsE8Coverage)(build(changed));
    }
    catch (error) {
        message = String(error.message);
    } (0, assert_1.equal)(message.includes("incompatible danglingIdCount"), true); });
    it("creates a deterministic receipt with isolated gate order", () => { const receipt = (0, events_e8_builder_1.buildEventsE8RefreshReceipt)(build()); (0, assert_1.deepEqual)(receipt.gateOrder, ["E0", "E1", "E2", "E3", "E4", "E5", "E6", "E8"]); (0, assert_1.equal)(receipt.refreshedSidecars[5].key, "asset_references"); });
});
//# sourceMappingURL=events-e8-builder.spec.js.map