"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = require("assert");
const events_e3_builder_1 = require("./events-e3-builder");
const events_e3_validator_1 = require("./events-e3-validator");
const skill = { id: 9, exec_timing_type: 1, turn: 1, is_once: 0, probability: 100, causality_conditions: "{}", target_type: 1, target_value1: 0, target_value2: 0, target_value3: 0, sub_target_type_set_id: null, efficacy_type: 2, eff_value1: 3, eff_value2: 4, eff_value3: 5, efficacy_values: "[]", calc_option: 0 };
const observation = {
    questEncounters: [{ sourceId: 2, displayTypeRaw: "normal", battles: [{ position: 0, rounds: [{ position: 0, roundNoRaw: 1, commentRaw: null, enemies: [{ position: 0, cardId: 7, enemySkillIds: [9], enemyRoundSkillSetId: 11 }] }, { position: 1, roundNoRaw: 2, commentRaw: null, enemies: [{ position: 0, cardId: 7, enemySkillIds: [], enemyRoundSkillSetId: null }, { position: 1, cardId: 7, enemySkillIds: [], enemyRoundSkillSetId: null }] }] }, { position: 1, rounds: [{ position: 0, roundNoRaw: 1, commentRaw: null, enemies: [{ position: 0, cardId: 7, enemySkillIds: [], enemyRoundSkillSetId: null }] }] }] }],
    originEncounters: [{ sourceId: 3, displayTypeRaw: "normal", battles: [{ position: 0, rounds: [{ position: 0, roundNoRaw: 1, commentRaw: null, enemies: [{ position: 0, cardId: 7, enemySkillIds: [9], enemyRoundSkillSetId: null }] }, { position: 1, roundNoRaw: 2, commentRaw: null, enemies: [{ position: 0, cardId: 7, enemySkillIds: [], enemyRoundSkillSetId: null }] }] }] }],
    referencedCards: [{ id: 7, character_id: 8, card_unique_info_id: null, resource_id: 70, rarity: 1, element: 2, lv_max: 80, hp_init: 1, hp_max: 2, atk_init: 3, atk_max: 4, def_init: 5, def_max: 6 }], referencedCharacters: [{ id: 8, race: 1, sex: 2, size: 3 }], referencedEnemySkills: [skill], referencedRoundSkillSets: [{ id: 11, effect_description: "e", cancel_description: "c" }], referencedRoundSkillSetRelations: [{ id: 12, enemy_round_skill_set_id: 11, enemy_round_skill_id: 13 }], referencedRoundSkills: [{ ...skill, id: 13, is_eternal: 0 }],
    zBattleEnemies: [{ id: 20, z_battle_stage_id: 4, ordinal_num: 1, start_level: 1, end_level: 10, base_hp: 1, base_attack: 2, base_defence: 3, hp_escalation_type: 30, attack_escalation_type: 30, defence_escalation_type: 30, special_attack_escalation_type: 30, card_escalation_type: 31, performance_escalation_type: 0, skill_escalation_type: 32 }], zBattleCardEscalations: [{ id: 40, escalation_type: 31, level: 1, card_id: 7 }], zBattleSkillEscalations: [{ id: 41, escalation_type: 32, level: 1, enemy_skill_id: 9 }], zBattleStatusEscalations: [{ id: 42, escalation_type: 30, level: 1, escalation_value: 100 }], zBattlePowerupThresholds: [{ id: 43, z_battle_stage_id: 4, hp: 1, atk: 2, def: 3, special_atk: 4 }], sdStageEnemyReferences: [{ id: 5, sd_enemy_table_id: 99 }],
};
const e2 = { questStages: [{ levels: [{ identity: { id: "2" } }] }], unboundQuestLevels: [], originBattles: [{ identity: { id: "3" } }], zBattleTopologies: [{ identity: { stageId: "4" } }], sdTopologies: [{ arenas: [{ stages: [{ identity: { stageId: "5" } }] }] }] };
const build = () => (0, events_e3_builder_1.buildEventsE3Dataset)({ observation, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE2Sha256: "e2" });
describe("events E3 encounters", () => {
    it("preserves ordered encounter topology and explicit stat boundaries", () => { const dataset = build(), goldens = (0, events_e3_builder_1.buildEventsE3Goldens)(dataset); (0, assert_1.equal)(dataset.questEncounters[0].battles[0].rounds[1].enemies[1].ordinal, 1); (0, assert_1.equal)(dataset.cardReferences[0].enemyRuntimeApplication.status, "unknown"); (0, assert_1.equal)(dataset.zBattleEnemyRanges[0].stats.status, "partial"); (0, assert_1.equal)((0, events_e3_validator_1.validateEventsE3Dataset)(dataset, observation, e2, goldens, goldens).valid, true); });
    it("rejects dangling card identities", () => { const expected = (0, events_e3_builder_1.buildEventsE3Goldens)(build()), dataset = build(); dataset.questEncounters[0].battles[0].rounds[0].enemies[0].cardId = "999"; const goldens = (0, events_e3_builder_1.buildEventsE3Goldens)(dataset); (0, assert_1.equal)((0, events_e3_builder_1.buildEventsE3Coverage)(dataset, e2).danglingIdCount, 1); (0, assert_1.equal)((0, events_e3_validator_1.validateEventsE3Dataset)(dataset, observation, e2, goldens, expected).valid, false); });
    it("rejects omitted escalation points", () => { const expected = (0, events_e3_builder_1.buildEventsE3Goldens)(build()), dataset = build(); dataset.zBattleStatusCurves[0].points = []; (0, assert_1.equal)((0, events_e3_validator_1.validateEventsE3Dataset)(dataset, observation, e2, (0, events_e3_builder_1.buildEventsE3Goldens)(dataset), expected).valid, false); });
    it("counts orphaned Z thresholds as dangling", () => { const dataset = build(); dataset.zBattlePowerupThresholds[0].stageId = "999"; (0, assert_1.equal)((0, events_e3_builder_1.buildEventsE3Coverage)(dataset, e2).danglingIdCount, 1); });
});
//# sourceMappingURL=events-e3-builder.spec.js.map