import * as assert from "assert";
import { buildWt0, makeExternalSourceLock } from "./wt0-audit";

const SYNTHETIC_EVENT = 9007190000000007, SYNTHETIC_MAP = 9007190000000701;
const har = (validator = "v1") => JSON.stringify({ log: { entries: [
    { request: { method: "GET", url: `https://example.invalid/budokais/${SYNTHETIC_EVENT}/entry?cursor=private`, headers: [{ name: "Authorization", value: "Bearer synthetic-secret-value" }] }, response: { status: 200, headers: [{ name: "ETag", value: validator }], content: { text: JSON.stringify({ id: SYNTHETIC_EVENT, name: "Synthetic event", participant: 9007190000099999, budokai_maps: [{ id: SYNTHETIC_MAP, budokai_id: SYNTHETIC_EVENT }] }) } } },
    { request: { method: "GET", url: `https://example.invalid/budokais/${SYNTHETIC_EVENT}/entry?cursor=private`, headers: [{ name: "If-None-Match", value: validator }] }, response: { status: 304, headers: [], content: {} } },
    { request: { method: "POST", url: `https://example.invalid/budokais/${SYNTHETIC_EVENT}/tournaments`, headers: [], postData: { text: JSON.stringify({ sign: "synthetic-request-sign" }) } }, response: { status: 200, headers: [], content: { text: JSON.stringify({ sign: "synthetic-response-sign" }) } } }
] } });

describe("world tournament WT0", () => {
    it("is deterministic, shape-only and proves matching 304 validators", () => { const source = har(), lock = makeExternalSourceLock(source), a = buildWt0(source, lock), b = buildWt0(source, lock), serialized = JSON.stringify(a); assert.deepEqual(a, b); assert.equal(a.cacheRelations.length, 1); assert.equal(a.structuralIds.some(value => value.kind === "budokai" && value.id === SYNTHETIC_EVENT), true); assert.equal(a.entries.at(-1)?.responseBodyDisposition, "opaque_envelope_schema_only"); for (const forbidden of ["private", "synthetic-secret-value", "synthetic-request-sign", "synthetic-response-sign", "Synthetic event", "9007190000099999"]) assert.equal(serialized.includes(forbidden), false); });
    it("fails closed on source drift", () => { const source = har(), lock = makeExternalSourceLock(source); assert.throws(() => buildWt0(`${source} `, lock), /source lock mismatch/); });
    it("does not retain an unproved 304 relation", () => { const source = har("one").replace('"If-None-Match","value":"one"', '"If-None-Match","value":"two"'), dataset = buildWt0(source, makeExternalSourceLock(source)); assert.equal(dataset.cacheRelations.length, 0); });
    it("retains an unknown WT route as shape-only evidence", () => { const source = JSON.stringify({ log: { entries: [{ request: { method: "GET", url: `https://example.invalid/budokais/${SYNTHETIC_EVENT}/future_surface/9007190000000009`, headers: [] }, response: { status: 200, headers: [], content: { text: "{}" } } }] } }), dataset = buildWt0(source, makeExternalSourceLock(source)); assert.equal(dataset.entries[0].route, "/budokais/:id/:opaque/:id"); assert.equal(dataset.entries[0].classification, "unknown"); });
    it("rejects forged cache lineage", () => { const source = har(), lock = makeExternalSourceLock(source), dataset = buildWt0(source, lock); dataset.cacheRelations[0].sourceEntryIndex = 2; const { validateWt0 } = require("./wt0-audit") as typeof import("./wt0-audit"); assert.equal(validateWt0(dataset, lock).valid, false); });
    it("fails closed on an unmodeled WT method", () => { const source = JSON.stringify({ log: { entries: [{ request: { method: "PATCH", url: `https://example.invalid/budokais/${SYNTHETIC_EVENT}`, headers: [] }, response: { status: 200, headers: [], content: {} } }] } }); assert.throws(() => buildWt0(source, makeExternalSourceLock(source)), /unsupported WT method/); });
    it("preserves a root Budokai identity route", () => { const source = JSON.stringify({ log: { entries: [{ request: { method: "GET", url: `https://example.invalid/budokais/${SYNTHETIC_EVENT}`, headers: [] }, response: { status: 200, headers: [], content: { text: "{}" } } }] } }), dataset = buildWt0(source, makeExternalSourceLock(source)); assert.equal(dataset.entries[0].route, "/budokais/:budokai_id"); });
    it("fails closed on a malformed HAR entry", () => { const source = JSON.stringify({ log: { entries: [{ request: { method: "GET", url: `https://example.invalid/budokais/${SYNTHETIC_EVENT}` } }] } }); assert.throws(() => buildWt0(source, makeExternalSourceLock(source)), /malformed HAR entry/); });
    it("rejects a literal-bearing forged route", () => { const source = har(), lock = makeExternalSourceLock(source), dataset = buildWt0(source, lock); dataset.entries[0].route = "/budokais/alice-private-token"; const { validateWt0 } = require("./wt0-audit") as typeof import("./wt0-audit"); assert.equal(validateWt0(dataset, lock).valid, false); });
});
