import * as assert from "assert"; import { buildWt0, makeExternalSourceLock } from "./wt0-audit"; import { buildWt1, validateWt1 } from "./wt1-catalog";
const routes = ["/resources/home", "/bonus_schedules", "/budokais/7/entry", "/budokais/7/ranks", "/budokais/7/rankings", "/budokais/7/rankings/borders", "/budokais/7/rankings/friends", "/budokais/7/box_rankings/71", "/quests/0/briefing"];
function source(): string { const entries: unknown[] = routes.map(path => ({ request: { method: "GET", url: `https://example.invalid${path}`, headers: [] }, response: { status: 200, headers: [], content: { text: "{}" } } })); entries.push({ request: { method: "POST", url: "https://example.invalid/budokais/7/tournaments", headers: [], postData: { text: "{\"sign\":\"synthetic-request\"}" } }, response: { status: 200, headers: [], content: { text: "{\"sign\":\"synthetic-response\"}" } } }); return JSON.stringify({ log: { entries } }); }
describe("world tournament WT1", () => {
    it("catalogs every required route deterministically", () => { const raw = source(), wt0 = buildWt0(raw, makeExternalSourceLock(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, a = buildWt1(wt0, text), b = buildWt1(wt0, text); assert.deepEqual(a, b); assert.equal(validateWt1(a).valid, true); assert.equal(a.requiredSurface.every(value => value.status === "observed"), true); });
    it("rejects input bytes that do not exactly bind WT0", () => { const raw = source(), wt0 = buildWt0(raw, makeExternalSourceLock(raw)); assert.throws(() => buildWt1(wt0, `${JSON.stringify(wt0, null, 2)} `), /exact WT0 input mismatch/); });
    it("rejects a missing route", () => { const raw = source(), wt0 = buildWt0(raw, makeExternalSourceLock(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, dataset = buildWt1(wt0, text); dataset.requiredSurface[0].status = "unknown"; assert.equal(validateWt1(dataset).valid, false); });
    it("preserves type to occurrence association", () => { const raw = JSON.parse(source()); raw.log.entries.push({ request: { method: "GET", url: "https://example.invalid/resources/home", headers: [] }, response: { status: 200, headers: [], content: { text: "{\"budokai\":{\"id\":7}}" } } }, { request: { method: "GET", url: "https://example.invalid/resources/home", headers: [] }, response: { status: 200, headers: [], content: { text: "{\"budokai\":{\"id\":\"synthetic\"}}" } } }); const text = JSON.stringify(raw), wt0 = buildWt0(text, makeExternalSourceLock(text)), wt0Text = `${JSON.stringify(wt0, null, 2)}\n`, catalog = buildWt1(wt0, wt0Text), node = catalog.routes.find(value => value.route === "/resources/home")!.responseSchema.find(value => value.path === "$.budokai.id")!; assert.deepEqual(node.types, ["number", "string"]); assert.equal(node.typeOccurrences.length, 2); assert.notDeepEqual(node.typeOccurrences[0].observedEntryIndexes, node.typeOccurrences[1].observedEntryIndexes); });
    it("does not let GET satisfy the POST start contract", () => { const raw = source(), wt0 = buildWt0(raw, makeExternalSourceLock(raw)), start = wt0.entries.find(value => value.route.endsWith("/tournaments"))!; start.method = "GET"; start.traffic = "read_observed"; const text = `${JSON.stringify(wt0, null, 2)}\n`; assert.throws(() => buildWt1(wt0, text), /required observed surface/); });
    it("rejects a canonical but semantically forged WT0", () => { const raw = source(), wt0 = buildWt0(raw, makeExternalSourceLock(raw)); wt0.contract = "forged" as never; assert.throws(() => buildWt1(wt0, `${JSON.stringify(wt0, null, 2)}\n`), /exact WT0 input mismatch/); });
    it("rejects forged route and required-surface contracts", () => { const raw = source(), wt0 = buildWt0(raw, makeExternalSourceLock(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, catalog = buildWt1(wt0, text); catalog.routes[0].route = "/budokais/private-literal"; catalog.requiredSurface.pop(); assert.equal(validateWt1(catalog).valid, false); });
    it("rejects forged scope, schema type and GET traffic", () => { const raw = source(), wt0 = buildWt0(raw, makeExternalSourceLock(raw)), text = `${JSON.stringify(wt0, null, 2)}\n`, catalog = buildWt1(wt0, text), get = catalog.routes.find(value => value.method === "GET" && value.responseSchema.length > 0)!; get.classification = "opaque"; get.traffic = "mutation_observed_not_replayable"; get.responseSchema[0].types = ["forged" as never]; assert.equal(validateWt1(catalog).valid, false); });
});
