import { createHash } from "crypto";
import { Wt0Dataset, WtSchemaNode } from "./wt0-contract";
import { validateWt0 } from "./wt0-audit";
import { Wt1Dataset, Wt1Route, Wt1SchemaOccurrence, Wt1Validation } from "./wt1-contract";

const REQUIRED: Array<{ method: "GET" | "POST"; route: string }> = ["/resources/home", "/bonus_schedules", "/budokais/:budokai_id/entry", "/budokais/:budokai_id/ranks", "/budokais/:budokai_id/rankings", "/budokais/:budokai_id/rankings/borders", "/budokais/:budokai_id/rankings/friends", "/budokais/:budokai_id/box_rankings/:box_ranking_id", "/quests/:quest_id/briefing"].map(route => ({ method: "GET", route })) as Array<{ method: "GET"; route: string }>; REQUIRED.push({ method: "POST", route: "/budokais/:budokai_id/tournaments" });
function sha256(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function occurrences(rows: Array<{ entryIndex: number; schema: WtSchemaNode[] }>): Wt1SchemaOccurrence[] {
    const values = new Map<string, { path: string; types: Map<WtSchemaNode["types"][number], Set<number>>; indexes: Set<number> }>();
    for (const row of rows) for (const node of row.schema) { const value = values.get(node.path) ?? { path: node.path, types: new Map(), indexes: new Set() }; for (const type of node.types) { const indexes = value.types.get(type) ?? new Set<number>(); indexes.add(row.entryIndex); value.types.set(type, indexes); } value.indexes.add(row.entryIndex); values.set(node.path, value); }
    return [...values.values()].map(value => ({ path: value.path, types: [...value.types.keys()].sort(), observedEntryIndexes: [...value.indexes].sort((a, b) => a - b), typeOccurrences: [...value.types].map(([type, indexes]) => ({ type, observedEntryIndexes: [...indexes].sort((a, b) => a - b) })).sort((a, b) => a.type.localeCompare(b.type)) })).sort((a, b) => a.path.localeCompare(b.path));
}
export function buildWt1(wt0: Wt0Dataset, wt0Text: string): Wt1Dataset {
    const lock = { ...wt0.source, fileName: "world_tournament_until_start_crash.har" as const }; if (!validateWt0(wt0, lock).valid || `${JSON.stringify(wt0, null, 2)}\n` !== wt0Text) throw new Error("WT1 exact WT0 input mismatch");
    const grouped = new Map<string, typeof wt0.entries>();
    for (const entry of wt0.entries) { const key = `${entry.method} ${entry.route}`, prior = grouped.get(key) ?? []; prior.push(entry); grouped.set(key, prior); }
    const routes: Wt1Route[] = [...grouped].map(([, rows]) => {
        const classifications = new Set(rows.map(value => value.classification)), traffic = new Set(rows.map(value => value.traffic)); if (classifications.size !== 1 || traffic.size !== 1) throw new Error("WT1 route classification drift");
        return { method: rows[0].method, route: rows[0].route, classification: rows[0].classification, statuses: [...new Set(rows.map(value => value.status))].sort((a, b) => a - b), observedEntryIndexes: rows.map(value => value.entryIndex).sort((a, b) => a - b), traffic: rows[0].traffic, queryKeyNames: [...new Set(rows.flatMap(value => value.queryKeyNames))].sort(), requestSchema: occurrences(rows.map(value => ({ entryIndex: value.entryIndex, schema: value.requestSchema }))), responseSchema: occurrences(rows.map(value => ({ entryIndex: value.entryIndex, schema: value.responseSchema }))) };
    }).sort((a, b) => `${a.route} ${a.method}`.localeCompare(`${b.route} ${b.method}`));
    const dataset: Wt1Dataset = { schemaVersion: 1, contract: "dokkan-world-tournament-route-schema-catalog", contractVersion: "0.2.0", source: { contractVersion: wt0.contractVersion, sizeBytes: Buffer.byteLength(wt0Text), sha256: sha256(wt0Text) }, valuePolicy: "schema_paths_types_and_structural_route_parameters_only", routes, requiredSurface: REQUIRED.map(required => ({ ...required, status: routes.some(value => value.method === required.method && value.route === required.route) ? "observed" : "unknown" })) };
    const validation = validateWt1(dataset); if (!validation.valid) throw new Error(`WT1 validation failed: ${validation.failures.join(", ")}`); return dataset;
}
export function validateWt1(dataset: Wt1Dataset): Wt1Validation {
    const failures: string[] = [], keys = new Set<string>();
    if (dataset.schemaVersion !== 1 || dataset.contract !== "dokkan-world-tournament-route-schema-catalog" || dataset.contractVersion !== "0.2.0" || dataset.valuePolicy !== "schema_paths_types_and_structural_route_parameters_only" || dataset.source.contractVersion !== "0.1.0" || !Number.isSafeInteger(dataset.source.sizeBytes) || dataset.source.sizeBytes <= 0 || !/^[a-f0-9]{64}$/.test(dataset.source.sha256)) failures.push("contract");
    const canonicalRoute = /^(?:\/(?:resources\/home|bonus_schedules|budokais\/:budokai_id(?:\/(?:entry|ranks|rankings(?:\/borders|\/friends)?|box_rankings\/:box_ranking_id|tournaments))?|quests\/:quest_id\/briefing|images\/:locale\/(?:budokai|:wt_help_collection)\/:asset)|\/(?:budokais|images|quests)(?:\/:id|\/:opaque)+)$/;
    const schemaTypes = new Set(["array", "boolean", "null", "number", "object", "string"]), routeScope = (route: string) => route === "/bonus_schedules" || route.endsWith("/ranks") ? "global" : route.endsWith("/rankings/borders") || route.includes("/briefing") || route === "/resources/home" || route.includes("/box_rankings/") ? "partial" : route.includes("/rankings") || route.endsWith("/entry") ? "account_scoped" : route.endsWith("/tournaments") ? "opaque" : "unknown";
    for (const route of dataset.routes) { const key = `${route.method} ${route.route}`; if (keys.has(key)) failures.push("duplicate route"); keys.add(key); const schemaInvalid = [...route.requestSchema, ...route.responseSchema].some(value => { const occurrenceUnion = [...new Set(value.typeOccurrences.flatMap(item => item.observedEntryIndexes))].sort((a, b) => a - b); return !value.path.startsWith("$") || value.types.some(type => !schemaTypes.has(type)) || value.typeOccurrences.length !== value.types.length || JSON.stringify(occurrenceUnion) !== JSON.stringify(value.observedEntryIndexes) || value.typeOccurrences.some(item => !schemaTypes.has(item.type) || !value.types.includes(item.type) || item.observedEntryIndexes.length === 0 || item.observedEntryIndexes.some(index => !route.observedEntryIndexes.includes(index))); }); if (!canonicalRoute.test(route.route) || !["GET", "POST"].includes(route.method) || route.classification !== routeScope(route.route) || route.observedEntryIndexes.length === 0 || new Set(route.observedEntryIndexes).size !== route.observedEntryIndexes.length || route.statuses.length === 0 || route.statuses.some(status => !Number.isInteger(status) || status < 0 || status > 599) || route.queryKeyNames.some(name => !name || name.includes("=")) || schemaInvalid) failures.push("route schema"); if ((route.method === "POST" && route.traffic !== "mutation_observed_not_replayable") || (route.method === "GET" && route.traffic !== "read_observed")) failures.push("mutation policy"); }
    const expectedSurface = REQUIRED.map(value => ({ ...value, status: "observed" as const })); if (JSON.stringify(dataset.requiredSurface) !== JSON.stringify(expectedSurface) || dataset.requiredSurface.some(required => !dataset.routes.some(value => value.method === required.method && value.route === required.route))) failures.push("required observed surface");
    const start = dataset.routes.find(value => value.method === "POST" && value.route === "/budokais/:budokai_id/tournaments"); if (!start || JSON.stringify(start.requestSchema.map(value => [value.path, value.types])) !== JSON.stringify([["$", ["object"]], ["$.sign", ["string"]]]) || JSON.stringify(start.responseSchema.map(value => [value.path, value.types])) !== JSON.stringify([["$", ["object"]], ["$.sign", ["string"]]])) failures.push("opaque start schema");
    return { schemaVersion: 1, valid: failures.length === 0, routeCount: dataset.routes.length, failures: [...new Set(failures)] };
}
