import * as assert from "assert";
import { createHash } from "crypto";
import { Wt3Dataset } from "./wt3-contract";
import { validateWt3 } from "./wt3-rankings";

const field = (path: string, classification: any) => ({ path, types: ["number" as const], typeOccurrences: [{ type: "number" as const, observedEntryIndexes: [1] }], classification, valueRetention: "omitted_schema_only" as const });
const surface = (route: string, fields: any[]) => { const reconstructed = fields.map(value => ({ path: value.path, types: value.types, observedEntryIndexes: [1], typeOccurrences: value.typeOccurrences })), classification = route.endsWith("/friends") ? "account_scoped" : route.includes("/box_rankings/") ? "partial" : "global"; return { route, classification, fields, sourceSchemaSha256: createHash("sha256").update(JSON.stringify(reconstructed)).digest("hex") }; };
function fixture(): Wt3Dataset {
    const general = surface("/budokais/:budokai_id/rankings", [field("$.current_page", "global"), field("$.per_page", "global"), field("$.total_page", "global"), field("$.updated_at", "global"), field("$.rankers", "account_scoped")]), borders = surface("/budokais/:budokai_id/rankings/borders", [field("$.my_ranking", "account_scoped"), field("$.updated_at", "global")]), friends = surface("/budokais/:budokai_id/rankings/friends", [field("$.rankers", "account_scoped")]), box = surface("/budokais/:budokai_id/box_rankings/:box_ranking_id", [field("$.ranking_status", "partial")]), schedules = surface("/bonus_schedules", [field("$.bonus_schedules", "global")]);
    return { schemaVersion: 1, contract: "dokkan-world-tournament-rankings-box-schedules", contractVersion: "0.4.0", lineage: [{ gate: "WT0", contractVersion: "0.1.0", sizeBytes: 1, sha256: "a".repeat(64) }, { gate: "WT1", contractVersion: "0.2.0", sizeBytes: 1, sha256: "b".repeat(64) }], generalRanking: { ...general, paginationPaths: ["$.current_page", "$.per_page", "$.total_page"], updatedAtPath: "$.updated_at" }, rankingBorders: { ...borders, myRankingPath: "$.my_ranking", updatedAtPath: "$.updated_at" }, rankingFriends: friends, boxRanking: { ...box, boxRankingIds: [71], statusSemantics: "partial" }, bonusSchedules: { ...schedules, scheduleIds: [5] }, rewards: { observedSchemaPaths: [], definitionsObserved: false, grantedOrClaimedObserved: false, boundary: "no_ranking_reward_definition_or_grant_response_observed" } } as Wt3Dataset;
}
describe("world tournament WT3", () => {
    it("validates sanitized ranking surfaces", () => assert.equal(validateWt3(fixture()).valid, true));
    it("rejects account rankers promoted global", () => { const dataset = fixture(); dataset.generalRanking.fields.at(-1)!.classification = "global"; assert.equal(validateWt3(dataset).valid, false); });
    it("rejects absent required metadata and forged occurrences", () => { const dataset = fixture(); dataset.generalRanking.fields = dataset.generalRanking.fields.filter(value => value.path !== "$.updated_at"); dataset.generalRanking.fields[0].typeOccurrences[0].observedEntryIndexes = []; assert.equal(validateWt3(dataset).valid, false); });
    it("rejects duplicate occurrence types and indexes", () => { const dataset = fixture(), target = dataset.generalRanking.fields[0]; target.types = ["number", "string"]; target.typeOccurrences = [{ type: "number", observedEntryIndexes: [1, 1] }, { type: "number", observedEntryIndexes: [1] }]; assert.equal(validateWt3(dataset).valid, false); });
    it("derives reward presence and rejects grant claims or missing IDs", () => { const dataset = fixture(); dataset.rewards.observedSchemaPaths = ["$.ranking_rewards"]; dataset.rewards.definitionsObserved = false; dataset.rewards.grantedOrClaimedObserved = true as false; dataset.boxRanking.boxRankingIds = []; assert.equal(validateWt3(dataset).valid, false); });
});
