import { equal, rejects, throws } from "assert";
import { createHash } from "crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";
import { describe, it } from "mocha";
import { buildWallpaperGameAssets, validatePinnedWallpaperToolchain, validateWallpaperAssetManifest, WallpaperAssetSourceIdentity } from "./game-db-wallpaper-assets";
import { GameDbRow } from "./game-db-source";

const png = Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), Buffer.from("fixture")]);
const sourceIdentity: WallpaperAssetSourceIdentity = {
    packageName: "com.bandainamcogames.dbzdokkanww",
    versionName: "6.5.5",
    versionCode: "348",
    databaseSnapshotVersion: "1788329250",
    databaseSha256: "7a6ca01808aea355ef28f9c0190e2c072f43a7c08be41d363f5b052824922495",
    acquiredAt: "2026-09-04T12:00:00.000Z",
    cpkReader: { repository: "https://github.com/Sewer56/CriFsV2Lib", commit: "169b001c748dfffc28c9fc14fcec269dd45e6eec" },
};
const row = (values: Record<string, string>): GameDbRow => values;

async function fixture(root: string, id: string, mode: "canonical" | "layered" | "canonical-plus-layer" = "canonical"): Promise<void> {
    const padded = id.padStart(4, "0");
    await mkdir(join(root, "archives"), { recursive: true });
    const extracted = join(root, "extracted", padded);
    await mkdir(extracted, { recursive: true });
    const textures = mode === "canonical"
        ? [`Images_${padded}.png`]
        : mode === "layered"
            ? ["Images_layer_01.png"]
            : [`Images_${padded}.png`, "Images_layer_01.png"];
    const archiveMembers = [`${padded}.lwf`, `icon_${padded}.png`, `thumb_${padded}.png`, ...textures];
    await writeFile(join(root, "archives", `${padded}.cpk`), Buffer.from(`CPK ${archiveMembers.join("\0")}`, "ascii"));
    await writeFile(join(extracted, `${padded}.lwf`), textures.join("\0"));
    await writeFile(join(extracted, `icon_${padded}.png`), png);
    await writeFile(join(extracted, `thumb_${padded}.png`), png);
    for (const texture of textures) await writeFile(join(extracted, texture), png);
}

async function fakeExtractor(root: string): Promise<{ path: string, sha256: string }> {
    const path = join(root, "fake-cpk-extractor.js");
    await writeFile(path, [
        'const { cpSync } = require("fs");',
        'const { basename, dirname, join } = require("path");',
        'const archive = process.argv[2];',
        'const output = process.argv[3];',
        'const id = basename(archive, ".cpk");',
        'cpSync(join(dirname(dirname(archive)), "extracted", id), output, { recursive: true, errorOnExist: true });',
    ].join("\n"));
    return { path, sha256: createHash("sha256").update(await readFile(path)).digest("hex") };
}

describe("official wallpaper assets", function () {
    it("mirrors canonical official presentation and records multi-texture fallback", async () => {
        const root = await mkdtemp(join(tmpdir(), "dokkan-wallpaper-"));
        try {
            const source = join(root, "source");
            await fixture(source, "76");
            await fixture(source, "87", "layered");
            await fixture(source, "58", "canonical-plus-layer");
            const extractor = await fakeExtractor(root);
            const output = join(root, "output");
            const manifest = await buildWallpaperGameAssets({
                generatedAt: "2026-09-04T12:00:00.000Z",
                sourceIdentity,
                sourceBundleRoot: source,
                outputRoot: output,
                wallpaperItems: [
                    row({ id: "76", name: "Companions on Planet Vampa", description: "Official description" }),
                    row({ id: "87", name: "Composite", description: "Official composite" }),
                    row({ id: "58", name: "Ambiguous canonical", description: "Official layered composition" }),
                ],
                cpkExtractorPath: extractor.path,
                testOnlyExpectedExtractorSha256: extractor.sha256,
            });
            equal(manifest.wallpaperCount, 3);
            equal(manifest.assetCount, 7);
            equal(manifest.fullImageCount, 1);
            equal(manifest.fullImageGaps.length, 2);
            equal(manifest.presentations.find(item => item.itemId === "58")?.fullImageAssetPath, undefined);
            equal(manifest.presentations.find(item => item.itemId === "76")?.fullImageAssetPath, "item/wallpaper/0076/full_0076.png");
            equal((await readFile(join(output, "game-assets", "item", "wallpaper", "0076", "full_0076.png"))).equals(png), true);
            validateWallpaperAssetManifest(manifest);
            throws(() => validatePinnedWallpaperToolchain(manifest), /not generated by the pinned CriFsV2Lib toolchain/);
            const duplicate = structuredClone(manifest);
            duplicate.presentations.push(structuredClone(duplicate.presentations[0]));
            throws(() => validateWallpaperAssetManifest(duplicate), /Duplicate wallpaper presentation/);
            const invalidInventory = structuredClone(manifest);
            invalidInventory.inventorySha256 = "0".repeat(64);
            throws(() => validateWallpaperAssetManifest(invalidInventory), /cardinality or inventory mismatch/);
            const invalidPath = structuredClone(manifest);
            invalidPath.presentations[0].thumbnailAssetPath = "item/wallpaper/0058/thumb_9999.png";
            throws(() => validateWallpaperAssetManifest(invalidPath), /invalid advertised assets/);
        } finally {
            await rm(root, { recursive: true, force: true });
        }
    });

    it("rejects archives that are not structurally CPK files", async () => {
        const root = await mkdtemp(join(tmpdir(), "dokkan-wallpaper-invalid-cpk-"));
        try {
            const source = join(root, "source");
            await fixture(source, "76");
            const extractor = await fakeExtractor(root);
            await writeFile(join(source, "archives", "0076.cpk"), "arbitrary bytes with member names");
            await rejects(buildWallpaperGameAssets({
                generatedAt: "2026-09-04T12:00:00.000Z",
                sourceIdentity,
                sourceBundleRoot: source,
                outputRoot: join(root, "output"),
                wallpaperItems: [row({ id: "76", name: "Name", description: "Description" })],
                cpkExtractorPath: extractor.path,
                testOnlyExpectedExtractorSha256: extractor.sha256,
            }), /Invalid official wallpaper CPK/);
        } finally {
            await rm(root, { recursive: true, force: true });
        }
    });

    it("fails closed when the canonical full image advertised to consumers is missing", async () => {
        const root = await mkdtemp(join(tmpdir(), "dokkan-wallpaper-missing-"));
        try {
            const source = join(root, "source");
            await fixture(source, "76");
            const extractor = await fakeExtractor(root);
            await rm(join(source, "extracted", "0076", "Images_0076.png"));
            await rejects(buildWallpaperGameAssets({
                generatedAt: "2026-09-04T12:00:00.000Z",
                sourceIdentity,
                sourceBundleRoot: source,
                outputRoot: join(root, "output"),
                wallpaperItems: [row({ id: "76", name: "Name", description: "Description" })],
                cpkExtractorPath: extractor.path,
                testOnlyExpectedExtractorSha256: extractor.sha256,
            }), /Missing extracted wallpaper CPK member/);
        } finally {
            await rm(root, { recursive: true, force: true });
        }
    });

    it("rejects an extractor outside the pinned production identity", async () => {
        const root = await mkdtemp(join(tmpdir(), "dokkan-wallpaper-unapproved-extractor-"));
        try {
            const source = join(root, "source");
            await fixture(source, "76");
            const extractor = await fakeExtractor(root);
            await rejects(buildWallpaperGameAssets({
                generatedAt: "2026-09-04T12:00:00.000Z",
                sourceIdentity,
                sourceBundleRoot: source,
                outputRoot: join(root, "output"),
                wallpaperItems: [row({ id: "76", name: "Name", description: "Description" })],
                cpkExtractorPath: extractor.path,
            }), /CPK extractor is not approved/);
        } finally {
            await rm(root, { recursive: true, force: true });
        }
    });
});
