export const CORE_GAME_DB_TABLES = [
    "active_skill_sets",
    "active_skills",
    "card_active_skills",
    "card_awakening_routes",
    "card_card_categories",
    "card_categories",
    "card_finish_skill_set_relations",
    "card_unique_info_set_relations",
    "card_unique_infos",
    "card_specials",
    "card_standby_skill_set_relations",
    "cards",
    "finish_skill_sets",
    "finish_skills",
    "leader_skill_sets",
    "leader_skills",
    "link_skills",
    "optimal_awakening_growths",
    "passive_skill_set_relations",
    "passive_skill_sets",
    "passive_skills",
    "skill_causalities",
    "special_sets",
    "standby_skill_set_finish_skill_set_relations",
    "standby_skills",
    "standby_skill_sets",
    "ultimate_specials",
] as const;

export const SUPER_ATTACK_EFFECT_GAME_DB_TABLES = [
    "specials",
] as const;

export const SUPER_ATTACK_CATEGORY_GAME_DB_TABLES = [
    "special_views",
    "special_categories",
] as const;

export const DOKKAN_FIELD_SIDECAR_TABLES = [
    "dokkan_fields",
    "dokkan_field_efficacy_sets",
    "dokkan_field_efficacies",
    "dokkan_field_active_skill_set_relations",
    "dokkan_field_passive_skill_relations",
] as const;

export const SUPPORT_MEMORY_GAME_DB_TABLES = [
    "mission_categories",
    "mission_rewards",
    "missions",
    "sub_target_type_sets",
    "sub_target_types",
    "support_films",
    "support_memories",
    "support_memory_enhancement_items",
    "support_memory_enhancement_levels",
    "support_memory_enhancement_require_items",
    "support_memory_skills",
] as const;

export const STAGE_GAME_DB_TABLES = [
    "areas",
    "chapters",
    "db_stories",
    "enemy_round_skill_set_relations",
    "enemy_round_skill_sets",
    "enemy_round_skills",
    "enemy_skills",
    "enemy_skill_cutin_extensions",
    "mission_category_rewards",
    "quest_category_bonus_rarity_tables",
    "quest_category_bonuses",
    "quest_category_bonus_groups",
    "quest_drop_item_views",
    "quests",
    "related_card_categories",
    "related_link_skills",
    "related_optimal_awakenings",
    "related_passive_skill_sets",
    "sugoroku_map_boss_drop_items",
    "sugoroku_map_enemy_informations",
    "sugoroku_map_puzzle_colors",
    "sugoroku_maps",
    "z_battle_check_points",
    "z_battle_enemies",
    "z_battle_enemy_card_escalations",
    "z_battle_enemy_skill_escalations",
    "z_battle_enemy_status_escalations",
    "z_battle_first_reward_level_ranges",
    "z_battle_first_rewards",
    "z_battle_normal_reward_tables",
    "z_battle_normal_rewards",
    "z_battle_powerup_thresholds",
    "z_battle_stage_views",
    "z_battle_stages",
] as const;

export const FIRST_PARTY_EXPORT_GAME_DB_TABLES = [
    ...CORE_GAME_DB_TABLES,
    ...SUPER_ATTACK_EFFECT_GAME_DB_TABLES,
    ...SUPER_ATTACK_CATEGORY_GAME_DB_TABLES,
    ...DOKKAN_FIELD_SIDECAR_TABLES,
    ...SUPPORT_MEMORY_GAME_DB_TABLES,
    ...STAGE_GAME_DB_TABLES,
] as const;
