import { createHash } from "crypto";
import { createReadStream, existsSync } from "fs";
import { open, mkdir, readFile, stat, writeFile } from "fs/promises";
import { resolve } from "path";
import { gunzipSync } from "zlib";
import { ReadOnlySqliteAdapter } from "../database-experiment/sqlite-readonly-adapter";
import { runIntegrationC1 } from "./integration-c1-run";
import { runIntegrationC2 } from "./integration-c2-run";
import { runIntegrationC3 } from "./integration-c3-run";
import { evaluateIntegrationC4Compatibility, integrationC4SchemaSha256 } from "./integration-c4-builder";
import { IntegrationC4Baseline, IntegrationC4CompatibilityReport, IntegrationC4Gate, IntegrationC4Manifest, IntegrationC4Observed, IntegrationC4Receipt, IntegrationC4ReceiptExpectation } from "./integration-c4-contract";
import { validateIntegrationC4Artifacts } from "./integration-c4-validator";

const DEFAULT_DATABASE = "D:/Dokkan/database/decrypted/dokkan-global-current.db", DEFAULT_ELF = "D:/Dokkan/database/apk/extracted/lib/arm64-v8a/libcocos2dcpp.so", DEFAULT_EXPERIMENT = resolve(process.cwd(), "data", "database-experiment"), DEFAULT_PRODUCTION = "D:/Dokkan/DokkanWebScraper/data/fyi-characters/latest", MEMORY_LIMIT = 1024 * 1024 * 1024;
const sha256 = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
let peakWorkingSetBytes = 0;
function observeMemory(): void { peakWorkingSetBytes = Math.max(peakWorkingSetBytes, process.memoryUsage().rss, process.resourceUsage().maxRSS * 1024); if (peakWorkingSetBytes > MEMORY_LIMIT) throw Error(`C4 memory limit exceeded: ${peakWorkingSetBytes}`); }
async function fingerprint(path: string) { const metadata = await stat(path), hash = createHash("sha256"); await new Promise<void>((done, reject) => { const stream = createReadStream(path); stream.on("data", chunk => { hash.update(chunk); observeMemory(); }); stream.on("error", reject); stream.on("end", done); }); return { sha256: hash.digest("hex"), sizeBytes: metadata.size, modifiedAtMs: metadata.mtimeMs }; }
function baselinePath(): string { const adjacent = resolve(__dirname, "integration-c4-baseline.json"); return existsSync(adjacent) ? adjacent : resolve(__dirname, "..", "..", "database-integration", "integration-c4-baseline.json"); }
async function elfFormat(path: string) { const handle = await open(path, "r"); try { const bytes = Buffer.alloc(20); await handle.read(bytes, 0, bytes.length, 0); return { elfClass: bytes.subarray(0, 4).toString("hex") === "7f454c46" && bytes[4] === 2 ? 64 : 0, endian: bytes[5] === 1 ? "little" : "unknown", machine: bytes.readUInt16LE(18) }; } finally { await handle.close(); } }
interface GateManifest { contractVersion: string; fileName: string; sha256: string; sizeBytes: number; uncompressedSizeBytes: number; sourceDatabaseSha256: string; nativeRuntimeSha256: string }
interface GatePayloadHeader { schemaVersion: number; contractVersion: string; sourceDatabaseSha256: string; nativeRuntime: { sha256: string } }
async function readSemanticInputs(inputDir: string): Promise<IntegrationC4Observed["semanticInputs"]> {
    const result = {} as IntegrationC4Observed["semanticInputs"];
    for (const gate of ["DB48", "DB49", "DB50"] as IntegrationC4Gate[]) {
        const manifest = JSON.parse(await readFile(resolve(inputDir, `team-analysis-${gate.toLowerCase()}-manifest.json`), "utf8")) as GateManifest, bytes = await readFile(resolve(inputDir, manifest.fileName));
        if (bytes.byteLength !== manifest.sizeBytes || sha256(bytes) !== manifest.sha256) throw Error(`C4 ${gate} artifact identity`);
        const json = gunzipSync(bytes); if (json.byteLength !== manifest.uncompressedSizeBytes) throw Error(`C4 ${gate} artifact uncompressed size`); const payload = JSON.parse(json.toString("utf8")) as GatePayloadHeader;
        if (payload.schemaVersion !== 1 || payload.contractVersion !== manifest.contractVersion || payload.sourceDatabaseSha256 !== manifest.sourceDatabaseSha256 || payload.nativeRuntime?.sha256 !== manifest.nativeRuntimeSha256) throw Error(`C4 ${gate} payload lineage`);
        result[gate] = { contractVersion: payload.contractVersion, sha256: manifest.sha256, sourceDatabaseSha256: payload.sourceDatabaseSha256, nativeRuntimeSha256: payload.nativeRuntime.sha256 };
    }
    return result;
}
async function observe(databasePath: string, nativeRuntimePath: string, inputDir: string): Promise<IntegrationC4Observed> {
    const [sourceDatabase, nativeRuntime, inspection, format, semanticInputs] = await Promise.all([fingerprint(databasePath), fingerprint(nativeRuntimePath), new ReadOnlySqliteAdapter(databasePath).inspect(), elfFormat(nativeRuntimePath), readSemanticInputs(inputDir)]); observeMemory();
    return { sourceDatabase: { ...sourceDatabase, tableCount: inspection.tableCount, schemaSha256: integrationC4SchemaSha256(inspection), inspection }, nativeRuntime: { ...nativeRuntime, ...format }, semanticInputs };
}
export async function runIntegrationC4(options: { databasePath?: string; nativeRuntimePath?: string; inputDir?: string; outputDir?: string; productionDir?: string; baselineFile?: string } = {}) {
    peakWorkingSetBytes = 0; const databasePath = options.databasePath ?? DEFAULT_DATABASE, nativeRuntimePath = options.nativeRuntimePath ?? DEFAULT_ELF, inputDir = options.inputDir ?? DEFAULT_EXPERIMENT, outputDir = options.outputDir ?? DEFAULT_EXPERIMENT, productionDir = options.productionDir ?? DEFAULT_PRODUCTION;
    const baseline = JSON.parse(await readFile(options.baselineFile ?? baselinePath(), "utf8")) as IntegrationC4Baseline; if (baseline.schemaVersion !== 1 || baseline.contractVersion !== "1.0.0") throw Error("C4 baseline contract");
    const before = await observe(databasePath, nativeRuntimePath, inputDir), expectedReport = evaluateIntegrationC4Compatibility(baseline, before), compatibilityText = `${JSON.stringify(expectedReport, null, 2)}\n`; await mkdir(outputDir, { recursive: true }); await writeFile(resolve(outputDir, "database-first-update-c4-compatibility.json"), compatibilityText);
    if (expectedReport.status === "incompatible") { const validation = validateIntegrationC4Artifacts(expectedReport, evaluateIntegrationC4Compatibility(baseline, before)); if (!validation.valid) throw Error("C4 incompatibility validation"); await writeFile(resolve(outputDir, "database-first-update-c4-validation.json"), `${JSON.stringify(validation, null, 2)}\n`); return { status: "incompatible" as const, compatibility: expectedReport, validation, peakWorkingSetBytes }; }
    const c1 = await runIntegrationC1({ inputDir, outputDir }); observeMemory(); const c2 = await runIntegrationC2({ inputDir: outputDir, outputDir }); observeMemory(); const c3 = await runIntegrationC3({ inputDir: outputDir, outputDir, productionDir }); observeMemory();
    const afterDatabase = await fingerprint(databasePath), afterNative = await fingerprint(nativeRuntimePath); if (JSON.stringify(afterDatabase) !== JSON.stringify({ sha256: before.sourceDatabase.sha256, sizeBytes: before.sourceDatabase.sizeBytes, modifiedAtMs: before.sourceDatabase.modifiedAtMs }) || JSON.stringify(afterNative) !== JSON.stringify({ sha256: before.nativeRuntime.sha256, sizeBytes: before.nativeRuntime.sizeBytes, modifiedAtMs: before.nativeRuntime.modifiedAtMs })) throw Error("C4 read-only source guarantee");
    const compatibilityReportSha256 = sha256(compatibilityText), receipt: IntegrationC4Receipt = { schemaVersion: 1, contract: "dokkan-database-first-focused-refresh", contractVersion: "1.0.0", generatedAt: c1.manifest.generatedAt, snapshotVersion: baseline.snapshotVersion, mode: "focused_c1_c2_c3_no_db0_db50_replay", compatibilityReportSha256, inputs: { sourceDatabaseSha256: before.sourceDatabase.sha256, nativeRuntimeSha256: before.nativeRuntime.sha256, schemaSha256: before.sourceDatabase.schemaSha256, semanticArtifacts: { DB48: before.semanticInputs.DB48.sha256, DB49: before.semanticInputs.DB49.sha256, DB50: before.semanticInputs.DB50.sha256 } }, outputs: { c1Sha256: c1.manifest.sha256, c2Sha256: c2.manifest.sha256, c3Sha256: c3.manifest.sha256 }, readOnlySourceGuarantee: true };
    const expectation: IntegrationC4ReceiptExpectation = { generatedAt: c1.manifest.generatedAt, snapshotVersion: baseline.snapshotVersion, compatibilityReportSha256, sourceDatabaseSha256: before.sourceDatabase.sha256, nativeRuntimeSha256: before.nativeRuntime.sha256, schemaSha256: before.sourceDatabase.schemaSha256, semanticArtifacts: { DB48: before.semanticInputs.DB48.sha256, DB49: before.semanticInputs.DB49.sha256, DB50: before.semanticInputs.DB50.sha256 }, c1Sha256: c1.manifest.sha256, c2Sha256: c2.manifest.sha256, c3Sha256: c3.manifest.sha256 };
    const validation = validateIntegrationC4Artifacts(expectedReport, evaluateIntegrationC4Compatibility(baseline, before), receipt, expectation), reportMutation = JSON.parse(JSON.stringify(expectedReport)) as IntegrationC4CompatibilityReport, inputMutation = JSON.parse(JSON.stringify(receipt)) as IntegrationC4Receipt, outputMutation = JSON.parse(JSON.stringify(receipt)) as IntegrationC4Receipt, snapshotMutation = JSON.parse(JSON.stringify(receipt)) as IntegrationC4Receipt; reportMutation.status = "incompatible"; inputMutation.inputs.sourceDatabaseSha256 = "0".repeat(64); outputMutation.outputs.c3Sha256 = "0".repeat(64); snapshotMutation.snapshotVersion = "changed"; validation.mutationRejectionCount = [reportMutation, inputMutation, outputMutation, snapshotMutation].filter((value, index) => index === 0 ? !validateIntegrationC4Artifacts(value as IntegrationC4CompatibilityReport, expectedReport, receipt, expectation).valid : !validateIntegrationC4Artifacts(expectedReport, expectedReport, value as IntegrationC4Receipt, expectation).valid).length; if (!validation.valid || validation.mutationRejectionCount !== 4) throw Error(`C4 validation ${JSON.stringify(validation.failures)}`);
    const receiptText = `${JSON.stringify(receipt, null, 2)}\n`; const manifest: IntegrationC4Manifest = { schemaVersion: 1, contractVersion: "1.0.0", generatedAt: receipt.generatedAt, fileName: "database-first-update-c4-receipt.json", sha256: sha256(receiptText), sizeBytes: Buffer.byteLength(receiptText), compatibilityFile: "database-first-update-c4-compatibility.json" };
    await Promise.all([writeFile(resolve(outputDir, manifest.fileName), receiptText), writeFile(resolve(outputDir, "database-first-update-c4-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`), writeFile(resolve(outputDir, "database-first-update-c4-validation.json"), `${JSON.stringify(validation, null, 2)}\n`)]); observeMemory();
    return { status: "compatible" as const, manifest, compatibility: expectedReport, validation, outputs: receipt.outputs, peakWorkingSetBytes };
}
if (require.main === module) runIntegrationC4().then(value => console.log(JSON.stringify(value, null, 2))).catch(error => { console.error(error); process.exitCode = 1; });
