import { createHash } from "crypto";
import { createReadStream, existsSync } from "fs";
import { mkdir, readFile, stat, writeFile } from "fs/promises";
import { resolve } from "path";
import { resolveEventsInputFile, resolveEventsOutputFiles } from "./events-artifact-path";
import { EventsE0Baseline } from "./events-e0-contract";
import { EventsE2Coverage, EventsE2Dataset, EventsE2Manifest, EventsE2Validation } from "./events-e2-contract";
import { buildEventsE3Coverage, buildEventsE3Dataset, buildEventsE3Goldens } from "./events-e3-builder";
import { EventsE3Baseline, EventsE3Manifest, EventsE3Observation } from "./events-e3-contract";
import { validateEventsE3Dataset } from "./events-e3-validator";
import { runEventsSqliteBridge } from "./events-sqlite-adapter";

const DEFAULT_DATABASE = "D:/Dokkan/database/decrypted/dokkan-global-current.db", DEFAULT_OUTPUT = resolve(process.cwd(), "data", "database-events"), MEMORY_LIMIT = 1024 * 1024 * 1024;
let peakWorkingSetBytes = 0;
function memory() { peakWorkingSetBytes = Math.max(peakWorkingSetBytes, process.memoryUsage().rss, process.resourceUsage().maxRSS * 1024); if (peakWorkingSetBytes > MEMORY_LIMIT) throw Error(`E3 memory limit exceeded ${peakWorkingSetBytes}`); }
const sha = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
async function fingerprint(path: string) { const metadata = await stat(path), hash = createHash("sha256"); await new Promise<void>((done, reject) => { const stream = createReadStream(path); stream.on("data", chunk => { hash.update(chunk); memory(); }); stream.on("error", reject); stream.on("end", done); }); return { sha256: hash.digest("hex"), sizeBytes: metadata.size, modifiedAtMs: metadata.mtimeMs }; }
function sourcePath(name: string) { const adjacent = resolve(__dirname, name); return existsSync(adjacent) ? adjacent : resolve(__dirname, "..", "..", "database-events", name); }

export async function runEventsE3(options: { databasePath?: string; outputDir?: string; e2Dir?: string; baselinePath?: string; e3BaselinePath?: string } = {}) {
    peakWorkingSetBytes = 0;
    const databasePath = resolve(options.databasePath ?? DEFAULT_DATABASE), outputDir = resolve(options.outputDir ?? DEFAULT_OUTPUT), e2Dir = resolve(options.e2Dir ?? DEFAULT_OUTPUT);
    const baseline = JSON.parse(await readFile(options.baselinePath ? resolve(options.baselinePath) : sourcePath("events-e0-baseline.json"), "utf8")) as EventsE0Baseline, e3Baseline = JSON.parse(await readFile(options.e3BaselinePath ? resolve(options.e3BaselinePath) : sourcePath("events-e3-baseline.json"), "utf8")) as EventsE3Baseline, e2Manifest = JSON.parse(await readFile(await resolveEventsInputFile(e2Dir, "events-e2-manifest.json", "events-e2-manifest.json"), "utf8")) as EventsE2Manifest;
    const [e2Path, coveragePath, validationPath] = await Promise.all([resolveEventsInputFile(e2Dir, e2Manifest.fileName, "events-e2-topology.json"), resolveEventsInputFile(e2Dir, e2Manifest.coverage?.fileName, "events-e2-coverage.json"), resolveEventsInputFile(e2Dir, e2Manifest.validation?.fileName, "events-e2-validation.json")]);
    const [e2Bytes, coverageBytes, validationBytes] = await Promise.all([readFile(e2Path), readFile(coveragePath), readFile(validationPath)]); memory();
    const e2 = JSON.parse(e2Bytes.toString("utf8")) as EventsE2Dataset, e2Coverage = JSON.parse(coverageBytes.toString("utf8")) as EventsE2Coverage, e2Validation = JSON.parse(validationBytes.toString("utf8")) as EventsE2Validation;
    if (e3Baseline.snapshotVersion !== baseline.snapshotVersion || e3Baseline.sourceE2Sha256 !== e2Manifest.sha256 || e2Manifest.contractVersion !== "0.3.0" || e2Manifest.generatedAtPolicy !== "pinned_to_source_snapshot_for_reproducible_bytes" || e2Manifest.generatedAt !== baseline.generatedAt || e2Manifest.sourceSnapshotVersion !== baseline.snapshotVersion || e2Manifest.sourceDatabaseSha256 !== baseline.sourceDatabase.sha256 || e2Bytes.byteLength !== e2Manifest.sizeBytes || sha(e2Bytes) !== e2Manifest.sha256 || coverageBytes.byteLength !== e2Manifest.coverage.sizeBytes || sha(coverageBytes) !== e2Manifest.coverage.sha256 || validationBytes.byteLength !== e2Manifest.validation.sizeBytes || sha(validationBytes) !== e2Manifest.validation.sha256 || e2.contract !== "dokkan-events-database-first-topology" || e2.contractVersion !== "0.3.0" || e2.generatedAt !== baseline.generatedAt || e2.generatedAtPolicy !== "pinned_to_source_snapshot_for_reproducible_bytes" || e2.sourceSnapshotVersion !== baseline.snapshotVersion || e2.sourceDatabaseSha256 !== baseline.sourceDatabase.sha256 || e2Coverage.danglingIdCount !== 0 || !e2Validation.valid || !e2Validation.exactProjection) throw Error("E3 E2 lineage");
    const before = await fingerprint(databasePath); if (before.sha256 !== baseline.sourceDatabase.sha256 || before.sizeBytes !== baseline.sourceDatabase.sizeBytes) throw Error("E3 pinned database identity");
    const observation = await runEventsSqliteBridge<EventsE3Observation>("encounters", databasePath, memory); memory();
    const dataset = buildEventsE3Dataset({ observation, generatedAt: baseline.generatedAt, sourceSnapshotVersion: baseline.snapshotVersion, sourceDatabaseSha256: before.sha256, sourceE2Sha256: e2Manifest.sha256 }), coverage = buildEventsE3Coverage(dataset, e2), goldens = buildEventsE3Goldens(dataset), validation = validateEventsE3Dataset(dataset, observation, e2, goldens, e3Baseline.goldens, { generatedAt: baseline.generatedAt, sourceSnapshotVersion: baseline.snapshotVersion, sourceDatabaseSha256: before.sha256, sourceE2Sha256: e2Manifest.sha256 });
    if (!validation.valid || coverage.danglingIdCount !== 0) throw Error(`E3 validation ${JSON.stringify(validation.failures)} dangling=${coverage.danglingIdCount}`);
    const after = await fingerprint(databasePath); if (JSON.stringify(before) !== JSON.stringify(after)) throw Error("E3 read-only source guarantee");
    const payloadText = `${JSON.stringify(dataset, null, 2)}\n`, coverageText = `${JSON.stringify(coverage, null, 2)}\n`, validationText = `${JSON.stringify(validation, null, 2)}\n`, goldensText = `${JSON.stringify(goldens, null, 2)}\n`;
    const manifest: EventsE3Manifest = { schemaVersion: 1, contractVersion: "0.4.0", generatedAt: dataset.generatedAt, generatedAtPolicy: dataset.generatedAtPolicy, sourceSnapshotVersion: dataset.sourceSnapshotVersion, fileName: "events-e3-encounters.json", compression: "none", sha256: sha(payloadText), sizeBytes: Buffer.byteLength(payloadText), sourceDatabaseSha256: dataset.sourceDatabaseSha256, sourceE2Sha256: dataset.sourceE2.sha256, coverage: { fileName: "events-e3-coverage.json", sha256: sha(coverageText), sizeBytes: Buffer.byteLength(coverageText) }, validation: { fileName: "events-e3-validation.json", sha256: sha(validationText), sizeBytes: Buffer.byteLength(validationText) }, goldens: { fileName: "events-e3-goldens.json", sha256: sha(goldensText), sizeBytes: Buffer.byteLength(goldensText) } };
    await mkdir(outputDir, { recursive: true }); const outputs = await resolveEventsOutputFiles(outputDir, [manifest.fileName, manifest.coverage.fileName, manifest.validation.fileName, manifest.goldens.fileName, "events-e3-manifest.json"]); await Promise.all([writeFile(outputs.get(manifest.fileName)!, payloadText), writeFile(outputs.get(manifest.coverage.fileName)!, coverageText), writeFile(outputs.get(manifest.validation.fileName)!, validationText), writeFile(outputs.get(manifest.goldens.fileName)!, goldensText), writeFile(outputs.get("events-e3-manifest.json")!, `${JSON.stringify(manifest, null, 2)}\n`)]); memory();
    return { dataset, coverage, validation, goldens, manifest, peakWorkingSetBytes };
}

if (require.main === module) runEventsE3().then(value => console.log(JSON.stringify({ coverage: value.coverage, validation: value.validation, goldens: value.goldens.representatives.map(item => ({ kind: item.kind, sourceId: item.sourceId })), manifest: value.manifest, peakWorkingSetBytes: value.peakWorkingSetBytes }, null, 2))).catch(error => { console.error(error); process.exitCode = 1; });
