import { EventsE7Coverage, EventsE7Dataset } from "./events-e7-contract";
import { EventsE8Coverage, EventsE8Registry } from "./events-e8-contract";
import { EventsE9Coverage, EventsE9Dataset, EventsE9RefreshEvidence } from "./events-e9-contract";

export function buildEventsE9Dataset(options: { e7: EventsE7Dataset; e7Coverage: EventsE7Coverage; e7Sha256: string; e8: EventsE8Registry; e8Coverage: EventsE8Coverage; e8Sha256: string; refreshEvidence: EventsE9RefreshEvidence; refreshEvidenceSha256: string }): EventsE9Dataset {
    const { e7, e7Coverage, e8, e8Coverage } = options, mechanics = e8Coverage.sourceCoverage.boss_mechanics as Record<string, number>, assets = e8Coverage.sourceCoverage.asset_references as Record<string, number>, rewards = e8Coverage.sourceCoverage.rewards as Record<string, number>;
    return {
        schemaVersion: 1, contract: "dokkan-events-database-first-readiness", contractVersion: "1.0.0", generatedAt: e8.generatedAt, generatedAtPolicy: "pinned_to_source_snapshot_for_reproducible_bytes", sourceSnapshotVersion: e8.sourceSnapshotVersion, sourceDatabaseSha256: e8.sourceDatabaseSha256, sourceE7: { contractVersion: "0.8.0", sha256: options.e7Sha256 }, sourceE8: { contractVersion: "0.9.0", sha256: options.e8Sha256, refreshProfileSha256: e8.refreshProfile.sha256 }, sourceRefreshEvidence: { sha256: options.refreshEvidenceSha256 },
        evidence: {
            sidecarCount: e8Coverage.sidecarCount, totalSidecarPayloadBytes: e8Coverage.totalPayloadBytes, parityByClassification: e7Coverage.byClassification, confirmedConflictCount: e7Coverage.confirmedConflictCount, paginationByStatus: e7Coverage.paginationByStatus,
            mechanics: { supported: mechanics.requestedSupportedCount, partial: mechanics.requestedPartialCount, unknown: mechanics.requestedUnknownCount },
            assets: { pathReferences: assets.pathAssetCount, numericReferences: assets.numericAssetCount, bindings: assets.bindingCount, directBaseApkPaths: assets.directBaseApkPathCount, absentBaseApkPaths: assets.absentBaseApkPathCount, endpointStatus: "unknown" },
            rewards: { supportedItemReferences: rewards.supportedItemReferenceCount, unknownItemReferences: rewards.unknownItemReferenceCount },
            focusedRefresh: { comparedArtifactCount: options.refreshEvidence.comparedArtifactCount, observedMaxPeakWorkingSetBytes: options.refreshEvidence.observedMaxPeakWorkingSetBytes, memoryLimitBytes: options.refreshEvidence.memoryLimitBytes, byteIdentical: options.refreshEvidence.fullRefreshByteIdentical },
        },
        decisions: [
            { id: "merge_disabled_infrastructure", status: "GO", rationale: ["optional_additive_contracts", "fail_closed_lineage_and_validation", "no_default_generation_or_production_mutation"], exitConditions: [] },
            { id: "pinned_optional_generation", status: "GO", rationale: ["focused_refresh_reproduced_all_artifacts", "profile_pins_database_elf_apk_and_semantic_baselines", "peak_memory_below_one_gibibyte"], exitConditions: ["use_an_explicit_compatible_refresh_profile_for_each_new_snapshot"] },
            { id: "replace_scraped_datasets", status: "NO_GO", rationale: ["remote_pagination_completeness_not_proved", "server_availability_absent", "reward_rows_and_sdbattle_roots_unjoinable"], exitConditions: ["prove_remote_source_total_coverage_or_first_party_server_schedule", "resolve_required_unjoinable_surfaces", "run_consumer_migration_parity"] },
            { id: "publish_r2", status: "NO_GO", rationale: ["not_authorized_in_this_campaign", "no_publisher_dry_run_or_stable_object_key_plan"], exitConditions: ["explicit_publication_authorization", "publisher_dry_run_with_projected_bytes_and_cache_policy"] },
            { id: "android_shadow_consumption", status: "NO_GO", rationale: ["android_out_of_scope_and_unchanged", "cache_backward_compatibility_not_integration_tested"], exitConditions: ["explicit_android_scope", "optional_missing_old_cache_compatibility_tests"] },
            { id: "event_stage_screens", status: "NO_GO", rationale: ["server_current_availability_unknown", "presentation_locale_and_asset_delivery_partial", "ui_not_implemented"], exitConditions: ["product_screen_contract", "availability_source", "asset_delivery_resolution", "android_or_web_ui_scope"] },
            { id: "beneficial_character_calculation", status: "NO_GO", rationale: ["requested_mechanics_have_zero_supported_runtime_semantics", "beneficial_logic_intentionally_not_derived"], exitConditions: ["prove_required_mechanic_consumers_and_formulas", "define_product_algorithm_using_structural_categories_and_links"] },
            { id: "boss_damage_simulation", status: "NO_GO", rationale: ["enemy_runtime_stats_and_scaling_not_fully_proved", "damage_guard_type_and_ai_semantics_incomplete", "full_combat_calculator_out_of_scope"], exitConditions: ["prove_runtime_units_scaling_precedence_and_mechanics", "separate_combat_contract_and_validation_campaign"] },
        ],
        remainingBoundaries: [
            { key: "current_event_availability", status: "unknown", nextAuthority: "server_api" }, { key: "remote_legacy_pagination_totals", status: "partial", nextAuthority: "legacy_source_contract" }, { key: "sdbattle_event_root", status: "unjoinable", nextAuthority: "server_api" }, { key: "event_reward_row_identity", status: "unjoinable", nextAuthority: "server_api" }, { key: "enemy_runtime_stats_and_formulas", status: "partial", nextAuthority: "runtime_consumer_proof" }, { key: "requested_boss_mechanics", status: "partial", nextAuthority: "runtime_consumer_proof" }, { key: "event_asset_delivery", status: "unknown", nextAuthority: "download_manifest_or_endpoint" }, { key: "android_shadow_contract", status: "unknown", nextAuthority: "android_integration" }, { key: "event_screen_and_beneficial_product_rules", status: "unknown", nextAuthority: "product_decision" },
        ],
        checkpoint: { gatesComplete: ["E0", "E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9"], stopReason: "E0_E9_COMPLETE", productionChanged: false, androidChanged: false, r2Published: false },
    };
}

export function buildEventsE9Coverage(dataset: EventsE9Dataset): EventsE9Coverage { return { schemaVersion: 1, decisionCount: dataset.decisions.length, goCount: dataset.decisions.filter(value => value.status === "GO").length, noGoCount: dataset.decisions.filter(value => value.status === "NO_GO").length, remainingBoundaryCount: dataset.remainingBoundaries.length, sourceConflictCount: dataset.evidence.confirmedConflictCount, sourceSidecarCount: dataset.evidence.sidecarCount, sourceSidecarBytes: dataset.evidence.totalSidecarPayloadBytes }; }
