import { equal } from "assert";
import { EventsE1Dataset } from "./events-e1-contract";
import { EventsE2Dataset } from "./events-e2-contract";
import { buildEventsE5Coverage, buildEventsE5Dataset } from "./events-e5-builder";
import { EventsE5Observation } from "./events-e5-contract";
import { validateEventsE5Dataset } from "./events-e5-validator";

const e1 = { catalog: [{ identity: { kind: "area", id: "1" } }, { identity: { kind: "z_battle_stage", id: "3" } }, { identity: { kind: "origin_episode", id: "4" } }, { identity: { kind: "budokai", id: "5" } }], opaqueRootFamilies: [{ identities: ["6"] }] } as unknown as EventsE1Dataset;
const e2 = { questStages: [{ identity: { id: "2" }, levels: [{ identity: { id: "20" }, costs: { act: 10, eventKeyCount: 1 } }] }, { identity: { id: "21" }, levels: [{ identity: { id: "22" }, costs: { act: 11, eventKeyCount: 0 } }] }], zBattleTopologies: [{ identity: { stageId: "3" }, checkpoints: [{ sourceRowId: "30", level: 1, act: 0, eventKeyCount: 0 }] }], originBattles: [{ identity: { id: "40" }, costsAndOutcomes: { act: 5 } }], areaRequirements: [{ sourceRowId: "50" }] } as unknown as EventsE2Dataset;
const reward = (id: number, parent: string, parentId: number) => ({ id, [parent]: parentId, item_id: 100, item_type: "Card", quantity: 1, card_exp_init: 0 });
const observation: EventsE5Observation = {
    bossDrops: [{ id: 1, sugoroku_map_id: 20, quest_id: 2, drop_type: 9, item_id: 100, item_type: "Card", card_exp_init: 0 }], questDropPreviews: [{ id: 2, quest_id: 2, difficulties: "[3]", item1_id: null, item1_type: null, item2_id: null, item2_type: null, item3_id: null, item3_type: null, item4_id: 100, item4_type: "Card", item5_id: null, item5_type: null, item6_id: null, item6_type: null }],
    zFirstRewardRanges: [{ id: 3, z_battle_stage_id: 3, level: 1, z_battle_first_reward_set_id: 7, main_reward_id: null }], zFirstRewards: [reward(4, "z_battle_first_reward_set_id", 7)], zNormalRewardTables: [{ id: 8, z_battle_normal_reward_table_group_id: 9 }], zNormalRewards: [reward(5, "z_battle_normal_reward_table_id", 8)], zRewardCheckpoints: [{ id: 30, z_battle_stage_id: 3, level: 1, z_battle_normal_reward_table_group_id: 9, main_reward_id: null }],
    linkedMissions: [{ id: 10, type: "raw", mission_category_id: 11, target_value: 1, display_target_value: 1, target_100_value: null, conditions: "{}", link_to: null, area_id: 1, z_battle_stage_id: null, origin_episode_id: null, origin_battle_id: null, start_at: null, end_at: null, end_at_hidden: null }], linkedMissionRewards: [reward(6, "mission_id", 10)], linkedMissionCategoryPreviews: [],
    budokaiMissions: [{ id: 12, budokai_id: 5, mission_type: "raw", target_value: 1 }], budokaiMissionRewards: [reward(7, "budokai_mission_id", 12)], budokaiRankingGiftSets: [{ id: 13, budokai_id: 5, order: 1, ranking: "raw" }], budokaiRankingGifts: [reward(8, "budokai_ranking_gift_set_id", 13)], budokaiBoxRankings: [{ id: 14, budokai_id: 5, prev_budokai_id: null, prev_budokai_box_ranking_id: null, player_max_count: 1, box_max_count: 1, start_at: "a", end_at: "b", collecting_end_at: "c" }], budokaiBoxRewardRanges: [{ id: 15, budokai_box_ranking_id: 14, start_value: 1, end_value: 2 }], budokaiBoxRewards: [reward(9, "budokai_box_ranking_reward_range_id", 15)],
    rmbattleMissions: [{ id: 16, rmbattle_id: 6, type: "raw", target_value: 1, conditions: null }], rmbattleMissionRewards: [reward(10, "rmbattle_mission_id", 16)], opaqueRewardBindings: { questMapRewardGroups: [{ id: 20, quest_id: 2, sugoroku_map_reward_group_id: null }], originBattleRewardSets: [{ id: 40, origin_battle_reward_set_id: null }] }, unboundRewardSurfaces: [{ table: "dot_character_lv_rewards", rowCount: 1, consumerStatus: "unknown" }], itemCatalogTargets: [{ rawItemType: "Card", targetKind: "card", targetTable: "cards", referencedIds: [100], joinedIds: [100] }],
};
const build = () => buildEventsE5Dataset({ observation, e2, e1, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE4Sha256: "e4", sourceE2Sha256: "e2", sourceE1Sha256: "e1" });

describe("events E5 rewards", () => {
    it("keeps quantities separate from unknown chance and repeatability", () => { const dataset = build(); equal(dataset.zBattleFirstRewardSets[0].rewards[0].value.quantity, 1); equal(dataset.zBattleFirstRewardSets[0].rewards[0].value.chance.status, "unknown"); equal(dataset.questBossDrops[0].reward.quantity, null); equal(validateEventsE5Dataset(dataset, observation, e2, e1).valid, true); });
    it("joins item catalogs by raw type and numeric id", () => { const dataset = build(); equal(dataset.questBossDrops[0].reward.item.catalogJoin.status, "supported"); equal(buildEventsE5Coverage(dataset, e2, e1, observation).danglingIdCount, 0); });
    it("preserves preview slots and validates the map to quest pair", () => { const dataset = build(); equal(dataset.questDropPreviews[0].items[0].slot, 4); dataset.questBossDrops[0].questId = "21"; equal(buildEventsE5Coverage(dataset, e2, e1, observation).danglingIdCount, 1); });
    it("compares catalog ID sets instead of only their sizes", () => { const inconsistent = { ...observation, itemCatalogTargets: [{ ...observation.itemCatalogTargets[0], joinedIds: [999] }] }; const dataset = buildEventsE5Dataset({ observation: inconsistent, e2, e1, generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", sourceE4Sha256: "e4", sourceE2Sha256: "e2", sourceE1Sha256: "e1" }); equal(dataset.itemCatalogBindings[0].status, "unknown"); equal(buildEventsE5Coverage(dataset, e2, e1, inconsistent).danglingIdCount, 2); });
    it("rejects a dangling structural stage", () => { const dataset = build(); dataset.zBattleFirstRewardAnchors[0].stageId = "999"; equal(buildEventsE5Coverage(dataset, e2, e1, observation).danglingIdCount, 1); equal(validateEventsE5Dataset(dataset, observation, e2, e1).valid, false); });
});
