import { EventsE2Coverage, EventsE2Dataset, EventsE2Observation, EventsE2QuestLevel, EventsE2SdMapTopology } from "./events-e2-contract";
import { EventsE1Dataset } from "./events-e1-contract";

const num = (row: Record<string, unknown>, key: string) => Number(row[key]);
const nullableNum = (row: Record<string, unknown>, key: string) => row[key] === null ? null : Number(row[key]);
const str = (row: Record<string, unknown>, key: string) => String(row[key]);
const nullableId = (value: unknown) => value === null ? null : String(value);
function level(row: Record<string, unknown>, questId: string | null): EventsE2QuestLevel { const mapId = str(row, "id"); return { identity: { kind: "quest_level", id: mapId }, source: { table: "sugoroku_maps", rowId: mapId }, deepLinkKey: questId === null ? `unbound-map:${mapId}` : `quest:${questId}/map:${mapId}`, rawDifficulty: num(row, "difficulty"), costs: { act: num(row, "act"), eventKeyCount: num(row, "eventkagi_num") }, outcomes: { rankExp: num(row, "user_exp"), zeni: num(row, "zeni"), rewardGroupId: nullableId(row.sugoroku_map_reward_group_id) }, rawAttributes: { cpuOnly: num(row, "is_cpu_only") !== 0, linkSkillLevelUpProbabilityRate: num(row, "link_skill_lv_up_prob_rate"), cpuFriendListId: nullableId(row.cpu_friend_list_id) } }; }

export function buildEventsE2Dataset(options: { observation: EventsE2Observation; generatedAt: string; sourceSnapshotVersion: string; sourceDatabaseSha256: string; sourceE1Sha256: string; budokaiRootCount: number; rmbattleRootCount: number }): EventsE2Dataset {
    const o = options.observation, maps = new Map<string, EventsE2QuestLevel[]>(), unboundQuestLevels: EventsE2Dataset["unboundQuestLevels"] = [];
    for (const row of o.maps) { const questId = nullableId(row.quest_id), value = level(row, questId); if (questId === null) unboundQuestLevels.push({ ...value, status: "unknown", missing: ["quest_id"] }); else maps.set(questId, [...(maps.get(questId) ?? []), value]); }
    const questStages = o.quests.map(row => { const questId = str(row, "id"); return { identity: { kind: "quest_stage" as const, id: questId }, source: { table: "quests" as const, rowId: questId }, areaId: str(row, "area_id"), deepLinkKey: `area:${str(row, "area_id")}/quest:${questId}`, title: { value: str(row, "name"), locale: "snapshot_embedded_unverified" as const }, previousStageId: nullableId(row.prev_quest_id), clearBonusStones: { anyDifficulty: nullableNum(row, "any_clear_bonus_stones"), allDifficulties: nullableNum(row, "all_clear_bonus_stones") }, attempts: { maxVisits: nullableNum(row, "visit_count_max"), resetIntervalDays: nullableNum(row, "interval_reset_visited_days") }, rules: { canIgnoreDifficultyOrder: num(row, "can_ignore_difficulty_order") !== 0, limitationAnnouncementId: nullableId(row.limitation_announcement_id), boostable: num(row, "boostable") !== 0, sugorokuAuto: num(row, "enable_sugoroku_auto") !== 0, battleAuto: num(row, "enable_battle_auto") !== 0, enemyInfoDisplayTypeRaw: str(row, "enemy_info_display_type") }, availabilityHint: { startAt: row.start_at === null ? null : str(row, "start_at"), boundary: "database_embedded_schedule_hint_not_server_current_availability" as const }, levels: (maps.get(questId) ?? []).sort((a, b) => Number(a.identity.id) - Number(b.identity.id)) }; }).sort((a, b) => Number(a.identity.id) - Number(b.identity.id));
    const byStage = <T extends Record<string, unknown>>(rows: T[]) => { const result = new Map<string, T[]>(); for (const row of rows) { const key = str(row, "z_battle_stage_id"); result.set(key, [...(result.get(key) ?? []), row]); } return result; }, ranges = byStage(o.zBattleEnemyRanges), checkpoints = byStage(o.zBattleCheckPoints), anchors = byStage(o.zBattleRewardLevelAnchors);
    const zBattleTopologies = o.zBattleStages.map(row => { const stageId = str(row, "id"); return { identity: { kind: "z_battle_topology" as const, stageId }, deepLinkPrefix: `z-battle:${stageId}/level:`, unlockConditions: { status: "partial" as const, rawJson: str(row, "unlock_conditions") }, enemyRanges: (ranges.get(stageId) ?? []).map(value => ({ sourceRowId: str(value, "id"), ordinal: num(value, "ordinal_num"), startLevel: num(value, "start_level"), endLevel: nullableNum(value, "end_level") })), checkpoints: (checkpoints.get(stageId) ?? []).map(value => ({ sourceRowId: str(value, "id"), level: num(value, "level"), act: num(value, "act"), eventKeyCount: num(value, "eventkagi_num") })), rewardLevelAnchors: (anchors.get(stageId) ?? []).map(value => ({ sourceRowId: str(value, "id"), level: num(value, "level") })) }; }).sort((a, b) => Number(a.identity.stageId) - Number(b.identity.stageId));
    const originBattles = o.originBattles.map(row => { const battleId = str(row, "id"); return { identity: { kind: "origin_battle" as const, id: battleId }, source: { table: "origin_battles" as const, rowId: battleId }, status: "partial" as const, originSpotIdRaw: str(row, "origin_spot_id"), deepLinkKey: `origin-battle:${battleId}`, costsAndOutcomes: { act: num(row, "act"), rankExp: num(row, "user_exp"), zeni: num(row, "zeni"), firstClearBonusStones: num(row, "first_clear_bonus_stones"), linkSkillLevelUpProbabilityRate: num(row, "link_skill_lv_up_prob_rate") }, rules: { battleAuto: num(row, "enable_battle_auto") !== 0, unlockMissionIdsRaw: row.unlock_mission_ids === null ? null : str(row, "unlock_mission_ids"), limitationAnnouncementId: nullableId(row.limitation_announcement_id) }, missing: ["origin_spot_root_table", "catalog_page_join"] as ["origin_spot_root_table", "catalog_page_join"] }; }).sort((a, b) => Number(a.identity.id) - Number(b.identity.id));
    const arenas = new Map<string, EventsE2SdMapTopology["arenas"]>(); for (const row of o.sdArenas) { const mapId = str(row, "sd_map_id"), arenaId = str(row, "id"); arenas.set(mapId, [...(arenas.get(mapId) ?? []), { identity: { arenaId }, sourceRowId: arenaId, position: { x: num(row, "position_x"), y: num(row, "position_y") }, symbolItem: { rawType: str(row, "symbol_item_type"), itemId: str(row, "symbol_item_id") }, stages: [] }]); }
    const arenaById = new Map<string, EventsE2SdMapTopology["arenas"][number]>(); for (const values of arenas.values()) for (const arena of values) arenaById.set(arena.identity.arenaId, arena); for (const row of o.sdStages) { const stageId = str(row, "id"), arenaId = str(row, "sd_arena_id"), arena = arenaById.get(arenaId); if (arena) arena.stages.push({ identity: { stageId }, sourceRowId: stageId, deepLinkKey: `sd-arena:${arenaId}/stage:${stageId}`, enemyTableIdRaw: str(row, "sd_enemy_table_id"), respawnMinutes: num(row, "respawn_minutes"), position: { x: num(row, "position_x"), y: num(row, "position_y") } }); }
    const sdTopologies = o.sdMaps.map(row => { const mapId = str(row, "id"), values = arenas.get(mapId) ?? []; for (const arena of values) arena.stages.sort((a, b) => Number(a.identity.stageId) - Number(b.identity.stageId)); return { identity: { kind: "sd_map_topology" as const, mapId }, status: "partial" as const, deepLinkPrefix: `sd-map:${mapId}/arena:`, arenas: values.sort((a, b) => Number(a.identity.arenaId) - Number(b.identity.arenaId)), missing: ["sd_product_family_label", "sd_enemy_table_target"] as ["sd_product_family_label", "sd_enemy_table_target"] }; }).sort((a, b) => Number(a.identity.mapId) - Number(b.identity.mapId));
    return { schemaVersion: 1, contract: "dokkan-events-database-first-topology", contractVersion: "0.3.0", generatedAt: options.generatedAt, generatedAtPolicy: "pinned_to_source_snapshot_for_reproducible_bytes", sourceSnapshotVersion: options.sourceSnapshotVersion, sourceDatabaseSha256: options.sourceDatabaseSha256, sourceE1: { contractVersion: "0.2.0", sha256: options.sourceE1Sha256 }, questStages, unboundQuestLevels: unboundQuestLevels.sort((a, b) => Number(a.identity.id) - Number(b.identity.id)), areaRequirements: o.areaConditions.map(row => ({ sourceRowId: str(row, "id"), areaId: str(row, "area_id"), status: "partial" as const, rawType: str(row, "type"), conditionsRawJson: str(row, "conditions"), comment: str(row, "comment") })).sort((a, b) => Number(a.sourceRowId) - Number(b.sourceRowId)), zBattleTopologies, originBattles, sdTopologies, nonTraditionalBoundaries: [{ family: "budokai", status: "partial", rootCount: options.budokaiRootCount, missing: ["stage_table", "server_match_topology"] }, { family: "rmbattle", status: "partial", rootCount: options.rmbattleRootCount, missing: ["root_table", "stage_table", "server_runtime_topology"] }] };
}

export function buildEventsE2Coverage(dataset: EventsE2Dataset, e1: EventsE1Dataset): EventsE2Coverage { const levels = dataset.questStages.flatMap(value => value.levels), rawDifficultyCounts: Record<string, number> = {}; for (const value of levels) rawDifficultyCounts[String(value.rawDifficulty)] = (rawDifficultyCounts[String(value.rawDifficulty)] ?? 0) + 1; const areas = new Set(e1.catalog.filter(value => value.identity.kind === "area").map(value => value.identity.id)), quests = new Set(dataset.questStages.map(value => value.identity.id)), zExpected = new Set(e1.catalog.filter(value => value.identity.kind === "z_battle_stage").map(value => value.identity.id)), zActual = new Set(dataset.zBattleTopologies.map(value => value.identity.stageId)), sdExpected = new Set(e1.catalog.filter(value => value.identity.kind === "sd_map").map(value => value.identity.id)), sdActual = new Set(dataset.sdTopologies.map(value => value.identity.mapId)); const danglingIdCount = dataset.questStages.filter(value => !areas.has(value.areaId)).length + dataset.questStages.filter(value => value.previousStageId !== null && !quests.has(value.previousStageId)).length + dataset.areaRequirements.filter(value => !areas.has(value.areaId)).length + [...zActual].filter(value => !zExpected.has(value)).length + [...zExpected].filter(value => !zActual.has(value)).length + [...sdActual].filter(value => !sdExpected.has(value)).length + [...sdExpected].filter(value => !sdActual.has(value)).length; return { schemaVersion: 1, questStageCount: dataset.questStages.length, questLevelCount: levels.length, rawDifficultyCounts, unboundQuestLevelCount: dataset.unboundQuestLevels.length, areaRequirementCount: dataset.areaRequirements.length, zBattleStageCount: dataset.zBattleTopologies.length, zBattleEnemyRangeCount: dataset.zBattleTopologies.reduce((sum, value) => sum + value.enemyRanges.length, 0), zBattleCheckpointCount: dataset.zBattleTopologies.reduce((sum, value) => sum + value.checkpoints.length, 0), zBattleRewardLevelAnchorCount: dataset.zBattleTopologies.reduce((sum, value) => sum + value.rewardLevelAnchors.length, 0), originBattleCount: dataset.originBattles.length, sdMapCount: dataset.sdTopologies.length, sdArenaCount: dataset.sdTopologies.reduce((sum, value) => sum + value.arenas.length, 0), sdStageCount: dataset.sdTopologies.reduce((sum, value) => sum + value.arenas.reduce((inner, arena) => inner + arena.stages.length, 0), 0), danglingIdCount }; }
