import { createHash } from "crypto";
import { createReadStream, existsSync } from "fs";
import { mkdir, readFile, stat, writeFile } from "fs/promises";
import { resolve } from "path";
import { resolveEventsInputFile, resolveEventsOutputFiles } from "./events-artifact-path";
import { inspectNativeRuntimeElf } from "../database-experiment/native-runtime-elf-adapter";
import { EventsE0Baseline } from "./events-e0-contract";
import { EventsE2Dataset, EventsE2Manifest } from "./events-e2-contract";
import { EventsE3Baseline, EventsE3Coverage, EventsE3Dataset, EventsE3Goldens, EventsE3Manifest, EventsE3Validation } from "./events-e3-contract";
import { buildEventsE4Coverage, buildEventsE4Dataset } from "./events-e4-builder";
import { EventsE4Manifest, EventsE4NativeEvidence, EventsE4Observation } from "./events-e4-contract";
import { validateEventsE4Dataset, validateEventsE4NativeEvidence } from "./events-e4-validator";
import { runEventsSqliteBridge } from "./events-sqlite-adapter";

const DEFAULT_DATABASE = "D:/Dokkan/database/decrypted/dokkan-global-current.db", DEFAULT_ELF = "D:/Dokkan/database/apk/extracted/lib/arm64-v8a/libcocos2dcpp.so", DEFAULT_OUTPUT = resolve(process.cwd(), "data", "database-events"), MEMORY_LIMIT = 1024 * 1024 * 1024;
let peakWorkingSetBytes = 0;
function memory() { peakWorkingSetBytes = Math.max(peakWorkingSetBytes, process.memoryUsage().rss, process.resourceUsage().maxRSS * 1024); if (peakWorkingSetBytes > MEMORY_LIMIT) throw Error(`E4 memory limit exceeded ${peakWorkingSetBytes}`); }
const sha = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
async function fingerprint(path: string) { const metadata = await stat(path), hash = createHash("sha256"); await new Promise<void>((done, reject) => { const stream = createReadStream(path); stream.on("data", chunk => { hash.update(chunk); memory(); }); stream.on("error", reject); stream.on("end", done); }); return { sha256: hash.digest("hex"), sizeBytes: metadata.size, modifiedAtMs: metadata.mtimeMs }; }
function sourcePath(name: string) { const adjacent = resolve(__dirname, name); return existsSync(adjacent) ? adjacent : resolve(__dirname, "..", "..", "database-events", name); }

export async function runEventsE4(options: { databasePath?: string; elfPath?: string; outputDir?: string; e3Dir?: string; e2Dir?: string; baselinePath?: string; e3BaselinePath?: string; nativeEvidencePath?: string } = {}) {
    peakWorkingSetBytes = 0;
    const databasePath = resolve(options.databasePath ?? DEFAULT_DATABASE), elfPath = resolve(options.elfPath ?? DEFAULT_ELF), outputDir = resolve(options.outputDir ?? DEFAULT_OUTPUT), e3Dir = resolve(options.e3Dir ?? DEFAULT_OUTPUT), e2Dir = resolve(options.e2Dir ?? DEFAULT_OUTPUT);
    const baseline = JSON.parse(await readFile(options.baselinePath ? resolve(options.baselinePath) : sourcePath("events-e0-baseline.json"), "utf8")) as EventsE0Baseline, e3Baseline = JSON.parse(await readFile(options.e3BaselinePath ? resolve(options.e3BaselinePath) : sourcePath("events-e3-baseline.json"), "utf8")) as EventsE3Baseline, nativeEvidenceBytes = await readFile(options.nativeEvidencePath ? resolve(options.nativeEvidencePath) : sourcePath("events-e4-native-enemy-efficacy-map.json")), nativeEvidence = JSON.parse(nativeEvidenceBytes.toString("utf8")) as EventsE4NativeEvidence, nativeEvidenceSha256 = sha(`${JSON.stringify(nativeEvidence, null, 2)}\n`);
    const e3Manifest = JSON.parse(await readFile(await resolveEventsInputFile(e3Dir, "events-e3-manifest.json", "events-e3-manifest.json"), "utf8")) as EventsE3Manifest, e2Manifest = JSON.parse(await readFile(await resolveEventsInputFile(e2Dir, "events-e2-manifest.json", "events-e2-manifest.json"), "utf8")) as EventsE2Manifest;
    const [e3Path, e3CoveragePath, e3ValidationPath, e3GoldensPath, e2Path] = await Promise.all([resolveEventsInputFile(e3Dir, e3Manifest.fileName, "events-e3-encounters.json"), resolveEventsInputFile(e3Dir, e3Manifest.coverage?.fileName, "events-e3-coverage.json"), resolveEventsInputFile(e3Dir, e3Manifest.validation?.fileName, "events-e3-validation.json"), resolveEventsInputFile(e3Dir, e3Manifest.goldens?.fileName, "events-e3-goldens.json"), resolveEventsInputFile(e2Dir, e2Manifest.fileName, "events-e2-topology.json")]);
    const [e3Bytes, e3CoverageBytes, e3ValidationBytes, e3GoldensBytes, e2Bytes] = await Promise.all([readFile(e3Path), readFile(e3CoveragePath), readFile(e3ValidationPath), readFile(e3GoldensPath), readFile(e2Path)]); memory();
    const e3 = JSON.parse(e3Bytes.toString("utf8")) as EventsE3Dataset, e3Coverage = JSON.parse(e3CoverageBytes.toString("utf8")) as EventsE3Coverage, e3Validation = JSON.parse(e3ValidationBytes.toString("utf8")) as EventsE3Validation, e3Goldens = JSON.parse(e3GoldensBytes.toString("utf8")) as EventsE3Goldens, e2 = JSON.parse(e2Bytes.toString("utf8")) as EventsE2Dataset;
    if (e3Baseline.snapshotVersion !== baseline.snapshotVersion || e3Baseline.sourceE2Sha256 !== e3Manifest.sourceE2Sha256 || JSON.stringify(e3Goldens) !== JSON.stringify(e3Baseline.goldens) || e3Manifest.contractVersion !== "0.4.0" || e3Manifest.generatedAtPolicy !== "pinned_to_source_snapshot_for_reproducible_bytes" || e3Manifest.generatedAt !== baseline.generatedAt || e3Manifest.sourceSnapshotVersion !== baseline.snapshotVersion || e3Manifest.sourceDatabaseSha256 !== baseline.sourceDatabase.sha256 || e3Bytes.byteLength !== e3Manifest.sizeBytes || sha(e3Bytes) !== e3Manifest.sha256 || e3CoverageBytes.byteLength !== e3Manifest.coverage.sizeBytes || sha(e3CoverageBytes) !== e3Manifest.coverage.sha256 || e3ValidationBytes.byteLength !== e3Manifest.validation.sizeBytes || sha(e3ValidationBytes) !== e3Manifest.validation.sha256 || e3GoldensBytes.byteLength !== e3Manifest.goldens.sizeBytes || sha(e3GoldensBytes) !== e3Manifest.goldens.sha256 || e3.contract !== "dokkan-events-database-first-encounters" || e3.contractVersion !== "0.4.0" || e3.generatedAt !== baseline.generatedAt || e3.generatedAtPolicy !== "pinned_to_source_snapshot_for_reproducible_bytes" || e3.sourceSnapshotVersion !== baseline.snapshotVersion || e3.sourceDatabaseSha256 !== baseline.sourceDatabase.sha256 || e3.sourceE2.sha256 !== e3Manifest.sourceE2Sha256 || e3Coverage.danglingIdCount !== 0 || !e3Validation.valid || !e3Validation.exactProjection) throw Error("E4 E3 lineage");
    if (e2Manifest.sha256 !== e3Manifest.sourceE2Sha256 || e2Bytes.byteLength !== e2Manifest.sizeBytes || sha(e2Bytes) !== e2Manifest.sha256 || e2.contract !== "dokkan-events-database-first-topology" || e2.contractVersion !== "0.3.0" || e2.generatedAtPolicy !== "pinned_to_source_snapshot_for_reproducible_bytes" || e2.sourceSnapshotVersion !== baseline.snapshotVersion || e2.sourceDatabaseSha256 !== baseline.sourceDatabase.sha256) throw Error("E4 E2 lineage");
    const databaseBefore = await fingerprint(databasePath), elfBefore = await fingerprint(elfPath); if (databaseBefore.sha256 !== baseline.sourceDatabase.sha256 || databaseBefore.sizeBytes !== baseline.sourceDatabase.sizeBytes || elfBefore.sha256 !== nativeEvidence.sourceElfSha256 || elfBefore.sizeBytes !== nativeEvidence.sourceElfSizeBytes) throw Error("E4 pinned source identity");
    const inspection = await inspectNativeRuntimeElf(elfPath); memory(); const nativeEvidenceValid = validateEventsE4NativeEvidence(nativeEvidence, nativeEvidenceSha256, inspection); if (!nativeEvidenceValid) throw Error("E4 native evidence");
    const observation = await runEventsSqliteBridge<EventsE4Observation>("mechanics", databasePath, memory), dataset = buildEventsE4Dataset({ observation, e3, e2, nativeEvidence, nativeEvidenceSha256, generatedAt: baseline.generatedAt, sourceSnapshotVersion: baseline.snapshotVersion, sourceDatabaseSha256: databaseBefore.sha256, sourceE3Sha256: e3Manifest.sha256, sourceE2Sha256: e2Manifest.sha256 }), coverage = buildEventsE4Coverage(dataset, e3, e2, observation), validation = validateEventsE4Dataset(dataset, observation, e3, e2, nativeEvidence, nativeEvidenceSha256, nativeEvidenceValid, { generatedAt: baseline.generatedAt, sourceSnapshotVersion: baseline.snapshotVersion, sourceDatabaseSha256: databaseBefore.sha256, sourceE3Sha256: e3Manifest.sha256, sourceE2Sha256: e2Manifest.sha256 });
    if (!validation.valid || coverage.danglingIdCount !== 0) throw Error(`E4 validation ${JSON.stringify(validation.failures)} dangling=${coverage.danglingIdCount}`);
    const databaseAfter = await fingerprint(databasePath), elfAfter = await fingerprint(elfPath); if (JSON.stringify(databaseBefore) !== JSON.stringify(databaseAfter) || JSON.stringify(elfBefore) !== JSON.stringify(elfAfter)) throw Error("E4 read-only source guarantee");
    const payloadText = `${JSON.stringify(dataset, null, 2)}\n`, coverageText = `${JSON.stringify(coverage, null, 2)}\n`, validationText = `${JSON.stringify(validation, null, 2)}\n`;
    const manifest: EventsE4Manifest = { schemaVersion: 1, contractVersion: "0.5.0", generatedAt: dataset.generatedAt, generatedAtPolicy: dataset.generatedAtPolicy, sourceSnapshotVersion: dataset.sourceSnapshotVersion, fileName: "events-e4-mechanics.json", compression: "none", sha256: sha(payloadText), sizeBytes: Buffer.byteLength(payloadText), sourceDatabaseSha256: dataset.sourceDatabaseSha256, sourceE3Sha256: dataset.sourceE3.sha256, sourceE2Sha256: dataset.sourceE2.sha256, sourceElfSha256: nativeEvidence.sourceElfSha256, nativeEvidenceSha256, coverage: { fileName: "events-e4-coverage.json", sha256: sha(coverageText), sizeBytes: Buffer.byteLength(coverageText) }, validation: { fileName: "events-e4-validation.json", sha256: sha(validationText), sizeBytes: Buffer.byteLength(validationText) } };
    await mkdir(outputDir, { recursive: true }); const outputs = await resolveEventsOutputFiles(outputDir, [manifest.fileName, manifest.coverage.fileName, manifest.validation.fileName, "events-e4-manifest.json"]); await Promise.all([writeFile(outputs.get(manifest.fileName)!, payloadText), writeFile(outputs.get(manifest.coverage.fileName)!, coverageText), writeFile(outputs.get(manifest.validation.fileName)!, validationText), writeFile(outputs.get("events-e4-manifest.json")!, `${JSON.stringify(manifest, null, 2)}\n`)]); memory();
    return { dataset, coverage, validation, manifest, peakWorkingSetBytes };
}

if (require.main === module) runEventsE4().then(value => console.log(JSON.stringify({ coverage: value.coverage, validation: value.validation, manifest: value.manifest, peakWorkingSetBytes: value.peakWorkingSetBytes }, null, 2))).catch(error => { console.error(error); process.exitCode = 1; });
