import { EventsE2Dataset } from "./events-e2-contract";
import { EventsE3Dataset, EventsE3RawRow } from "./events-e3-contract";
import { EventsE4Coverage, EventsE4Dataset, EventsE4NativeEvidence, EventsE4Observation, EventsE4Relation } from "./events-e4-contract";

const str = (value: unknown) => String(value);
const num = (row: EventsE3RawRow, key: string) => Number(row[key]);
const nullableId = (value: unknown) => value === null ? null : str(value);
const group = (rows: EventsE3RawRow[], column: string) => { const result = new Map<string, EventsE3RawRow[]>(); for (const row of rows) { const key = str(row[column]); result.set(key, [...(result.get(key) ?? []), row]); } return result; };
function relation(rows: EventsE3RawRow[], targetColumn: string): EventsE4Relation[] { return rows.map(row => ({ sourceRowId: str(row.id), enemySkillId: str(row.enemy_skill_id), targetId: str(row[targetColumn]), structuralStatus: "supported", semanticStatus: "partial", semanticBoundary: "relation_membership_proven_effect_direction_and_magnitude_unknown" })); }

export function buildEventsE4Dataset(options: { observation: EventsE4Observation; e3: EventsE3Dataset; e2: EventsE2Dataset; nativeEvidence: EventsE4NativeEvidence; nativeEvidenceSha256: string; generatedAt: string; sourceSnapshotVersion: string; sourceDatabaseSha256: string; sourceE3Sha256: string; sourceE2Sha256: string }): EventsE4Dataset {
    const { observation: o, e3, e2 } = options;
    const inventory = (sourceKind: "enemy_skill" | "enemy_round_skill", rows: Array<{ raw: EventsE3RawRow }>) => { const counts = new Map<number, number>(); for (const row of rows) { const raw = Number(row.raw.efficacy_type); counts.set(raw, (counts.get(raw) ?? 0) + 1); } return [...counts].sort((a, b) => a[0] - b[0]).map(([rawEfficacyType, ruleCount]) => ({ sourceKind, rawEfficacyType, ruleCount, structuralStatus: "supported" as const, semanticStatus: "unknown" as const })); };
    const subMembers = group(o.subTargetTypes, "sub_target_type_set_id"), questIds = new Set(e2.questStages.map(value => value.identity.id)), heatEntries = group(o.heatUpGimmicks, "heat_up_gimmick_set_id"), heatRefs = group(o.originBattleHeatUpReferences.filter(row => row.heat_up_gimmick_set_id !== null), "heat_up_gimmick_set_id");
    return {
        schemaVersion: 1, contract: "dokkan-events-database-first-mechanics", contractVersion: "0.5.0", generatedAt: options.generatedAt, generatedAtPolicy: "pinned_to_source_snapshot_for_reproducible_bytes", sourceSnapshotVersion: options.sourceSnapshotVersion, sourceDatabaseSha256: options.sourceDatabaseSha256,
        sourceE3: { contractVersion: "0.4.0", sha256: options.sourceE3Sha256 }, sourceE2: { contractVersion: "0.3.0", sha256: options.sourceE2Sha256 }, nativeEvidence: { fileName: "events-e4-native-enemy-efficacy-map.json", sha256: options.nativeEvidenceSha256, sourceElfSha256: options.nativeEvidence.sourceElfSha256, status: "partial", promotion: "none" },
        rawSkillTypeInventory: [...inventory("enemy_skill", e3.enemySkills), ...inventory("enemy_round_skill", e3.enemyRoundSkills)],
        relatedCardCategories: relation(o.relatedCardCategories, "card_category_id"), relatedLinkSkills: relation(o.relatedLinkSkills, "link_skill_id"), relatedOptimalAwakenings: relation(o.relatedOptimalAwakenings, "card_category_id"), relatedPassiveSkillSets: relation(o.relatedPassiveSkillSets, "passive_skill_set_id"),
        subTargetSets: o.subTargetTypeSets.map(row => ({ setId: str(row.id), structuralStatus: "supported", semanticStatus: "partial", members: (subMembers.get(str(row.id)) ?? []).map(member => ({ sourceRowId: str(member.id), rawTargetValueType: num(member, "target_value_type"), rawTargetValue: num(member, "target_value") })) })),
        questCategoryBonuses: o.questCategoryBonuses.map(row => ({ sourceRowId: str(row.id), questId: str(row.quest_id), bindingStatus: questIds.has(str(row.quest_id)) ? "supported" : "unknown", rawType: str(row.type), cardCategoryId: str(row.card_category_id), rarityTableId: str(row.quest_category_bonus_rarity_table_id), semanticStatus: "partial" })),
        questCategoryBonusRarityTables: o.questCategoryBonusRarityTables.map(row => ({ identity: { kind: "quest_category_bonus_rarity_table", id: str(row.id) }, rawByRarity: { n: num(row, "rarity_n"), r: num(row, "rarity_r"), sr: num(row, "rarity_sr"), ssr: num(row, "rarity_ssr"), ur: num(row, "rarity_ur"), lr: num(row, "rarity_lr") }, semanticStatus: "partial", unknowns: ["unit", "application_formula", "stacking"] })),
        originHeatUpMechanics: [...heatRefs].sort((a, b) => Number(a[0]) - Number(b[0])).map(([setId, references]) => ({ heatUpGimmickSetId: setId, originBattleIds: references.map(row => str(row.id)), status: "partial", entries: (heatEntries.get(setId) ?? []).map(entry => ({ sourceRowId: str(entry.id), rawGaugeStart: num(entry, "gauge_start"), heatUpGimmickSkillId: str(entry.heat_up_gimmick_skill_id), overrideId: nullableId(entry.override_id) })), semanticBoundary: "grouping_and_threshold_order_structural_runtime_effect_unknown" })),
        heatUpGimmickSkills: o.heatUpGimmickSkills.map(row => ({ identity: { kind: "heat_up_gimmick_skill", id: str(row.id) }, rawEfficacyType: num(row, "efficacy_type"), rawEffectValue1: num(row, "eff_value1"), semanticStatus: "unknown" })),
        unboundEnemyAiConditions: o.enemyAiConditions.map(row => ({ sourceRowId: str(row.id), bindingStatus: "unknown", raw: row })), unboundMechanicSurfaces: o.unboundMechanicSurfaces.map(value => ({ ...value, status: "unknown", missing: ["event_or_stage_consumer"] })),
        requestedMechanicCoverage: [
            { family: "damage_reduction", status: "unknown", boundary: "raw_enemy_rules_only_no_enemy_specific_consumer_proof" },
            { family: "guard_type_class", status: "unknown", boundary: "no_enemy_specific_consumer_proof" },
            { family: "status_immunities", status: "partial", boundary: "native_type_conversion_and_generic_handler_exist_but_runtime_chain_is_unproven" },
            { family: "dodge_nullification_attack_break", status: "unknown", boundary: "no_enemy_specific_consumer_proof" },
            { family: "super_attack_behavior", status: "unknown", boundary: "enemy_ai_rows_have_no_proven_encounter_binding" },
            { family: "category_link_advantages", status: "partial", boundary: "membership_relations_supported_effect_direction_and_magnitude_unknown" },
            { family: "phase_transitions", status: "partial", boundary: "ordered_round_topology_supported_transition_trigger_semantics_unknown" },
            { family: "locks_sealing_rotations_fields", status: "unknown", boundary: "raw_rules_only_no_semantic_promotion" },
            { family: "countdowns_limits_special_rules", status: "partial", boundary: "raw_timing_turn_probability_conditions_and_limits_preserved_without_runtime_semantics" },
        ],
    };
}

export function buildEventsE4Coverage(dataset: EventsE4Dataset, e3: EventsE3Dataset, e2: EventsE2Dataset, observation: EventsE4Observation): EventsE4Coverage {
    const enemyIds = new Set(e3.enemySkills.map(value => value.identity.id)), roundSkillIds = new Set(e3.enemyRoundSkills.map(value => value.identity.id)), categoryIds = new Set(observation.cardCategoryTargets.map(value => str(value.id))), linkIds = new Set(observation.linkSkillTargets.map(value => str(value.id))), passiveSetIds = new Set(observation.passiveSkillSetTargets.map(value => str(value.id))), subSetIds = new Set(dataset.subTargetSets.map(value => value.setId)), rarityIds = new Set(dataset.questCategoryBonusRarityTables.map(value => value.identity.id)), originIds = new Set(e2.originBattles.map(value => value.identity.id)), heatSkillIds = new Set(dataset.heatUpGimmickSkills.map(value => value.identity.id)), heatEntryIds = new Set(dataset.originHeatUpMechanics.flatMap(value => value.entries).map(value => value.sourceRowId));
    let danglingIdCount = 0;
    for (const value of dataset.relatedCardCategories) danglingIdCount += Number(!enemyIds.has(value.enemySkillId)) + Number(!categoryIds.has(value.targetId));
    for (const value of dataset.relatedOptimalAwakenings) danglingIdCount += Number(!enemyIds.has(value.enemySkillId)) + Number(!categoryIds.has(value.targetId));
    for (const value of dataset.relatedLinkSkills) danglingIdCount += Number(!enemyIds.has(value.enemySkillId)) + Number(!linkIds.has(value.targetId));
    for (const value of dataset.relatedPassiveSkillSets) danglingIdCount += Number(!enemyIds.has(value.enemySkillId)) + Number(!passiveSetIds.has(value.targetId));
    for (const skill of [...e3.enemySkills, ...e3.enemyRoundSkills]) if (Number(skill.raw.sub_target_type_set_id) !== 0) danglingIdCount += Number(!subSetIds.has(str(skill.raw.sub_target_type_set_id)));
    for (const value of dataset.questCategoryBonuses) danglingIdCount += Number(!categoryIds.has(value.cardCategoryId)) + Number(!rarityIds.has(value.rarityTableId));
    for (const value of dataset.originHeatUpMechanics) { danglingIdCount += value.originBattleIds.filter(id => !originIds.has(id)).length; for (const entry of value.entries) danglingIdCount += Number(!heatSkillIds.has(entry.heatUpGimmickSkillId)) + Number(entry.overrideId !== null && !heatEntryIds.has(entry.overrideId)); }
    const statuses = (status: "supported" | "partial" | "unknown") => dataset.requestedMechanicCoverage.filter(value => value.status === status).length;
    return { schemaVersion: 1, enemySkillRuleCount: e3.enemySkills.length, enemyRoundSkillRuleCount: e3.enemyRoundSkills.length, rawEnemyEfficacyTypeCount: dataset.rawSkillTypeInventory.filter(value => value.sourceKind === "enemy_skill").length, rawRoundEfficacyTypeCount: dataset.rawSkillTypeInventory.filter(value => value.sourceKind === "enemy_round_skill").length, cardCategoryRelationCount: dataset.relatedCardCategories.length, linkSkillRelationCount: dataset.relatedLinkSkills.length, optimalAwakeningRelationCount: dataset.relatedOptimalAwakenings.length, passiveSkillSetRelationCount: dataset.relatedPassiveSkillSets.length, subTargetSetCount: dataset.subTargetSets.length, subTargetMemberCount: dataset.subTargetSets.reduce((sum, value) => sum + value.members.length, 0), questCategoryBonusCount: dataset.questCategoryBonuses.length, unboundQuestCategoryBonusCount: dataset.questCategoryBonuses.filter(value => value.bindingStatus === "unknown").length, originHeatUpBattleCount: dataset.originHeatUpMechanics.reduce((sum, value) => sum + value.originBattleIds.length, 0), heatUpEntryCount: dataset.originHeatUpMechanics.reduce((sum, value) => sum + value.entries.length, 0), unboundEnemyAiConditionCount: dataset.unboundEnemyAiConditions.length, danglingIdCount, requestedSupportedCount: statuses("supported"), requestedPartialCount: statuses("partial"), requestedUnknownCount: statuses("unknown") };
}
