import { createHash } from "crypto";
import { createReadStream } from "fs";
import { mkdir, readFile, stat, writeFile } from "fs/promises";
import { resolve } from "path";
import { resolveEventsInputFile, resolveEventsOutputFiles } from "./events-artifact-path";
import { EventsE0Baseline } from "./events-e0-contract";
import { EventsE1Coverage, EventsE1Dataset, EventsE1Manifest, EventsE1Validation } from "./events-e1-contract";
import { buildEventsE2Coverage, buildEventsE2Dataset } from "./events-e2-builder";
import { EventsE2Manifest, EventsE2Observation } from "./events-e2-contract";
import { runEventsSqliteBridge } from "./events-sqlite-adapter";
import { validateEventsE2Dataset } from "./events-e2-validator";

const DEFAULT_DATABASE = "D:/Dokkan/database/decrypted/dokkan-global-current.db", DEFAULT_OUTPUT = resolve(process.cwd(), "data", "database-events"), MEMORY_LIMIT = 1024 * 1024 * 1024; let peakWorkingSetBytes = 0;
function memory() { peakWorkingSetBytes = Math.max(peakWorkingSetBytes, process.memoryUsage().rss, process.resourceUsage().maxRSS * 1024); if (peakWorkingSetBytes > MEMORY_LIMIT) throw Error(`E2 memory limit exceeded ${peakWorkingSetBytes}`); }
async function fingerprint(path: string) { const metadata = await stat(path), hash = createHash("sha256"); await new Promise<void>((done, reject) => { const stream = createReadStream(path); stream.on("data", chunk => { hash.update(chunk); memory(); }); stream.on("error", reject); stream.on("end", done); }); return { sha256: hash.digest("hex"), sizeBytes: metadata.size, modifiedAtMs: metadata.mtimeMs }; }
function sourcePath(name: string) { const adjacent = resolve(__dirname, name); return require("fs").existsSync(adjacent) ? adjacent : resolve(__dirname, "..", "..", "database-events", name); }

export async function runEventsE2(options: { databasePath?: string; outputDir?: string; e1Dir?: string; baselinePath?: string } = {}) {
    peakWorkingSetBytes = 0; const databasePath = resolve(options.databasePath ?? DEFAULT_DATABASE), outputDir = resolve(options.outputDir ?? DEFAULT_OUTPUT), e1Dir = resolve(options.e1Dir ?? DEFAULT_OUTPUT), sha = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
    const baseline = JSON.parse(await readFile(options.baselinePath ? resolve(options.baselinePath) : sourcePath("events-e0-baseline.json"), "utf8")) as EventsE0Baseline, e1Manifest = JSON.parse(await readFile(await resolveEventsInputFile(e1Dir, "events-e1-manifest.json", "events-e1-manifest.json"), "utf8")) as EventsE1Manifest;
    const [e1Path, coveragePath, validationPath] = await Promise.all([resolveEventsInputFile(e1Dir, e1Manifest.fileName, "events-e1-catalog.json"), resolveEventsInputFile(e1Dir, e1Manifest.coverage?.fileName, "events-e1-coverage.json"), resolveEventsInputFile(e1Dir, e1Manifest.validation?.fileName, "events-e1-validation.json")]);
    const [e1Bytes, coverageBytes, validationBytes] = await Promise.all([readFile(e1Path), readFile(coveragePath), readFile(validationPath)]), e1 = JSON.parse(e1Bytes.toString("utf8")) as EventsE1Dataset, e1Coverage = JSON.parse(coverageBytes.toString("utf8")) as EventsE1Coverage, e1Validation = JSON.parse(validationBytes.toString("utf8")) as EventsE1Validation;
    if (e1Manifest.contractVersion !== "0.2.0" || e1Manifest.generatedAtPolicy !== "pinned_to_source_snapshot_for_reproducible_bytes" || e1Manifest.generatedAt !== baseline.generatedAt || e1Manifest.sourceSnapshotVersion !== baseline.snapshotVersion || e1Manifest.sourceDatabaseSha256 !== baseline.sourceDatabase.sha256 || e1Bytes.byteLength !== e1Manifest.sizeBytes || sha(e1Bytes) !== e1Manifest.sha256 || coverageBytes.byteLength !== e1Manifest.coverage.sizeBytes || sha(coverageBytes) !== e1Manifest.coverage.sha256 || validationBytes.byteLength !== e1Manifest.validation.sizeBytes || sha(validationBytes) !== e1Manifest.validation.sha256 || e1.contract !== "dokkan-events-database-first-catalog" || e1.contractVersion !== "0.2.0" || e1.generatedAt !== baseline.generatedAt || e1.generatedAtPolicy !== "pinned_to_source_snapshot_for_reproducible_bytes" || e1.sourceSnapshotVersion !== baseline.snapshotVersion || e1.sourceDatabaseSha256 !== baseline.sourceDatabase.sha256 || e1.sourceE0.sha256 !== e1Manifest.sourceE0Sha256 || e1Coverage.entityCount !== e1.catalog.length || !e1Validation.valid || e1Validation.losslessIdentityCount !== e1.catalog.length) throw Error("E2 E1 lineage");
    const before = await fingerprint(databasePath); if (before.sha256 !== baseline.sourceDatabase.sha256 || before.sizeBytes !== baseline.sourceDatabase.sizeBytes) throw Error("E2 pinned database identity");
    const observation = await runEventsSqliteBridge<EventsE2Observation>("topology", databasePath, memory), budokaiRootCount = e1.catalog.filter(value => value.identity.kind === "budokai").length, rmbattleRootCount = e1.opaqueRootFamilies.find(value => value.family === "rmbattle")?.identities.length ?? 0;
    const dataset = buildEventsE2Dataset({ observation, generatedAt: baseline.generatedAt, sourceSnapshotVersion: baseline.snapshotVersion, sourceDatabaseSha256: before.sha256, sourceE1Sha256: e1Manifest.sha256, budokaiRootCount, rmbattleRootCount }), coverage = buildEventsE2Coverage(dataset, e1), validation = validateEventsE2Dataset(dataset, observation, e1, { generatedAt: baseline.generatedAt, sourceSnapshotVersion: baseline.snapshotVersion, sourceDatabaseSha256: before.sha256, sourceE1Sha256: e1Manifest.sha256 }); if (!validation.valid || coverage.danglingIdCount !== 0) throw Error(`E2 validation ${JSON.stringify(validation.failures)} dangling=${coverage.danglingIdCount}`);
    const after = await fingerprint(databasePath); if (JSON.stringify(before) !== JSON.stringify(after)) throw Error("E2 read-only source guarantee");
    const payloadText = `${JSON.stringify(dataset, null, 2)}\n`, coverageText = `${JSON.stringify(coverage, null, 2)}\n`, validationText = `${JSON.stringify(validation, null, 2)}\n`, manifest: EventsE2Manifest = { schemaVersion: 1, contractVersion: "0.3.0", generatedAt: dataset.generatedAt, generatedAtPolicy: dataset.generatedAtPolicy, sourceSnapshotVersion: dataset.sourceSnapshotVersion, fileName: "events-e2-topology.json", compression: "none", sha256: sha(payloadText), sizeBytes: Buffer.byteLength(payloadText), sourceDatabaseSha256: dataset.sourceDatabaseSha256, sourceE1Sha256: dataset.sourceE1.sha256, coverage: { fileName: "events-e2-coverage.json", sha256: sha(coverageText), sizeBytes: Buffer.byteLength(coverageText) }, validation: { fileName: "events-e2-validation.json", sha256: sha(validationText), sizeBytes: Buffer.byteLength(validationText) } };
    await mkdir(outputDir, { recursive: true }); const outputs = await resolveEventsOutputFiles(outputDir, [manifest.fileName, manifest.coverage.fileName, manifest.validation.fileName, "events-e2-manifest.json"]); await Promise.all([writeFile(outputs.get(manifest.fileName)!, payloadText), writeFile(outputs.get(manifest.coverage.fileName)!, coverageText), writeFile(outputs.get(manifest.validation.fileName)!, validationText), writeFile(outputs.get("events-e2-manifest.json")!, `${JSON.stringify(manifest, null, 2)}\n`)]); memory(); return { dataset, coverage, validation, manifest, peakWorkingSetBytes };
}
if (require.main === module) runEventsE2().then(value => console.log(JSON.stringify({ coverage: value.coverage, validation: value.validation, manifest: value.manifest, peakWorkingSetBytes: value.peakWorkingSetBytes }, null, 2))).catch(error => { console.error(error); process.exitCode = 1; });
