import { createHash } from "crypto";
import { EventsE3RawRow } from "./events-e3-contract";
import { EventsE6ApkObservation, EventsE6Binding, EventsE6Coverage, EventsE6Dataset, EventsE6EntityKind, EventsE6NumericAssetKind, EventsE6Observation } from "./events-e6-contract";

const str = (value: unknown) => String(value);
const keyHash = (value: string) => createHash("sha256").update(value).digest("hex");

export function buildEventsE6Dataset(options: { observation: EventsE6Observation; apk: EventsE6ApkObservation; generatedAt: string; sourceSnapshotVersion: string; sourceDatabaseSha256: string; sourceE5Sha256: string; sourceApkSha256: string; sourceApkSizeBytes: number }): EventsE6Dataset {
    const { observation: o, apk } = options, bindings: EventsE6Binding[] = [], pathValues = new Set<string>(), numericValues = new Map<string, { kind: EventsE6NumericAssetKind; rawId: string }>();
    const bindPath = (row: EventsE3RawRow, table: string, entityKind: EventsE6EntityKind, entityId: unknown, column: string) => { const value = row[column]; if (value === null || value === undefined || value === "") return; const rawPath = str(value), assetKey = `database_path:${keyHash(rawPath)}`; pathValues.add(rawPath); bindings.push({ source: { entityKind, entityId: str(entityId), table, rowId: str(row.id), column }, assetKey, structuralStatus: "supported" }); };
    const bindNumeric = (row: EventsE3RawRow, table: string, entityKind: EventsE6EntityKind, entityId: unknown, column: string, kind: EventsE6NumericAssetKind) => { if (row[column] === null || row[column] === undefined) return; const rawId = str(row[column]), assetKey = `${kind}:${rawId}`; numericValues.set(assetKey, { kind, rawId }); bindings.push({ source: { entityKind, entityId: str(entityId), table, rowId: str(row.id), column }, assetKey, structuralStatus: "supported" }); };
    const pathFields = (rows: EventsE3RawRow[], table: string, entityKind: EventsE6EntityKind, fields: string[], entityId = (row: EventsE3RawRow) => row.id) => { for (const row of rows) for (const field of fields) bindPath(row, table, entityKind, entityId(row), field); };
    pathFields(o.areas, "areas", "area", ["event_image_path", "banner_image_path", "listbutton_image_path"]);
    pathFields(o.zBattleStages, "z_battle_stages", "z_battle_stage", ["banner_image_path", "listbutton_image_path"]);
    pathFields(o.budokais, "budokais", "budokai", ["mission_reward_image_path", "banner_image_path", "home_banner_image_path", "listbutton_image_path"]);
    pathFields(o.originSeries, "origin_series", "origin_series", ["banner_image_path"]);
    pathFields(o.originEpisodes, "origin_episodes", "origin_episode", ["banner_image_path"]);
    pathFields(o.originPages, "origin_pages", "origin_page", ["background_image_path"]);
    pathFields(o.linkedMissionCategories, "mission_categories", "mission_category", ["image_path"]);
    for (const row of o.questMaps) { for (const field of ["sugoroku_bgm_id", "battle_bgm_id", "boss_bgm_id"] as const) bindNumeric(row, "sugoroku_maps", "quest_level", row.id, field, "bgm"); bindNumeric(row, "sugoroku_maps", "quest_level", row.id, "battle_background_id", "battle_background"); for (const field of ["start_script_id", "finish_script_id"] as const) bindNumeric(row, "sugoroku_maps", "quest_level", row.id, field, "script"); }
    for (const row of o.zBattleStageViews) bindNumeric(row, "z_battle_stage_views", "z_battle_stage", row.z_battle_stage_id, "enemy_resource_id", "z_enemy_resource");
    for (const row of o.budokais) for (const field of ["entry_script_id", "description_script_id"] as const) bindNumeric(row, "budokais", "budokai", row.id, field, "script");
    for (const row of o.originEpisodes) bindNumeric(row, "origin_episodes", "origin_episode", row.id, "bgm_id", "bgm");
    for (const row of o.originPages) bindNumeric(row, "origin_pages", "origin_page", row.id, "bgm_id", "bgm");
    for (const row of o.originBattles) { bindNumeric(row, "origin_battles", "origin_battle", row.id, "bgm_id", "bgm"); bindNumeric(row, "origin_battles", "origin_battle", row.id, "background_id", "origin_background"); }
    for (const row of o.sdMaps) bindNumeric(row, "sd_maps", "sd_map", row.id, "background_image_id", "sd_background_image");
    for (const row of o.sdArenas) bindNumeric(row, "sd_arenas", "sd_arena", row.id, "background_image_id", "sd_background_image");
    for (const row of o.referencedEnemyCards) bindNumeric(row, "cards", "enemy_card", row.id, "resource_id", "card_resource");
    bindings.sort((a, b) => a.source.table.localeCompare(b.source.table) || Number(a.source.rowId) - Number(b.source.rowId) || a.source.column.localeCompare(b.source.column));
    const apkEntries = new Set(apk.assetEntryPaths);
    const pathAssets = [...pathValues].sort().map(rawPath => { const baseApkLiteralEntryPath = apkEntries.has(rawPath) ? rawPath : null, prefixedPath = `assets/${rawPath}`, baseApkPrefixedCandidate = baseApkLiteralEntryPath === null && apkEntries.has(prefixedPath) ? { apkEntryPath: prefixedPath, status: "partial" as const, boundary: "assets_prefix_resolution_has_no_runtime_consumer_proof" as const } : null; return { assetKey: `database_path:${keyHash(rawPath)}`, rawPath, source: "database_path_column" as const, baseApkLiteralEntryStatus: baseApkLiteralEntryPath === null ? "absent_literal" as const : "present_literal" as const, baseApkLiteralEntryPath, baseApkPrefixedCandidate, deliveryStatus: baseApkLiteralEntryPath === null ? "unknown_requires_downloaded_container_or_endpoint" as const : "extractable_direct_from_base_apk" as const }; });
    const numericAssets = [...numericValues].sort((a, b) => a[0].localeCompare(b[0])).map(([assetKey, value]) => { const candidates = value.kind === "bgm" ? apk.assetEntryPaths.filter(path => new RegExp(`^assets/bgm/bgm_${String(Number(value.rawId)).padStart(3, "0")}\\.(acb|awb)$`).test(path)).map(apkEntryPath => ({ apkEntryPath, status: "partial" as const, boundary: "filename_pattern_candidate_no_runtime_consumer_proof" as const })) : []; return { assetKey, ...value, status: "partial" as const, bundledCandidates: candidates, missing: "validated_runtime_asset_manifest" as const }; });
    const representativeSamples = apk.samples.filter(value => value.exists && value.sizeBytes !== null && value.compressedSizeBytes !== null && value.sha256 !== null).map(value => ({ apkEntryPath: value.path, sizeBytes: value.sizeBytes!, compressedSizeBytes: value.compressedSizeBytes!, sha256: value.sha256!, status: "supported" as const }));
    return {
        schemaVersion: 1, contract: "dokkan-events-database-first-assets", contractVersion: "0.7.0", generatedAt: options.generatedAt, generatedAtPolicy: "pinned_to_source_snapshot_for_reproducible_bytes", sourceSnapshotVersion: options.sourceSnapshotVersion, sourceDatabaseSha256: options.sourceDatabaseSha256, sourceE5: { contractVersion: "0.6.0", sha256: options.sourceE5Sha256 }, sourceApk: { fileName: "dokkan-global-base.apk", sha256: options.sourceApkSha256, sizeBytes: options.sourceApkSizeBytes, entryCount: apk.entryCount, assetEntryCount: apk.assetEntryCount },
        pathAssets, numericAssets, bindings, apkAssetInventory: { extensionCounts: apk.assetExtensionCounts, representativeSamples }, downloadBoundary: { directDatabasePathPresentInBaseApkCount: pathAssets.filter(value => value.baseApkLiteralEntryStatus === "present_literal").length, directDatabasePathAbsentFromBaseApkCount: pathAssets.filter(value => value.baseApkLiteralEntryStatus === "absent_literal").length, bundledAssetEntryCount: apk.assetEntryCount, cpkContainerCount: apk.assetExtensionCounts[".cpk"] ?? 0, eventAssetEndpointStatus: "unknown", note: "base_apk_entries_are_extractable_event_paths_may_require_downloaded_cpk_or_external_endpoint" }, unusedAssetPathPatterns: o.unusedAssetPathPatterns.map(row => ({ sourceRowId: str(row.id), rawPattern: str(row.file_path_pattern), status: "unknown", boundary: "table_name_does_not_establish_download_or_exclusion_semantics" }))
    };
}

export function buildEventsE6Coverage(dataset: EventsE6Dataset, observation: EventsE6Observation): EventsE6Coverage {
    const pathKeys = new Set(dataset.pathAssets.map(value => value.assetKey)), numericKeys = new Set(dataset.numericAssets.map(value => value.assetKey)), allKeys = new Set([...pathKeys, ...numericKeys]), questIds = new Set(observation.questTargets.map(value => str(value.id))), zStageIds = new Set(observation.zBattleStages.map(value => str(value.id))), seriesIds = new Set(observation.originSeries.map(value => str(value.id))), episodeIds = new Set(observation.originEpisodes.map(value => str(value.id))), sdMapIds = new Set(observation.sdMaps.map(value => str(value.id)));
    let danglingIdCount = dataset.bindings.filter(value => !allKeys.has(value.assetKey)).length;
    for (const row of observation.questMaps) danglingIdCount += Number(row.quest_id !== null && !questIds.has(str(row.quest_id)));
    for (const row of observation.zBattleStageViews) danglingIdCount += Number(!zStageIds.has(str(row.z_battle_stage_id)));
    for (const row of observation.originEpisodes) danglingIdCount += Number(!seriesIds.has(str(row.origin_series_id)));
    for (const row of observation.originPages) danglingIdCount += Number(!episodeIds.has(str(row.origin_episode_id)));
    for (const row of observation.sdArenas) danglingIdCount += Number(!sdMapIds.has(str(row.sd_map_id)));
    const linkedCategoryIds = new Set(observation.linkedMissionCategoryIds.map(str)), joinedCategoryIds = new Set(observation.linkedMissionCategories.map(value => str(value.id))), referencedCardIds = new Set(observation.referencedEnemyCardIds.map(str)), joinedCardIds = new Set(observation.referencedEnemyCards.map(value => str(value.id)));
    danglingIdCount += [...linkedCategoryIds].filter(id => !joinedCategoryIds.has(id)).length + [...joinedCategoryIds].filter(id => !linkedCategoryIds.has(id)).length + [...referencedCardIds].filter(id => !joinedCardIds.has(id)).length + [...joinedCardIds].filter(id => !referencedCardIds.has(id)).length;
    const bindingsByEntityKind: Record<string, number> = {}; for (const value of dataset.bindings) bindingsByEntityKind[value.source.entityKind] = (bindingsByEntityKind[value.source.entityKind] ?? 0) + 1;
    return { schemaVersion: 1, pathAssetCount: dataset.pathAssets.length, numericAssetCount: dataset.numericAssets.length, bindingCount: dataset.bindings.length, bindingsByEntityKind: Object.fromEntries(Object.entries(bindingsByEntityKind).sort(([a], [b]) => a.localeCompare(b))), directBaseApkPathCount: dataset.pathAssets.filter(value => value.baseApkLiteralEntryStatus === "present_literal").length, absentBaseApkPathCount: dataset.pathAssets.filter(value => value.baseApkLiteralEntryStatus === "absent_literal").length, bundledCandidateCount: dataset.numericAssets.reduce((sum, value) => sum + value.bundledCandidates.length, 0) + dataset.pathAssets.filter(value => value.baseApkPrefixedCandidate !== null).length, representativeSampleCount: dataset.apkAssetInventory.representativeSamples.length, representativeSampleBytes: dataset.apkAssetInventory.representativeSamples.reduce((sum, value) => sum + value.sizeBytes, 0), danglingIdCount };
}
