import { createHash } from "crypto";
import { createReadStream, existsSync } from "fs";
import { mkdir, readFile, stat, writeFile } from "fs/promises";
import { resolve } from "path";
import { resolveEventsInputFile, resolveEventsOutputFiles } from "./events-artifact-path";
import { buildEventsE9Coverage, buildEventsE9Dataset } from "./events-e9-builder";
import { EventsE7Coverage, EventsE7Dataset, EventsE7Manifest, EventsE7Validation } from "./events-e7-contract";
import { EventsE8Coverage, EventsE8Manifest, EventsE8Registry, EventsE8Validation } from "./events-e8-contract";
import { EventsE9Manifest, EventsE9RefreshEvidence } from "./events-e9-contract";
import { validateEventsE9Dataset } from "./events-e9-validator";

const DEFAULT_DIRECTORY = resolve(process.cwd(), "data", "database-events"), MEMORY_LIMIT = 1024 * 1024 * 1024;
let peakWorkingSetBytes = 0;
function memory() { peakWorkingSetBytes = Math.max(peakWorkingSetBytes, process.memoryUsage().rss, process.resourceUsage().maxRSS * 1024); if (peakWorkingSetBytes > MEMORY_LIMIT) throw Error(`E9 memory limit exceeded ${peakWorkingSetBytes}`); }
const sha = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
async function fingerprint(path: string) { const metadata = await stat(path), hash = createHash("sha256"); await new Promise<void>((done, reject) => { const stream = createReadStream(path); stream.on("data", chunk => { hash.update(chunk); memory(); }); stream.on("error", reject); stream.on("end", done); }); return { sha256: hash.digest("hex"), sizeBytes: metadata.size, modifiedAtMs: metadata.mtimeMs }; }
function verify(bytes: Buffer, expected: { sha256: string; sizeBytes: number }, label: string) { if (bytes.byteLength !== expected.sizeBytes || sha(bytes) !== expected.sha256) throw Error(`E9 ${label} identity`); }
function sourcePath(name: string) { const adjacent = resolve(__dirname, name); return existsSync(adjacent) ? adjacent : resolve(__dirname, "..", "..", "database-events", name); }

export async function runEventsE9(options: { inputDir?: string; outputDir?: string } = {}) {
    peakWorkingSetBytes = 0;
    const inputDir = resolve(options.inputDir ?? DEFAULT_DIRECTORY), outputDir = resolve(options.outputDir ?? inputDir), e7Manifest = JSON.parse(await readFile(await resolveEventsInputFile(inputDir, "events-e7-manifest.json", "events-e7-manifest.json"), "utf8")) as EventsE7Manifest, e8ManifestBytes = await readFile(await resolveEventsInputFile(inputDir, "events-e8-manifest.json", "events-e8-manifest.json")), e8Manifest = JSON.parse(e8ManifestBytes.toString("utf8")) as EventsE8Manifest, refreshEvidenceBytes = await readFile(sourcePath("events-e9-refresh-evidence.json")), refreshEvidenceSha256 = sha(refreshEvidenceBytes), refreshEvidence = JSON.parse(refreshEvidenceBytes.toString("utf8")) as EventsE9RefreshEvidence;
    const [e7Path, e7CoveragePath, e7ValidationPath, e8Path, e8CoveragePath, e8ValidationPath, e8ReceiptPath] = await Promise.all([resolveEventsInputFile(inputDir, e7Manifest.fileName, "events-e7-shadow-parity.json"), resolveEventsInputFile(inputDir, e7Manifest.coverage?.fileName, "events-e7-coverage.json"), resolveEventsInputFile(inputDir, e7Manifest.validation?.fileName, "events-e7-validation.json"), resolveEventsInputFile(inputDir, e8Manifest.fileName, "events-sidecars.json"), resolveEventsInputFile(inputDir, e8Manifest.coverage?.fileName, "events-e8-coverage.json"), resolveEventsInputFile(inputDir, e8Manifest.validation?.fileName, "events-e8-validation.json"), resolveEventsInputFile(inputDir, e8Manifest.refreshReceipt?.fileName, "events-e8-refresh-receipt.json")]);
    const [e7Before, e7CoverageBytes, e7ValidationBytes, e8Before, e8CoverageBytes, e8ValidationBytes, e8ReceiptBytes] = await Promise.all([fingerprint(e7Path), readFile(e7CoveragePath), readFile(e7ValidationPath), fingerprint(e8Path), readFile(e8CoveragePath), readFile(e8ValidationPath), readFile(e8ReceiptPath)]); memory();
    if (e7Before.sha256 !== e7Manifest.sha256 || e7Before.sizeBytes !== e7Manifest.sizeBytes || e8Before.sha256 !== e8Manifest.sha256 || e8Before.sizeBytes !== e8Manifest.sizeBytes) throw Error("E9 payload identity");
    verify(e7CoverageBytes, e7Manifest.coverage, "E7 coverage"); verify(e7ValidationBytes, e7Manifest.validation, "E7 validation"); verify(e8CoverageBytes, e8Manifest.coverage, "E8 coverage"); verify(e8ValidationBytes, e8Manifest.validation, "E8 validation"); verify(e8ReceiptBytes, e8Manifest.refreshReceipt, "E8 receipt");
    const e7 = JSON.parse(await readFile(e7Path, "utf8")) as EventsE7Dataset, e7Coverage = JSON.parse(e7CoverageBytes.toString("utf8")) as EventsE7Coverage, e7Validation = JSON.parse(e7ValidationBytes.toString("utf8")) as EventsE7Validation, e8 = JSON.parse(await readFile(e8Path, "utf8")) as EventsE8Registry, e8Coverage = JSON.parse(e8CoverageBytes.toString("utf8")) as EventsE8Coverage, e8Validation = JSON.parse(e8ValidationBytes.toString("utf8")) as EventsE8Validation;
    if (e7Manifest.contractVersion !== "0.8.0" || e8Manifest.contractVersion !== "0.9.0" || !e7Validation.valid || !e7Validation.exactProjection || !e8Validation.valid || !e8Validation.exactProjection || e8Manifest.refreshProfileSha256 !== e8.refreshProfile.sha256) throw Error("E9 upstream validation");
    const e8Artifacts = { coverageSha256: sha(e8CoverageBytes), validationSha256: sha(e8ValidationBytes), receiptSha256: sha(e8ReceiptBytes), manifestSha256: sha(e8ManifestBytes) }, sources = { e7, e7Coverage, e7Sha256: e7Manifest.sha256, e8, e8Coverage, e8Sha256: e8Manifest.sha256, e8Artifacts, refreshEvidence, refreshEvidenceSha256 }, dataset = buildEventsE9Dataset(sources), coverage = buildEventsE9Coverage(dataset), validation = validateEventsE9Dataset(dataset, sources);
    if (!validation.valid) throw Error(`E9 validation ${JSON.stringify(validation.failures)}`);
    const e7After = await fingerprint(e7Path), e8After = await fingerprint(e8Path); if (JSON.stringify(e7Before) !== JSON.stringify(e7After) || JSON.stringify(e8Before) !== JSON.stringify(e8After)) throw Error("E9 read-only source guarantee");
    const payloadText = `${JSON.stringify(dataset, null, 2)}\n`, coverageText = `${JSON.stringify(coverage, null, 2)}\n`, validationText = `${JSON.stringify(validation, null, 2)}\n`;
    const manifest: EventsE9Manifest = { schemaVersion: 1, contractVersion: "1.0.0", generatedAt: dataset.generatedAt, generatedAtPolicy: dataset.generatedAtPolicy, sourceSnapshotVersion: dataset.sourceSnapshotVersion, fileName: "events-e9-readiness.json", compression: "none", sha256: sha(payloadText), sizeBytes: Buffer.byteLength(payloadText), sourceDatabaseSha256: dataset.sourceDatabaseSha256, sourceE7Sha256: dataset.sourceE7.sha256, sourceE8Sha256: dataset.sourceE8.sha256, refreshEvidenceSha256, coverage: { fileName: "events-e9-coverage.json", sha256: sha(coverageText), sizeBytes: Buffer.byteLength(coverageText) }, validation: { fileName: "events-e9-validation.json", sha256: sha(validationText), sizeBytes: Buffer.byteLength(validationText) } };
    await mkdir(outputDir, { recursive: true }); const outputs = await resolveEventsOutputFiles(outputDir, [manifest.fileName, manifest.coverage.fileName, manifest.validation.fileName, "events-e9-manifest.json"]); await Promise.all([writeFile(outputs.get(manifest.fileName)!, payloadText), writeFile(outputs.get(manifest.coverage.fileName)!, coverageText), writeFile(outputs.get(manifest.validation.fileName)!, validationText), writeFile(outputs.get("events-e9-manifest.json")!, `${JSON.stringify(manifest, null, 2)}\n`)]); memory();
    return { dataset, coverage, validation, manifest, peakWorkingSetBytes };
}

if (require.main === module) runEventsE9().then(value => console.log(JSON.stringify({ coverage: value.coverage, validation: value.validation, manifest: value.manifest, peakWorkingSetBytes: value.peakWorkingSetBytes }, null, 2))).catch(error => { console.error(error); process.exitCode = 1; });
