import { equal } from "assert";
import { buildEventsE9Coverage, buildEventsE9Dataset } from "./events-e9-builder";
import { validateEventsE9Dataset } from "./events-e9-validator";

const e7 = { sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db" } as any, e7Coverage = { byClassification: { agreement: 1, representation_gain: 1, confirmed_conflict: 0, unknown: 1, unjoinable: 1 }, confirmedConflictCount: 0, paginationByStatus: { supported: 1, partial: 3, unknown: 3 } } as any;
const gateFileNames = ["E0.json", "E1.json", "E2.json", "E3.json", "E4.json", "E5.json", "E6.json", "events-sidecars.json"], e8 = { generatedAt: "time", sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", refreshProfile: { sha256: "profile" }, sourceAnchors: { inventory: { fileName: gateFileNames[0], sha256: "e0" } }, sidecars: [1, 2, 3, 4, 5, 6].map(gate => ({ gate, payload: { fileName: gateFileNames[gate], sha256: `p${gate}` } })), delivery: { optional: true, defaultPipelineEnabled: false } } as any, e8Coverage = { sidecarCount: 6, totalPayloadBytes: 100, invalidValidationCount: 0, danglingIdCount: 0, sourceCoverage: { boss_mechanics: { requestedSupportedCount: 0, requestedPartialCount: 4, requestedUnknownCount: 5 }, asset_references: { pathAssetCount: 2, numericAssetCount: 3, bindingCount: 4, directBaseApkPathCount: 0, absentBaseApkPathCount: 2 }, rewards: { supportedItemReferenceCount: 8, unknownItemReferenceCount: 2 } } } as any;
const gateHashes = ["e0", "p1", "p2", "p3", "p4", "p5", "p6", "e8"], e8Artifacts = { coverageSha256: "c8", validationSha256: "v8", receiptSha256: "r8", manifestSha256: "m8" }, compared = [...gateFileNames.map((fileName, index) => ({ fileName, beforeSha256: gateHashes[index], afterSha256: gateHashes[index] })), { fileName: "events-e8-coverage.json", beforeSha256: "c8", afterSha256: "c8" }, { fileName: "events-e8-validation.json", beforeSha256: "v8", afterSha256: "v8" }, { fileName: "events-e8-refresh-receipt.json", beforeSha256: "r8", afterSha256: "r8" }, { fileName: "events-e8-manifest.json", beforeSha256: "m8", afterSha256: "m8" }], refreshEvidence = { schemaVersion: 1, profileId: "snapshot", refreshProfileSha256: "profile", sourceDatabaseSha256: "db", memoryLimitBytes: 1024, observedMaxPeakWorkingSetBytes: 800, fullRefreshByteIdentical: true, comparedArtifactCount: 12, comparedArtifacts: compared, gates: ["E0", "E1", "E2", "E3", "E4", "E5", "E6", "E8"].map((gate, index) => ({ gate, payloadFileName: gateFileNames[index], payloadSha256: gateHashes[index], peakWorkingSetBytes: (index + 1) * 100 })) } as any;
const sources = { e7, e7Coverage, e7Sha256: "e7", e8, e8Coverage, e8Sha256: "e8", e8Artifacts, refreshEvidence, refreshEvidenceSha256: "refresh" }, build = () => buildEventsE9Dataset(sources);

describe("events E9 readiness", () => {
    it("allows only disabled infrastructure and pinned optional generation", () => { const dataset = build(), coverage = buildEventsE9Coverage(dataset); equal(coverage.goCount, 2); equal(coverage.noGoCount, 6); equal(dataset.decisions.find(value => value.id === "replace_scraped_datasets")!.status, "NO_GO"); equal(validateEventsE9Dataset(dataset, sources).valid, true); });
    it("keeps every no-go actionable", () => { equal(build().decisions.filter(value => value.status === "NO_GO").every(value => value.exitConditions.length > 0), true); });
    it("rejects promotion of simulation without evidence", () => { const dataset = build(), simulation = dataset.decisions.find(value => value.id === "boss_damage_simulation")!; simulation.status = "GO"; const validation = validateEventsE9Dataset(dataset, sources); equal(validation.valid, false); equal(validation.decisionPolicyValid, false); });
    it("rejects conflicted source evidence", () => { const changed = { ...sources, e7Coverage: { ...e7Coverage, confirmedConflictCount: 1 } }; const dataset = buildEventsE9Dataset(changed); equal(validateEventsE9Dataset(dataset, changed).sourceEvidenceValid, false); });
    it("rejects a refresh peak at the memory limit", () => { const changedEvidence = { ...refreshEvidence, observedMaxPeakWorkingSetBytes: 1024, gates: refreshEvidence.gates.map((value: any, index: number) => index === 7 ? { ...value, peakWorkingSetBytes: 1024 } : value) }, changed = { ...sources, refreshEvidence: changedEvidence }; const dataset = buildEventsE9Dataset(changed); equal(validateEventsE9Dataset(dataset, changed).sourceEvidenceValid, false); });
    it("rejects a refresh artifact pair that does not match its current source hash", () => { const changedEvidence = { ...refreshEvidence, comparedArtifacts: refreshEvidence.comparedArtifacts.map((value: any, index: number) => index === 0 ? { ...value, beforeSha256: "stale", afterSha256: "stale" } : value) }, changed = { ...sources, refreshEvidence: changedEvidence }; const dataset = buildEventsE9Dataset(changed); equal(validateEventsE9Dataset(dataset, changed).sourceEvidenceValid, false); });
});
