"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = require("fs");
const path_1 = require("path");
const v8_1 = require("v8");
const capture_secret_scan_1 = require("../database-server-captures/capture-secret-scan");
const frontier_f6_readiness_1 = require("./frontier-f6-readiness");
const root = (0, path_1.resolve)(process.cwd());
if ((0, v8_1.getHeapStatistics)().heap_size_limit >= 1024 * 1024 * 1024)
    throw new Error("Frontier F6 requires a Node heap below 1 GiB");
const read = (path) => (0, fs_1.readFileSync)((0, path_1.resolve)(root, path), "utf8"), artifacts = [{ gate: "f0", fileName: "frontier-f0-inventory.json", text: read("data/database-frontier-captures/f0/frontier-f0-inventory.json") }, { gate: "f1", fileName: "frontier-f1-zstd-audit.json", text: read("data/database-frontier-captures/f1/frontier-f1-zstd-audit.json") }, { gate: "f2", fileName: "frontier-f2-sanitized-shapes.json", text: read("data/database-frontier-captures/f2/frontier-f2-sanitized-shapes.json") }, { gate: "f3", fileName: "frontier-f3-catalog.json", text: read("data/database-frontier-captures/f3/frontier-f3-catalog.json") }, { gate: "f4", fileName: "frontier-f4-observational-protocol.json", text: read("data/database-frontier-captures/f4/frontier-f4-observational-protocol.json") }, { gate: "f5", fileName: "frontier-f5-shadow-parity.json", text: read("data/database-frontier-captures/f5/frontier-f5-shadow-parity.json") }], f1 = JSON.parse(artifacts[1].text), f5 = JSON.parse(artifacts[5].text), fixtureText = read("database-frontier-captures/fixtures/frontier-synthetic-shapes.json"), memory = JSON.parse(read("database-frontier-captures/frontier-f6-memory-evidence.json")), dataset = (0, frontier_f6_readiness_1.buildFrontierF6)({ generatedAt: f5.generatedAt, f0: JSON.parse(read("data/database-frontier-captures/f0/frontier-f0-validation.json")), f1, f1Validation: JSON.parse(read("data/database-frontier-captures/f1/frontier-f1-validation.json")), f2: JSON.parse(read("data/database-frontier-captures/f2/frontier-f2-validation.json")), f3: JSON.parse(read("data/database-frontier-captures/f3/frontier-f3-validation.json")), f4: JSON.parse(read("data/database-frontier-captures/f4/frontier-f4-validation.json")), f5, f5Validation: JSON.parse(read("data/database-frontier-captures/f5/frontier-f5-validation.json")), artifactTexts: artifacts, fixtureText, memory }), validation = (0, frontier_f6_readiness_1.validateFrontierF6)(dataset), text = `${JSON.stringify(dataset, null, 2)}\n`, manifest = { schemaVersion: 1, contractVersion: dataset.contractVersion, generatedAt: dataset.generatedAt, fileName: "frontier-f6-readiness.json", sizeBytes: Buffer.byteLength(text), sha256: require("crypto").createHash("sha256").update(text).digest("hex") }, sourceManifest = { schemaVersion: 1, inputRoot: "frontier", captures: [{ captureId: "frontier-2026-08-10", path: "frontier.har" }] }, scan = (0, capture_secret_scan_1.scanTextsForSecrets)((0, capture_secret_scan_1.collectCaptureSensitiveValues)(sourceManifest, { frontier: "D:\\Dokkan\\har logs\\08-10" }), [...artifacts.map(value => ({ name: value.fileName, text: value.text })), { name: "frontier-f6-readiness.json", text }, { name: "frontier-synthetic-shapes.json", text: fixtureText }]);
if (!scan.valid)
    throw new Error("F6 secret scan failed");
const out = (0, path_1.resolve)(root, "data/database-frontier-captures/f6");
(0, fs_1.mkdirSync)(out, { recursive: true });
(0, fs_1.writeFileSync)((0, path_1.resolve)(out, "frontier-f6-readiness.json"), text);
(0, fs_1.writeFileSync)((0, path_1.resolve)(out, "frontier-f6-validation.json"), `${JSON.stringify(validation, null, 2)}\n`);
(0, fs_1.writeFileSync)((0, path_1.resolve)(out, "frontier-f6-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
(0, fs_1.writeFileSync)((0, path_1.resolve)(out, "frontier-f6-secret-scan.json"), `${JSON.stringify(scan, null, 2)}\n`);
process.stdout.write(`${JSON.stringify({ ...validation, secretScanValid: scan.valid, exactCapturedSecretMatches: scan.exactCapturedSecretMatches })}\n`);
//# sourceMappingURL=frontier-f6-run.js.map