"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert_1 = require("assert");
const integration_c5_builder_1 = require("./integration-c5-builder");
const integration_c5_validator_1 = require("./integration-c5-validator");
const integration_c5_evidence_1 = require("./integration-c5-evidence");
const evidence = { sourceSnapshotVersion: "snapshot", artifacts: { c1: { sha256: "1", sizeBytes: 1 }, c2: { sha256: "2", sizeBytes: 2 }, c3: { sha256: "3", sizeBytes: 3 }, c4Receipt: { sha256: "4", sizeBytes: 4 } }, coverage: { auditRuleCount: 10, supportedRuleCount: 10, sidecarStateCount: 5, supportedTimingCount: 8, unknownTimingCount: 2, shadowAgreementCount: 6, representationGainCount: 2, shadowUnknownCount: 1, unjoinableRuleCount: 1, confirmedConflictCount: 0, commonFirstPartyRuleIdentityCount: 0, unknownConditionCount: 10, unknownProbabilityCount: 10, unknownFinalHpCount: 10 }, refresh: { status: "compatible", exactEvidenceIdentity: true, readOnlySourceGuarantee: true } };
const fileChain = () => ({ c1Manifest: { sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", nativeRuntimeSha256: "elf", sha256: "1" }, c1Dataset: { sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", nativeRuntimeSha256: "elf" }, c2Manifest: { sourceSnapshotVersion: "snapshot", sourceAuditSidecarSha256: "1", sha256: "2", contractVersion: "1.0.0" }, c2Dataset: { sourceSnapshotVersion: "snapshot", sourceDatabaseSha256: "db", nativeRuntimeSha256: "elf", auditSidecar: { sha256: "1" } }, c3Manifest: { sourceSupportedSidecarSha256: "2", sha256: "3" }, c3Dataset: { sourceSupportedSidecar: { sha256: "2", contractVersion: "1.0.0" } }, c4Manifest: { compatibilityFile: "database-first-update-c4-compatibility.json", generatedAt: "time" }, c4Receipt: { generatedAt: "time", snapshotVersion: "snapshot", compatibilityReportSha256: "compat", inputs: { sourceDatabaseSha256: "db", nativeRuntimeSha256: "elf", schemaSha256: "schema" }, outputs: { c1Sha256: "1", c2Sha256: "2", c3Sha256: "3" } }, c4Compatibility: { status: "compatible", issues: [], snapshotVersion: "snapshot", sourceDatabase: { sha256: "db", schemaSha256: "schema" }, nativeRuntime: { sha256: "elf" } }, compatibilityFileSha256: "compat" });
describe("database-first integration C5 adoption readiness", () => {
    it("allows only additive infrastructure and pinned optional generation", () => { const value = (0, integration_c5_builder_1.buildIntegrationC5Readiness)("time", evidence); (0, assert_1.equal)(value.decisions.find(item => item.stage === "merge_infrastructure")?.decision, "GO"); (0, assert_1.equal)(value.decisions.find(item => item.stage === "optional_production_generation")?.decision, "GO"); });
    it("keeps publication, Android and combat authority blocked", () => { const value = (0, integration_c5_builder_1.buildIntegrationC5Readiness)("time", evidence); for (const stage of ["r2_publication", "android_shadow_consumption", "partial_combat_calculation", "full_simulation"])
        (0, assert_1.equal)(value.decisions.find(item => item.stage === stage)?.decision, "NO_GO"); });
    it("rejects decision and evidence mutations", () => { const value = (0, integration_c5_builder_1.buildIntegrationC5Readiness)("time", evidence), mutation = JSON.parse(JSON.stringify(value)); mutation.decisions[2].decision = "GO"; (0, assert_1.equal)((0, integration_c5_validator_1.validateIntegrationC5Readiness)(value, "time", evidence).valid, true); (0, assert_1.equal)((0, integration_c5_validator_1.validateIntegrationC5Readiness)(mutation, "time", evidence).valid, false); });
    it("refuses readiness without exact compatible read-only refresh evidence", () => { const changed = JSON.parse(JSON.stringify(evidence)); changed.refresh.exactEvidenceIdentity = false; let failed = false; try {
        (0, integration_c5_builder_1.buildIntegrationC5Readiness)("time", changed);
    }
    catch {
        failed = true;
    } (0, assert_1.equal)(failed, true); });
    it("rejects an isolated C1 manifest snapshot mutation", () => { const chain = fileChain(); (0, assert_1.equal)((0, integration_c5_evidence_1.validateIntegrationC5FileChain)(chain).length, 0); chain.c1Manifest.sourceSnapshotVersion = "forged"; (0, assert_1.equal)((0, integration_c5_evidence_1.validateIntegrationC5FileChain)(chain).some(issue => issue.includes("C1")), true); });
    it("rejects a compatibility report whose bytes no longer match the C4 receipt", () => { const chain = fileChain(); chain.compatibilityFileSha256 = "changed"; (0, assert_1.equal)((0, integration_c5_evidence_1.validateIntegrationC5FileChain)(chain).some(issue => issue.includes("compatibility")), true); });
});
//# sourceMappingURL=integration-c5-builder.spec.js.map