import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { getHeapStatistics } from "v8";
import { CaptureH0Dataset, CaptureInputManifest } from "./capture-h0-contract";
import { CaptureH3Dataset } from "./capture-h3-contract";
import { validateCaptureH3 } from "./capture-h3-schedules";
import { CaptureH4Dataset } from "./capture-h4-contract";
import { validateCaptureH4 } from "./capture-h4-gashas";
import { CaptureH5Dataset } from "./capture-h5-contract";
import { validateCaptureH5 } from "./capture-h5-missions";
import { CaptureH6Dataset } from "./capture-h6-contract";
import { validateCaptureH6 } from "./capture-h6-assets";
import { captureH7LocalLineage, CaptureH7SourceLock, loadCaptureH7ExternalInputs } from "./capture-h7-inputs";
import { buildCaptureH7, validateCaptureH7 } from "./capture-h7-shadow-readiness";
import { collectCaptureSensitiveValues, scanTextsForSecrets } from "./capture-secret-scan";

const repositoryRoot = resolve(process.cwd());
if (JSON.parse(readFileSync(resolve(repositoryRoot, "package.json"), "utf8"))?.name !== "dokkan-web-scraper") throw new Error("H7 must run from the repository root");
if (getHeapStatistics().heap_size_limit >= 1024 * 1024 * 1024) throw new Error("H7 requires a Node heap below 1 GiB");
const readLocal = <T>(relativePath: string): { value: T; text: string } => { const text = readFileSync(resolve(repositoryRoot, relativePath), "utf8"); return { value: JSON.parse(text) as T, text }; };
const h0File = readLocal<CaptureH0Dataset>("data/database-server-captures/h0/capture-h0-inventory.json"), h3File = readLocal<CaptureH3Dataset>("data/database-server-captures/h3/capture-h3-schedules.json"), h4File = readLocal<CaptureH4Dataset>("data/database-server-captures/h4/capture-h4-gashas.json"), h5File = readLocal<CaptureH5Dataset>("data/database-server-captures/h5/capture-h5-mission-boards.json"), h6File = readLocal<CaptureH6Dataset>("data/database-server-captures/h6/capture-h6-assets.json");
const h0 = h0File.value, h3 = h3File.value, h4 = h4File.value, h5 = h5File.value, h6 = h6File.value;
if (!validateCaptureH3(h3, h0).valid || !validateCaptureH4(h4, h0).valid || !validateCaptureH5(h5, h0).valid || !validateCaptureH6(h6, h0).valid) throw new Error("H7 capture sidecar validation failed");
const sourceLockFile = readLocal<CaptureH7SourceLock>("database-server-captures/capture-h7-source-lock.json");
const external = loadCaptureH7ExternalInputs("D:\\Dokkan\\DokkanWebScraper\\data", sourceLockFile.value);
const localLineage = [captureH7LocalLineage("h0", "data/database-server-captures/h0/capture-h0-inventory.json", h0File.text, h0.contract, h0.contractVersion), captureH7LocalLineage("h3", "data/database-server-captures/h3/capture-h3-schedules.json", h3File.text, h3.contract, h3.contractVersion), captureH7LocalLineage("h4", "data/database-server-captures/h4/capture-h4-gashas.json", h4File.text, h4.contract, h4.contractVersion), captureH7LocalLineage("h5", "data/database-server-captures/h5/capture-h5-mission-boards.json", h5File.text, h5.contract, h5.contractVersion), captureH7LocalLineage("h6", "data/database-server-captures/h6/capture-h6-assets.json", h6File.text, h6.contract, h6.contractVersion)];
const sourceLockSha256 = captureH7LocalLineage("source_lock", "database-server-captures/capture-h7-source-lock.json", sourceLockFile.text, sourceLockFile.value.contract, sourceLockFile.value.contractVersion).artifactSha256;
const dataset = buildCaptureH7(h0.generatedAt, sourceLockSha256, external.inputs, [...external.lineage, ...localLineage], h3, h4, h5, h6), validation = validateCaptureH7(dataset), outputText = `${JSON.stringify(dataset, null, 2)}\n`;
const manifest = JSON.parse(readFileSync(resolve(repositoryRoot, "database-server-captures", "capture-input-manifest.json"), "utf8")) as CaptureInputManifest, roots = { "dokkan-local-captures": "D:\\Dokkan" };
const scan = scanTextsForSecrets(collectCaptureSensitiveValues(manifest, roots), [{ name: "capture-h7-shadow-readiness.json", text: outputText }]); if (!scan.valid) throw new Error(`H7 secret scan failed for ${scan.failingTargets.length} target(s)`);
const outputDirectory = resolve(repositoryRoot, "data", "database-server-captures", "h7"); mkdirSync(outputDirectory, { recursive: true });
writeFileSync(resolve(outputDirectory, "capture-h7-shadow-readiness.json"), outputText); writeFileSync(resolve(outputDirectory, "capture-h7-validation.json"), `${JSON.stringify(validation, null, 2)}\n`); writeFileSync(resolve(outputDirectory, "capture-h7-secret-scan.json"), `${JSON.stringify(scan, null, 2)}\n`);
process.stdout.write(`${JSON.stringify({ contract: dataset.contract, contractVersion: dataset.contractVersion, sourceCount: validation.sourceCount, comparisonCount: validation.comparisonCount, comparisonCellTotals: validation.comparisonCellTotals, decisions: Object.fromEntries(dataset.decisions.map(value => [value.key, value.status])), secretScanValid: scan.valid })}\n`);
