import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { getHeapStatistics } from "v8";
import { CaptureInputManifest } from "./capture-h0-contract";
import { validateCaptureH8 } from "./capture-h8-audit";
import { CaptureH8Dataset } from "./capture-h8-contract";
import { validateCaptureH9 } from "./capture-h9-schemas";
import { CaptureH9Dataset } from "./capture-h9-contract";
import { buildCaptureH10, validateCaptureH10 } from "./capture-h10-domains";
import { collectCaptureSensitiveValues, scanTextsForSecrets } from "./capture-secret-scan";

const root = resolve(process.cwd());
if (getHeapStatistics().heap_size_limit >= 1024 * 1024 * 1024) throw new Error("H10 requires a Node heap below 1 GiB");
const manifest = JSON.parse(readFileSync(resolve(root, "database-server-captures/capture-h8-input-manifest.json"), "utf8")) as CaptureInputManifest;
const roots = { "dokkan-local-captures-0810": "D:\\Dokkan\\har logs\\08-10" };
const h8Text = readFileSync(resolve(root, "data/database-server-captures/h8/capture-h8-inventory.json"), "utf8");
const h8 = JSON.parse(h8Text) as CaptureH8Dataset;
const h9Text = readFileSync(resolve(root, "data/database-server-captures/h9/capture-h9-observed-schemas.json"), "utf8");
const h9 = JSON.parse(h9Text) as CaptureH9Dataset;
if (!validateCaptureH8(h8, manifest, roots).valid || !validateCaptureH9(h9, manifest, roots, h8, h8Text).valid) throw new Error("H10 upstream validation failed");
const dataset = buildCaptureH10(manifest, roots, h9, h9Text);
const validation = validateCaptureH10(dataset, manifest, roots, h9, h9Text);
const text = `${JSON.stringify(dataset, null, 2)}\n`;
const scan = scanTextsForSecrets(collectCaptureSensitiveValues(manifest, roots), [{ name: "capture-h10-domains.json", text }]);
if (!scan.valid) throw new Error("H10 secret scan failed");
const output = resolve(root, "data/database-server-captures/h10");
mkdirSync(output, { recursive: true });
writeFileSync(resolve(output, "capture-h10-domains.json"), text);
writeFileSync(resolve(output, "capture-h10-validation.json"), `${JSON.stringify(validation, null, 2)}\n`);
writeFileSync(resolve(output, "capture-h10-secret-scan.json"), `${JSON.stringify(scan, null, 2)}\n`);
process.stdout.write(`${JSON.stringify({ ...validation, crashBoundary: dataset.crashBoundary, secretScanValid: scan.valid })}\n`);
