export type CaptureH9Scope = "global_product" | "account_scoped" | "mixed" | "authentication" | "cdn" | "unknown";
export type CaptureH9Disposition = "json" | "invalid_json" | "not_modified" | "body_absent" | "non_json" | "encoded" | "oversized";
export interface CaptureH9Field { path: string; type: "array" | "object" | "string" | "number" | "boolean" | "null"; state: "value" | "empty_array" | "empty_object" | "empty_string" | "null"; }
export interface CaptureH9Body { disposition: CaptureH9Disposition; fields: CaptureH9Field[]; }
export interface CaptureH9Observation { captureId: string; entryIndex: number; method: string; normalizedPath: string; status: number; scope: CaptureH9Scope; request: CaptureH9Body; response: CaptureH9Body; validatorHeaderNames: string[]; cacheRelation: null | { priorEntryIndex: number; proof: "exact_url_and_etag" | "exact_url_and_last_modified"; }; }
export interface CaptureH9SchemaField { path: string; types: CaptureH9Field["type"][]; states: CaptureH9Field["state"][]; presentCount: number; absentCount: number; provenance: Array<{ captureId: string; entryIndex: number; }>; }
export interface CaptureH9RouteSchema { method: string; normalizedPath: string; scope: CaptureH9Scope; side: "request" | "response"; observationCount: number; jsonBodyCount: number; notModifiedCount: number; bodyAbsentCount: number; otherBodyCount: number; fields: CaptureH9SchemaField[]; paginationFieldPaths: string[]; scheduleFieldPaths: string[]; availabilityFieldPaths: string[]; idFieldPaths: string[]; }
export interface CaptureH9Dataset { schemaVersion: 1; contract: "dokkan-official-capture-observed-schemas"; contractVersion: "0.10.0"; generatedAt: string; generatedAtPolicy: "inherits_h8_capture_timestamp"; collectionMode: "offline_local_har_no_requests"; productionMutation: false; defaultEnabled: false; authority: "schema_and_cache_relation_evidence_only_values_omitted"; h8ArtifactSha256: string; h8ArtifactSizeBytes: number; observations: CaptureH9Observation[]; routeSchemas: CaptureH9RouteSchema[]; }
export interface CaptureH9Validation { schemaVersion: 1; valid: boolean; observationCount: number; routeSchemaCount: number; jsonObservationCount: number; notModifiedCount: number; provedCacheRelationCount: number; failures: string[]; }
