"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const assert = require("assert");
const assets_builder_1 = require("./assets-builder");
const assets_validator_1 = require("./assets-validator");
describe("database character assets", () => {
    it("rejects a claimed local file or delivery", () => { const dataset = { schemaVersion: 1, contract: "dokkan-database-characters-assets", contractVersion: "1.0.0", policy: { endpointsDiscovered: false, catalogsDownloaded: false, resourceBundleNotClaimedAsPortraitOrCardArt: true, rarityTypeFrameMapping: "unknown", entranceAnimationGrouping: "unknown", domainAnimationGrouping: "unknown", deliveryOwnedElsewhere: true }, rawRows: [], references: [{ referenceId: "1", cardId: "1", role: "card_resource_bundle", firstPartyValue: "1", source: { table: "cards", rowId: "1", column: "resource_id", columns: ["resource_id"] }, assetKey: { value: "x", kind: "derived_from_first_party_id" }, localFile: { status: "proved" }, delivery: "known" }], gaps: [], formResourceAudit: { relationTargetCount: 0, unresolvedTargetCount: 0 } }; const coverage = { ...(0, assets_builder_1.buildDatabaseCharacterAssetsCoverage)(dataset), missingCardResourceCount: 0 }; assert((0, assets_validator_1.validateDatabaseCharacterAssetsDataset)(dataset, coverage).failures.includes("reference provenance")); });
    it("rejects a missing special-view target", () => { const dataset = { schemaVersion: 1, contract: "dokkan-database-characters-assets", contractVersion: "1.0.0", policy: { endpointsDiscovered: false, catalogsDownloaded: false, resourceBundleNotClaimedAsPortraitOrCardArt: true, rarityTypeFrameMapping: "unknown", entranceAnimationGrouping: "unknown", domainAnimationGrouping: "unknown", deliveryOwnedElsewhere: true }, rawRows: [{ values: { id: 1, card_id: 1, view_id: 9 }, provenance: { table: "card_specials", rowId: "1", columns: ["id", "card_id", "view_id"] } }], references: [{ referenceId: "v", cardId: "1", role: "super_view", firstPartyValue: "9", source: { table: "card_specials", rowId: "1", column: "view_id" }, assetKey: { value: "super_view:9", kind: "derived_from_first_party_id" }, localFile: { status: "unknown_no_compatible_local_asset_catalog" }, delivery: "unknown_owned_by_server_campaign" }], gaps: Array.from({ length: 5759 }, (_, index) => ({ gapId: String(index), cardId: String(index), role: "card_resource_bundle", reason: "missing_resource_id", source: { table: "cards", rowId: String(index), column: "resource_id", columns: ["resource_id"] } })), formResourceAudit: { relationTargetCount: 0, unresolvedTargetCount: 0 } }; const coverage = (0, assets_builder_1.buildDatabaseCharacterAssetsCoverage)(dataset); assert.strictEqual(coverage.missingSpecialViewCount, 1); assert((0, assets_validator_1.validateDatabaseCharacterAssetsDataset)(dataset, coverage).failures.includes("join, delivery or identity")); });
});
//# sourceMappingURL=assets-builder.spec.js.map